# AUTO-GENERATED by packages/modelparams-python/scripts/codegen.ts.
# Do not edit by hand; the YAML catalog under /models is the source of truth.

# ruff: noqa: F401

from typing import Annotated, Literal

from pydantic import ConfigDict, Field
from typing_extensions import TypedDict

_PARAMS_CONFIG = ConfigDict(strict=True, extra="forbid")

Deepseek_V3_2Params = TypedDict(
    "Deepseek_V3_2Params",
    {
        "max_completion_tokens": Annotated[int, Field(ge=1)],
        "temperature": Annotated[float, Field(ge=0, le=1.9)],
        "top_p": Annotated[float, Field(ge=0, le=1)],
        "extra_body.top_k": Annotated[int, Field(ge=0)],
        "extra_body.enable_thinking": bool,
        "extra_body.thinking_budget": Annotated[int, Field(ge=1)],
    },
    total=False,
)
setattr(Deepseek_V3_2Params, "__pydantic_config__", _PARAMS_CONFIG)

Deepseek_V4_FlashParams = TypedDict(
    "Deepseek_V4_FlashParams",
    {
        "max_completion_tokens": Annotated[int, Field(ge=1)],
        "temperature": Annotated[float, Field(ge=0, le=1.9)],
        "top_p": Annotated[float, Field(ge=0, le=1)],
        "extra_body.top_k": Annotated[int, Field(ge=0)],
        "extra_body.enable_thinking": bool,
        "extra_body.thinking_budget": Annotated[int, Field(ge=1)],
    },
    total=False,
)
setattr(Deepseek_V4_FlashParams, "__pydantic_config__", _PARAMS_CONFIG)

Deepseek_V4_Flash_0731Params = TypedDict(
    "Deepseek_V4_Flash_0731Params",
    {
        "max_completion_tokens": Annotated[int, Field(ge=1)],
        "temperature": Annotated[float, Field(ge=0, le=1.9)],
        "top_p": Annotated[float, Field(ge=0, le=1)],
        "extra_body.top_k": Annotated[int, Field(ge=0)],
        "extra_body.enable_thinking": bool,
        "extra_body.thinking_budget": Annotated[int, Field(ge=1)],
    },
    total=False,
)
setattr(Deepseek_V4_Flash_0731Params, "__pydantic_config__", _PARAMS_CONFIG)

Deepseek_V4_ProParams = TypedDict(
    "Deepseek_V4_ProParams",
    {
        "max_completion_tokens": Annotated[int, Field(ge=1)],
        "temperature": Annotated[float, Field(ge=0, le=1.9)],
        "top_p": Annotated[float, Field(ge=0, le=1)],
        "extra_body.top_k": Annotated[int, Field(ge=0)],
        "extra_body.enable_thinking": bool,
        "extra_body.thinking_budget": Annotated[int, Field(ge=1)],
    },
    total=False,
)
setattr(Deepseek_V4_ProParams, "__pydantic_config__", _PARAMS_CONFIG)

Deepseek_V4_Pro_0813Params = TypedDict(
    "Deepseek_V4_Pro_0813Params",
    {
        "max_completion_tokens": Annotated[int, Field(ge=1)],
        "temperature": Annotated[float, Field(ge=0, le=1.9)],
        "top_p": Annotated[float, Field(ge=0, le=1)],
        "extra_body.top_k": Annotated[int, Field(ge=0)],
        "extra_body.enable_thinking": bool,
        "extra_body.thinking_budget": Annotated[int, Field(ge=1)],
    },
    total=False,
)
setattr(Deepseek_V4_Pro_0813Params, "__pydantic_config__", _PARAMS_CONFIG)

Deepseek_V4_1_FlashParams = TypedDict(
    "Deepseek_V4_1_FlashParams",
    {
        "max_completion_tokens": Annotated[int, Field(ge=1)],
        "temperature": Annotated[float, Field(ge=0, le=1.9)],
        "top_p": Annotated[float, Field(ge=0, le=1)],
        "extra_body.top_k": Annotated[int, Field(ge=0)],
        "extra_body.enable_thinking": bool,
        "extra_body.thinking_budget": Annotated[int, Field(ge=1)],
    },
    total=False,
)
setattr(Deepseek_V4_1_FlashParams, "__pydantic_config__", _PARAMS_CONFIG)

Glm_5_1Params = TypedDict(
    "Glm_5_1Params",
    {
        "max_completion_tokens": Annotated[int, Field(ge=1)],
        "temperature": Annotated[float, Field(ge=0, le=1.9)],
        "top_p": Annotated[float, Field(ge=0, le=1)],
        "extra_body.top_k": Annotated[int, Field(ge=0)],
        "extra_body.enable_thinking": bool,
        "extra_body.thinking_budget": Annotated[int, Field(ge=1)],
    },
    total=False,
)
setattr(Glm_5_1Params, "__pydantic_config__", _PARAMS_CONFIG)

Glm_5_2Params = TypedDict(
    "Glm_5_2Params",
    {
        "max_completion_tokens": Annotated[int, Field(ge=1)],
        "temperature": Annotated[float, Field(ge=0, le=1.9)],
        "top_p": Annotated[float, Field(ge=0, le=1)],
        "extra_body.top_k": Annotated[int, Field(ge=0)],
        "extra_body.enable_thinking": bool,
        "extra_body.thinking_budget": Annotated[int, Field(ge=1)],
    },
    total=False,
)
setattr(Glm_5_2Params, "__pydantic_config__", _PARAMS_CONFIG)

Glm_5_2_Fast_PreviewParams = TypedDict(
    "Glm_5_2_Fast_PreviewParams",
    {
        "max_completion_tokens": Annotated[int, Field(ge=1)],
        "temperature": Annotated[float, Field(ge=0, le=1.9)],
        "top_p": Annotated[float, Field(ge=0, le=1)],
        "extra_body.top_k": Annotated[int, Field(ge=0)],
        "extra_body.enable_thinking": bool,
        "extra_body.thinking_budget": Annotated[int, Field(ge=1)],
    },
    total=False,
)
setattr(Glm_5_2_Fast_PreviewParams, "__pydantic_config__", _PARAMS_CONFIG)

Glm_5_3Params = TypedDict(
    "Glm_5_3Params",
    {
        "max_completion_tokens": Annotated[int, Field(ge=1)],
        "temperature": Annotated[float, Field(ge=0, le=1.9)],
        "top_p": Annotated[float, Field(ge=0, le=1)],
        "extra_body.top_k": Annotated[int, Field(ge=0)],
        "extra_body.enable_thinking": bool,
        "extra_body.thinking_budget": Annotated[int, Field(ge=1)],
    },
    total=False,
)
setattr(Glm_5_3Params, "__pydantic_config__", _PARAMS_CONFIG)

Glm_5_3_PrimeParams = TypedDict(
    "Glm_5_3_PrimeParams",
    {
        "max_completion_tokens": Annotated[int, Field(ge=1)],
        "temperature": Annotated[float, Field(ge=0, le=1.9)],
        "top_p": Annotated[float, Field(ge=0, le=1)],
        "extra_body.top_k": Annotated[int, Field(ge=0)],
        "extra_body.enable_thinking": bool,
        "extra_body.thinking_budget": Annotated[int, Field(ge=1)],
    },
    total=False,
)
setattr(Glm_5_3_PrimeParams, "__pydantic_config__", _PARAMS_CONFIG)

Kimi_K2_7_CodeParams = TypedDict(
    "Kimi_K2_7_CodeParams",
    {
        "max_completion_tokens": Annotated[int, Field(ge=1)],
        "temperature": Annotated[float, Field(ge=0, le=1.9)],
        "top_p": Annotated[float, Field(ge=0, le=1)],
        "extra_body.top_k": Annotated[int, Field(ge=0)],
        "extra_body.enable_thinking": bool,
        "extra_body.thinking_budget": Annotated[int, Field(ge=1)],
    },
    total=False,
)
setattr(Kimi_K2_7_CodeParams, "__pydantic_config__", _PARAMS_CONFIG)

Kimi_K3Params = TypedDict(
    "Kimi_K3Params",
    {
        "max_completion_tokens": Annotated[int, Field(ge=1)],
        "temperature": Annotated[float, Field(ge=0, le=1.9)],
        "top_p": Annotated[float, Field(ge=0, le=1)],
        "extra_body.top_k": Annotated[int, Field(ge=0)],
        "extra_body.enable_thinking": bool,
        "extra_body.thinking_budget": Annotated[int, Field(ge=1)],
    },
    total=False,
)
setattr(Kimi_K3Params, "__pydantic_config__", _PARAMS_CONFIG)

Qvq_MaxParams = TypedDict(
    "Qvq_MaxParams",
    {
        "max_completion_tokens": Annotated[int, Field(ge=1)],
        "temperature": Annotated[float, Field(ge=0, le=1.9)],
        "top_p": Annotated[float, Field(ge=0, le=1)],
        "extra_body.top_k": Annotated[int, Field(ge=0)],
        "extra_body.enable_thinking": bool,
        "extra_body.thinking_budget": Annotated[int, Field(ge=1)],
    },
    total=False,
)
setattr(Qvq_MaxParams, "__pydantic_config__", _PARAMS_CONFIG)

Qwen_Coder_PlusParams = TypedDict(
    "Qwen_Coder_PlusParams",
    {
        "max_tokens": Annotated[int, Field(ge=1)],
        "temperature": Annotated[float, Field(ge=0, le=1.9)],
        "top_p": Annotated[float, Field(ge=0, le=1)],
        "extra_body.top_k": Annotated[int, Field(ge=1)],
        "extra_body.chat_template_kwargs.enable_thinking": bool,
    },
    total=False,
)
setattr(Qwen_Coder_PlusParams, "__pydantic_config__", _PARAMS_CONFIG)

Qwen_FlashParams = TypedDict(
    "Qwen_FlashParams",
    {
        "max_tokens": Annotated[int, Field(ge=1)],
        "temperature": Annotated[float, Field(ge=0, le=1.9)],
        "top_p": Annotated[float, Field(ge=0, le=1)],
        "extra_body.top_k": Annotated[int, Field(ge=1)],
        "extra_body.chat_template_kwargs.enable_thinking": bool,
    },
    total=False,
)
setattr(Qwen_FlashParams, "__pydantic_config__", _PARAMS_CONFIG)

Qwen_Flash_CharacterParams = TypedDict(
    "Qwen_Flash_CharacterParams",
    {
        "max_tokens": Annotated[int, Field(ge=1)],
        "temperature": Annotated[float, Field(ge=0, le=1.9)],
        "top_p": Annotated[float, Field(ge=0, le=1)],
        "extra_body.top_k": Annotated[int, Field(ge=1)],
        "extra_body.chat_template_kwargs.enable_thinking": bool,
    },
    total=False,
)
setattr(Qwen_Flash_CharacterParams, "__pydantic_config__", _PARAMS_CONFIG)

Qwen_MaxParams = TypedDict(
    "Qwen_MaxParams",
    {
        "max_tokens": Annotated[int, Field(ge=1)],
        "temperature": Annotated[float, Field(ge=0, le=1.9)],
        "top_p": Annotated[float, Field(ge=0, le=1)],
        "extra_body.top_k": Annotated[int, Field(ge=1)],
        "extra_body.chat_template_kwargs.enable_thinking": bool,
    },
    total=False,
)
setattr(Qwen_MaxParams, "__pydantic_config__", _PARAMS_CONFIG)

Qwen_PlusParams = TypedDict(
    "Qwen_PlusParams",
    {
        "max_tokens": Annotated[int, Field(ge=1)],
        "temperature": Annotated[float, Field(ge=0, le=1.9)],
        "top_p": Annotated[float, Field(ge=0, le=1)],
        "extra_body.top_k": Annotated[int, Field(ge=1)],
        "extra_body.chat_template_kwargs.enable_thinking": bool,
    },
    total=False,
)
setattr(Qwen_PlusParams, "__pydantic_config__", _PARAMS_CONFIG)

Qwen_Plus_CharacterParams = TypedDict(
    "Qwen_Plus_CharacterParams",
    {
        "max_tokens": Annotated[int, Field(ge=1)],
        "temperature": Annotated[float, Field(ge=0, le=1.9)],
        "top_p": Annotated[float, Field(ge=0, le=1)],
        "extra_body.top_k": Annotated[int, Field(ge=1)],
        "extra_body.chat_template_kwargs.enable_thinking": bool,
    },
    total=False,
)
setattr(Qwen_Plus_CharacterParams, "__pydantic_config__", _PARAMS_CONFIG)

Qwen_Plus_LatestParams = TypedDict(
    "Qwen_Plus_LatestParams",
    {
        "max_tokens": Annotated[int, Field(ge=1)],
        "temperature": Annotated[float, Field(ge=0, le=1.9)],
        "top_p": Annotated[float, Field(ge=0, le=1)],
        "extra_body.top_k": Annotated[int, Field(ge=1)],
        "extra_body.chat_template_kwargs.enable_thinking": bool,
    },
    total=False,
)
setattr(Qwen_Plus_LatestParams, "__pydantic_config__", _PARAMS_CONFIG)

Qwen_TurboParams = TypedDict(
    "Qwen_TurboParams",
    {
        "max_tokens": Annotated[int, Field(ge=1)],
        "temperature": Annotated[float, Field(ge=0, le=1.9)],
        "top_p": Annotated[float, Field(ge=0, le=1)],
        "extra_body.top_k": Annotated[int, Field(ge=1)],
        "extra_body.chat_template_kwargs.enable_thinking": bool,
    },
    total=False,
)
setattr(Qwen_TurboParams, "__pydantic_config__", _PARAMS_CONFIG)

Qwen_Vl_MaxParams = TypedDict(
    "Qwen_Vl_MaxParams",
    {
        "max_tokens": Annotated[int, Field(ge=1)],
        "temperature": Annotated[float, Field(ge=0, le=1.9)],
        "top_p": Annotated[float, Field(ge=0, le=1)],
        "extra_body.top_k": Annotated[int, Field(ge=1)],
        "extra_body.chat_template_kwargs.enable_thinking": bool,
    },
    total=False,
)
setattr(Qwen_Vl_MaxParams, "__pydantic_config__", _PARAMS_CONFIG)

Qwen_Vl_PlusParams = TypedDict(
    "Qwen_Vl_PlusParams",
    {
        "max_tokens": Annotated[int, Field(ge=1)],
        "temperature": Annotated[float, Field(ge=0, le=1.9)],
        "top_p": Annotated[float, Field(ge=0, le=1)],
        "extra_body.top_k": Annotated[int, Field(ge=1)],
        "extra_body.chat_template_kwargs.enable_thinking": bool,
    },
    total=False,
)
setattr(Qwen_Vl_PlusParams, "__pydantic_config__", _PARAMS_CONFIG)

Qwen3_14bParams = TypedDict(
    "Qwen3_14bParams",
    {
        "max_tokens": Annotated[int, Field(ge=1)],
        "temperature": Annotated[float, Field(ge=0, le=1.9)],
        "top_p": Annotated[float, Field(ge=0, le=1)],
        "extra_body.top_k": Annotated[int, Field(ge=1)],
        "extra_body.chat_template_kwargs.enable_thinking": bool,
    },
    total=False,
)
setattr(Qwen3_14bParams, "__pydantic_config__", _PARAMS_CONFIG)

Qwen3_235b_A22bParams = TypedDict(
    "Qwen3_235b_A22bParams",
    {
        "max_tokens": Annotated[int, Field(ge=1)],
        "temperature": Annotated[float, Field(ge=0, le=1.9)],
        "top_p": Annotated[float, Field(ge=0, le=1)],
        "extra_body.top_k": Annotated[int, Field(ge=1)],
        "extra_body.chat_template_kwargs.enable_thinking": bool,
    },
    total=False,
)
setattr(Qwen3_235b_A22bParams, "__pydantic_config__", _PARAMS_CONFIG)

Qwen3_235b_A22b_Instruct_2507Params = TypedDict(
    "Qwen3_235b_A22b_Instruct_2507Params",
    {
        "max_tokens": Annotated[int, Field(ge=1)],
        "temperature": Annotated[float, Field(ge=0, le=1.9)],
        "top_p": Annotated[float, Field(ge=0, le=1)],
        "extra_body.top_k": Annotated[int, Field(ge=1)],
        "extra_body.chat_template_kwargs.enable_thinking": bool,
    },
    total=False,
)
setattr(Qwen3_235b_A22b_Instruct_2507Params, "__pydantic_config__", _PARAMS_CONFIG)

Qwen3_235b_A22b_Thinking_2507Params = TypedDict(
    "Qwen3_235b_A22b_Thinking_2507Params",
    {
        "max_tokens": Annotated[int, Field(ge=1)],
        "temperature": Annotated[float, Field(ge=0, le=1.9)],
        "top_p": Annotated[float, Field(ge=0, le=1)],
        "extra_body.top_k": Annotated[int, Field(ge=1)],
        "extra_body.chat_template_kwargs.enable_thinking": bool,
    },
    total=False,
)
setattr(Qwen3_235b_A22b_Thinking_2507Params, "__pydantic_config__", _PARAMS_CONFIG)

Qwen3_30b_A3bParams = TypedDict(
    "Qwen3_30b_A3bParams",
    {
        "max_tokens": Annotated[int, Field(ge=1)],
        "temperature": Annotated[float, Field(ge=0, le=1.9)],
        "top_p": Annotated[float, Field(ge=0, le=1)],
        "extra_body.top_k": Annotated[int, Field(ge=1)],
        "extra_body.chat_template_kwargs.enable_thinking": bool,
    },
    total=False,
)
setattr(Qwen3_30b_A3bParams, "__pydantic_config__", _PARAMS_CONFIG)

Qwen3_30b_A3b_Instruct_2507Params = TypedDict(
    "Qwen3_30b_A3b_Instruct_2507Params",
    {
        "max_tokens": Annotated[int, Field(ge=1)],
        "temperature": Annotated[float, Field(ge=0, le=1.9)],
        "top_p": Annotated[float, Field(ge=0, le=1)],
        "extra_body.top_k": Annotated[int, Field(ge=1)],
        "extra_body.chat_template_kwargs.enable_thinking": bool,
    },
    total=False,
)
setattr(Qwen3_30b_A3b_Instruct_2507Params, "__pydantic_config__", _PARAMS_CONFIG)

Qwen3_30b_A3b_Thinking_2507Params = TypedDict(
    "Qwen3_30b_A3b_Thinking_2507Params",
    {
        "max_tokens": Annotated[int, Field(ge=1)],
        "temperature": Annotated[float, Field(ge=0, le=1.9)],
        "top_p": Annotated[float, Field(ge=0, le=1)],
        "extra_body.top_k": Annotated[int, Field(ge=1)],
        "extra_body.chat_template_kwargs.enable_thinking": bool,
    },
    total=False,
)
setattr(Qwen3_30b_A3b_Thinking_2507Params, "__pydantic_config__", _PARAMS_CONFIG)

Qwen3_8bParams = TypedDict(
    "Qwen3_8bParams",
    {
        "max_tokens": Annotated[int, Field(ge=1)],
        "temperature": Annotated[float, Field(ge=0, le=1.9)],
        "top_p": Annotated[float, Field(ge=0, le=1)],
        "extra_body.top_k": Annotated[int, Field(ge=1)],
        "extra_body.chat_template_kwargs.enable_thinking": bool,
    },
    total=False,
)
setattr(Qwen3_8bParams, "__pydantic_config__", _PARAMS_CONFIG)

Qwen3_Coder_480b_A35b_InstructParams = TypedDict(
    "Qwen3_Coder_480b_A35b_InstructParams",
    {
        "max_tokens": Annotated[int, Field(ge=1)],
        "temperature": Annotated[float, Field(ge=0, le=1.9)],
        "top_p": Annotated[float, Field(ge=0, le=1)],
        "extra_body.top_k": Annotated[int, Field(ge=1)],
    },
    total=False,
)
setattr(Qwen3_Coder_480b_A35b_InstructParams, "__pydantic_config__", _PARAMS_CONFIG)

Qwen3_Coder_FlashParams = TypedDict(
    "Qwen3_Coder_FlashParams",
    {
        "max_tokens": Annotated[int, Field(ge=1)],
        "temperature": Annotated[float, Field(ge=0, le=1.9)],
        "top_p": Annotated[float, Field(ge=0, le=1)],
        "extra_body.top_k": Annotated[int, Field(ge=1)],
    },
    total=False,
)
setattr(Qwen3_Coder_FlashParams, "__pydantic_config__", _PARAMS_CONFIG)

Qwen3_Coder_NextParams = TypedDict(
    "Qwen3_Coder_NextParams",
    {
        "max_tokens": Annotated[int, Field(ge=1)],
        "temperature": Annotated[float, Field(ge=0, le=1.9)],
        "top_p": Annotated[float, Field(ge=0, le=1)],
        "extra_body.top_k": Annotated[int, Field(ge=1)],
    },
    total=False,
)
setattr(Qwen3_Coder_NextParams, "__pydantic_config__", _PARAMS_CONFIG)

Qwen3_Coder_PlusParams = TypedDict(
    "Qwen3_Coder_PlusParams",
    {
        "max_tokens": Annotated[int, Field(ge=1)],
        "temperature": Annotated[float, Field(ge=0, le=1.9)],
        "top_p": Annotated[float, Field(ge=0, le=1)],
        "extra_body.top_k": Annotated[int, Field(ge=1)],
    },
    total=False,
)
setattr(Qwen3_Coder_PlusParams, "__pydantic_config__", _PARAMS_CONFIG)

Qwen3_MaxParams = TypedDict(
    "Qwen3_MaxParams",
    {
        "max_tokens": Annotated[int, Field(ge=1)],
        "temperature": Annotated[float, Field(ge=0, le=1.9)],
        "top_p": Annotated[float, Field(ge=0, le=1)],
        "extra_body.top_k": Annotated[int, Field(ge=1)],
        "extra_body.chat_template_kwargs.enable_thinking": bool,
    },
    total=False,
)
setattr(Qwen3_MaxParams, "__pydantic_config__", _PARAMS_CONFIG)

Qwen3_Max_PreviewParams = TypedDict(
    "Qwen3_Max_PreviewParams",
    {
        "max_tokens": Annotated[int, Field(ge=1)],
        "temperature": Annotated[float, Field(ge=0, le=1.9)],
        "top_p": Annotated[float, Field(ge=0, le=1)],
        "extra_body.top_k": Annotated[int, Field(ge=1)],
        "extra_body.chat_template_kwargs.enable_thinking": bool,
    },
    total=False,
)
setattr(Qwen3_Max_PreviewParams, "__pydantic_config__", _PARAMS_CONFIG)

Qwen3_Next_80b_A3b_InstructParams = TypedDict(
    "Qwen3_Next_80b_A3b_InstructParams",
    {
        "max_tokens": Annotated[int, Field(ge=1)],
        "temperature": Annotated[float, Field(ge=0, le=1.9)],
        "top_p": Annotated[float, Field(ge=0, le=1)],
        "extra_body.top_k": Annotated[int, Field(ge=1)],
        "extra_body.chat_template_kwargs.enable_thinking": bool,
    },
    total=False,
)
setattr(Qwen3_Next_80b_A3b_InstructParams, "__pydantic_config__", _PARAMS_CONFIG)

Qwen3_Next_80b_A3b_ThinkingParams = TypedDict(
    "Qwen3_Next_80b_A3b_ThinkingParams",
    {
        "max_tokens": Annotated[int, Field(ge=1)],
        "temperature": Annotated[float, Field(ge=0, le=1.9)],
        "top_p": Annotated[float, Field(ge=0, le=1)],
        "extra_body.top_k": Annotated[int, Field(ge=1)],
        "extra_body.chat_template_kwargs.enable_thinking": bool,
    },
    total=False,
)
setattr(Qwen3_Next_80b_A3b_ThinkingParams, "__pydantic_config__", _PARAMS_CONFIG)

Qwen3_Omni_FlashParams = TypedDict(
    "Qwen3_Omni_FlashParams",
    {
        "max_tokens": Annotated[int, Field(ge=1)],
        "temperature": Annotated[float, Field(ge=0, le=1.9)],
        "top_p": Annotated[float, Field(ge=0, le=1)],
        "extra_body.top_k": Annotated[int, Field(ge=1)],
        "extra_body.chat_template_kwargs.enable_thinking": bool,
    },
    total=False,
)
setattr(Qwen3_Omni_FlashParams, "__pydantic_config__", _PARAMS_CONFIG)

Qwen3_Omni_Flash_2025_09_15Params = TypedDict(
    "Qwen3_Omni_Flash_2025_09_15Params",
    {
        "max_tokens": Annotated[int, Field(ge=1)],
        "temperature": Annotated[float, Field(ge=0, le=1.9)],
        "top_p": Annotated[float, Field(ge=0, le=1)],
        "extra_body.top_k": Annotated[int, Field(ge=1)],
        "extra_body.chat_template_kwargs.enable_thinking": bool,
    },
    total=False,
)
setattr(Qwen3_Omni_Flash_2025_09_15Params, "__pydantic_config__", _PARAMS_CONFIG)

Qwen3_Omni_Flash_2025_12_01Params = TypedDict(
    "Qwen3_Omni_Flash_2025_12_01Params",
    {
        "max_tokens": Annotated[int, Field(ge=1)],
        "temperature": Annotated[float, Field(ge=0, le=1.9)],
        "top_p": Annotated[float, Field(ge=0, le=1)],
        "extra_body.top_k": Annotated[int, Field(ge=1)],
        "extra_body.chat_template_kwargs.enable_thinking": bool,
    },
    total=False,
)
setattr(Qwen3_Omni_Flash_2025_12_01Params, "__pydantic_config__", _PARAMS_CONFIG)

Qwen3_Vl_235b_A22b_InstructParams = TypedDict(
    "Qwen3_Vl_235b_A22b_InstructParams",
    {
        "max_tokens": Annotated[int, Field(ge=1)],
        "temperature": Annotated[float, Field(ge=0, le=1.9)],
        "top_p": Annotated[float, Field(ge=0, le=1)],
        "extra_body.top_k": Annotated[int, Field(ge=1)],
        "extra_body.chat_template_kwargs.enable_thinking": bool,
    },
    total=False,
)
setattr(Qwen3_Vl_235b_A22b_InstructParams, "__pydantic_config__", _PARAMS_CONFIG)

Qwen3_Vl_235b_A22b_ThinkingParams = TypedDict(
    "Qwen3_Vl_235b_A22b_ThinkingParams",
    {
        "max_tokens": Annotated[int, Field(ge=1)],
        "temperature": Annotated[float, Field(ge=0, le=1.9)],
        "top_p": Annotated[float, Field(ge=0, le=1)],
        "extra_body.top_k": Annotated[int, Field(ge=1)],
        "extra_body.chat_template_kwargs.enable_thinking": bool,
    },
    total=False,
)
setattr(Qwen3_Vl_235b_A22b_ThinkingParams, "__pydantic_config__", _PARAMS_CONFIG)

Qwen3_Vl_FlashParams = TypedDict(
    "Qwen3_Vl_FlashParams",
    {
        "max_tokens": Annotated[int, Field(ge=1)],
        "temperature": Annotated[float, Field(ge=0, le=1.9)],
        "top_p": Annotated[float, Field(ge=0, le=1)],
        "extra_body.top_k": Annotated[int, Field(ge=1)],
        "extra_body.chat_template_kwargs.enable_thinking": bool,
    },
    total=False,
)
setattr(Qwen3_Vl_FlashParams, "__pydantic_config__", _PARAMS_CONFIG)

Qwen3_Vl_Flash_2026_01_22Params = TypedDict(
    "Qwen3_Vl_Flash_2026_01_22Params",
    {
        "max_tokens": Annotated[int, Field(ge=1)],
        "temperature": Annotated[float, Field(ge=0, le=1.9)],
        "top_p": Annotated[float, Field(ge=0, le=1)],
        "extra_body.top_k": Annotated[int, Field(ge=1)],
        "extra_body.chat_template_kwargs.enable_thinking": bool,
    },
    total=False,
)
setattr(Qwen3_Vl_Flash_2026_01_22Params, "__pydantic_config__", _PARAMS_CONFIG)

Qwen3_Vl_PlusParams = TypedDict(
    "Qwen3_Vl_PlusParams",
    {
        "max_tokens": Annotated[int, Field(ge=1)],
        "temperature": Annotated[float, Field(ge=0, le=1.9)],
        "top_p": Annotated[float, Field(ge=0, le=1)],
        "extra_body.top_k": Annotated[int, Field(ge=1)],
        "extra_body.chat_template_kwargs.enable_thinking": bool,
    },
    total=False,
)
setattr(Qwen3_Vl_PlusParams, "__pydantic_config__", _PARAMS_CONFIG)

Qwen3_Vl_Plus_2025_09_23Params = TypedDict(
    "Qwen3_Vl_Plus_2025_09_23Params",
    {
        "max_tokens": Annotated[int, Field(ge=1)],
        "temperature": Annotated[float, Field(ge=0, le=1.9)],
        "top_p": Annotated[float, Field(ge=0, le=1)],
        "extra_body.top_k": Annotated[int, Field(ge=1)],
        "extra_body.chat_template_kwargs.enable_thinking": bool,
    },
    total=False,
)
setattr(Qwen3_Vl_Plus_2025_09_23Params, "__pydantic_config__", _PARAMS_CONFIG)

Qwen3_Vl_Plus_2025_12_19Params = TypedDict(
    "Qwen3_Vl_Plus_2025_12_19Params",
    {
        "max_tokens": Annotated[int, Field(ge=1)],
        "temperature": Annotated[float, Field(ge=0, le=1.9)],
        "top_p": Annotated[float, Field(ge=0, le=1)],
        "extra_body.top_k": Annotated[int, Field(ge=1)],
        "extra_body.chat_template_kwargs.enable_thinking": bool,
    },
    total=False,
)
setattr(Qwen3_Vl_Plus_2025_12_19Params, "__pydantic_config__", _PARAMS_CONFIG)

Qwen3_5Params = TypedDict(
    "Qwen3_5Params",
    {
        "max_tokens": Annotated[int, Field(ge=1)],
        "temperature": Annotated[float, Field(ge=0, le=1.9)],
        "top_p": Annotated[float, Field(ge=0, le=1)],
        "extra_body.top_k": Annotated[int, Field(ge=1)],
        "extra_body.chat_template_kwargs.enable_thinking": bool,
    },
    total=False,
)
setattr(Qwen3_5Params, "__pydantic_config__", _PARAMS_CONFIG)

Qwen3_5_122b_A10bParams = TypedDict(
    "Qwen3_5_122b_A10bParams",
    {
        "max_tokens": Annotated[int, Field(ge=1)],
        "temperature": Annotated[float, Field(ge=0, le=1.9)],
        "top_p": Annotated[float, Field(ge=0, le=1)],
        "extra_body.top_k": Annotated[int, Field(ge=1)],
        "extra_body.chat_template_kwargs.enable_thinking": bool,
    },
    total=False,
)
setattr(Qwen3_5_122b_A10bParams, "__pydantic_config__", _PARAMS_CONFIG)

Qwen3_5_27bParams = TypedDict(
    "Qwen3_5_27bParams",
    {
        "max_tokens": Annotated[int, Field(ge=1)],
        "temperature": Annotated[float, Field(ge=0, le=1.9)],
        "top_p": Annotated[float, Field(ge=0, le=1)],
        "extra_body.top_k": Annotated[int, Field(ge=1)],
        "extra_body.chat_template_kwargs.enable_thinking": bool,
    },
    total=False,
)
setattr(Qwen3_5_27bParams, "__pydantic_config__", _PARAMS_CONFIG)

Qwen3_5_35b_A3bParams = TypedDict(
    "Qwen3_5_35b_A3bParams",
    {
        "max_tokens": Annotated[int, Field(ge=1)],
        "temperature": Annotated[float, Field(ge=0, le=1.9)],
        "top_p": Annotated[float, Field(ge=0, le=1)],
        "extra_body.top_k": Annotated[int, Field(ge=1)],
        "extra_body.chat_template_kwargs.enable_thinking": bool,
    },
    total=False,
)
setattr(Qwen3_5_35b_A3bParams, "__pydantic_config__", _PARAMS_CONFIG)

Qwen3_5_397b_A17bParams = TypedDict(
    "Qwen3_5_397b_A17bParams",
    {
        "max_tokens": Annotated[int, Field(ge=1)],
        "temperature": Annotated[float, Field(ge=0, le=1.9)],
        "top_p": Annotated[float, Field(ge=0, le=1)],
        "extra_body.top_k": Annotated[int, Field(ge=1)],
        "extra_body.chat_template_kwargs.enable_thinking": bool,
    },
    total=False,
)
setattr(Qwen3_5_397b_A17bParams, "__pydantic_config__", _PARAMS_CONFIG)

Qwen3_5_FlashParams = TypedDict(
    "Qwen3_5_FlashParams",
    {
        "max_tokens": Annotated[int, Field(ge=1)],
        "temperature": Annotated[float, Field(ge=0, le=1.9)],
        "top_p": Annotated[float, Field(ge=0, le=1)],
        "extra_body.top_k": Annotated[int, Field(ge=1)],
        "extra_body.chat_template_kwargs.enable_thinking": bool,
    },
    total=False,
)
setattr(Qwen3_5_FlashParams, "__pydantic_config__", _PARAMS_CONFIG)

Qwen3_5_Omni_FlashParams = TypedDict(
    "Qwen3_5_Omni_FlashParams",
    {
        "max_tokens": Annotated[int, Field(ge=1)],
        "temperature": Annotated[float, Field(ge=0, le=1.9)],
        "top_p": Annotated[float, Field(ge=0, le=1)],
        "extra_body.top_k": Annotated[int, Field(ge=1)],
        "extra_body.chat_template_kwargs.enable_thinking": bool,
    },
    total=False,
)
setattr(Qwen3_5_Omni_FlashParams, "__pydantic_config__", _PARAMS_CONFIG)

Qwen3_5_Omni_Flash_2026_03_15Params = TypedDict(
    "Qwen3_5_Omni_Flash_2026_03_15Params",
    {
        "max_tokens": Annotated[int, Field(ge=1)],
        "temperature": Annotated[float, Field(ge=0, le=1.9)],
        "top_p": Annotated[float, Field(ge=0, le=1)],
        "extra_body.top_k": Annotated[int, Field(ge=1)],
        "extra_body.chat_template_kwargs.enable_thinking": bool,
    },
    total=False,
)
setattr(Qwen3_5_Omni_Flash_2026_03_15Params, "__pydantic_config__", _PARAMS_CONFIG)

Qwen3_5_Omni_PlusParams = TypedDict(
    "Qwen3_5_Omni_PlusParams",
    {
        "max_tokens": Annotated[int, Field(ge=1)],
        "temperature": Annotated[float, Field(ge=0, le=1.9)],
        "top_p": Annotated[float, Field(ge=0, le=1)],
        "extra_body.top_k": Annotated[int, Field(ge=1)],
        "extra_body.chat_template_kwargs.enable_thinking": bool,
    },
    total=False,
)
setattr(Qwen3_5_Omni_PlusParams, "__pydantic_config__", _PARAMS_CONFIG)

Qwen3_5_Omni_Plus_2026_03_15Params = TypedDict(
    "Qwen3_5_Omni_Plus_2026_03_15Params",
    {
        "max_tokens": Annotated[int, Field(ge=1)],
        "temperature": Annotated[float, Field(ge=0, le=1.9)],
        "top_p": Annotated[float, Field(ge=0, le=1)],
        "extra_body.top_k": Annotated[int, Field(ge=1)],
        "extra_body.chat_template_kwargs.enable_thinking": bool,
    },
    total=False,
)
setattr(Qwen3_5_Omni_Plus_2026_03_15Params, "__pydantic_config__", _PARAMS_CONFIG)

Qwen3_5_PlusParams = TypedDict(
    "Qwen3_5_PlusParams",
    {
        "max_tokens": Annotated[int, Field(ge=1)],
        "temperature": Annotated[float, Field(ge=0, le=1.9)],
        "top_p": Annotated[float, Field(ge=0, le=1)],
        "extra_body.top_k": Annotated[int, Field(ge=1)],
        "extra_body.chat_template_kwargs.enable_thinking": bool,
    },
    total=False,
)
setattr(Qwen3_5_PlusParams, "__pydantic_config__", _PARAMS_CONFIG)

Qwen3_5_Plus_2026_02_15Params = TypedDict(
    "Qwen3_5_Plus_2026_02_15Params",
    {
        "max_tokens": Annotated[int, Field(ge=1)],
        "temperature": Annotated[float, Field(ge=0, le=1.9)],
        "top_p": Annotated[float, Field(ge=0, le=1)],
        "extra_body.top_k": Annotated[int, Field(ge=1)],
        "extra_body.chat_template_kwargs.enable_thinking": bool,
    },
    total=False,
)
setattr(Qwen3_5_Plus_2026_02_15Params, "__pydantic_config__", _PARAMS_CONFIG)

Qwen3_5_Plus_2026_04_20Params = TypedDict(
    "Qwen3_5_Plus_2026_04_20Params",
    {
        "max_tokens": Annotated[int, Field(ge=1)],
        "temperature": Annotated[float, Field(ge=0, le=1.9)],
        "top_p": Annotated[float, Field(ge=0, le=1)],
        "extra_body.top_k": Annotated[int, Field(ge=1)],
        "extra_body.chat_template_kwargs.enable_thinking": bool,
    },
    total=False,
)
setattr(Qwen3_5_Plus_2026_04_20Params, "__pydantic_config__", _PARAMS_CONFIG)

Qwen3_6_27bParams = TypedDict(
    "Qwen3_6_27bParams",
    {
        "max_completion_tokens": Annotated[int, Field(ge=1)],
        "temperature": Annotated[float, Field(ge=0, le=1.9)],
        "top_p": Annotated[float, Field(ge=0, le=1)],
        "extra_body.top_k": Annotated[int, Field(ge=0)],
        "extra_body.enable_thinking": bool,
        "extra_body.thinking_budget": Annotated[int, Field(ge=1)],
    },
    total=False,
)
setattr(Qwen3_6_27bParams, "__pydantic_config__", _PARAMS_CONFIG)

Qwen3_6_35b_A3bParams = TypedDict(
    "Qwen3_6_35b_A3bParams",
    {
        "max_completion_tokens": Annotated[int, Field(ge=1)],
        "temperature": Annotated[float, Field(ge=0, le=1.9)],
        "top_p": Annotated[float, Field(ge=0, le=1)],
        "extra_body.top_k": Annotated[int, Field(ge=0)],
        "extra_body.enable_thinking": bool,
        "extra_body.thinking_budget": Annotated[int, Field(ge=1)],
    },
    total=False,
)
setattr(Qwen3_6_35b_A3bParams, "__pydantic_config__", _PARAMS_CONFIG)

Qwen3_6_FlashParams = TypedDict(
    "Qwen3_6_FlashParams",
    {
        "max_completion_tokens": Annotated[int, Field(ge=1)],
        "temperature": Annotated[float, Field(ge=0, le=1.9)],
        "top_p": Annotated[float, Field(ge=0, le=1)],
        "extra_body.top_k": Annotated[int, Field(ge=0)],
        "extra_body.enable_thinking": bool,
        "extra_body.thinking_budget": Annotated[int, Field(ge=1)],
    },
    total=False,
)
setattr(Qwen3_6_FlashParams, "__pydantic_config__", _PARAMS_CONFIG)

Qwen3_6_Max_PreviewParams = TypedDict(
    "Qwen3_6_Max_PreviewParams",
    {
        "max_completion_tokens": Annotated[int, Field(ge=1)],
        "temperature": Annotated[float, Field(ge=0, le=1.9)],
        "top_p": Annotated[float, Field(ge=0, le=1)],
        "extra_body.top_k": Annotated[int, Field(ge=0)],
        "extra_body.enable_thinking": bool,
        "extra_body.thinking_budget": Annotated[int, Field(ge=1)],
    },
    total=False,
)
setattr(Qwen3_6_Max_PreviewParams, "__pydantic_config__", _PARAMS_CONFIG)

Qwen3_6_PlusParams = TypedDict(
    "Qwen3_6_PlusParams",
    {
        "max_completion_tokens": Annotated[int, Field(ge=1)],
        "temperature": Annotated[float, Field(ge=0, le=1.9)],
        "top_p": Annotated[float, Field(ge=0, le=1)],
        "extra_body.top_k": Annotated[int, Field(ge=0)],
        "extra_body.enable_thinking": bool,
        "extra_body.thinking_budget": Annotated[int, Field(ge=1)],
    },
    total=False,
)
setattr(Qwen3_6_PlusParams, "__pydantic_config__", _PARAMS_CONFIG)

Qwen3_7_FlashParams = TypedDict(
    "Qwen3_7_FlashParams",
    {
        "max_completion_tokens": Annotated[int, Field(ge=1)],
        "temperature": Annotated[float, Field(ge=0, le=1.9)],
        "top_p": Annotated[float, Field(ge=0, le=1)],
        "extra_body.top_k": Annotated[int, Field(ge=0)],
        "extra_body.enable_thinking": bool,
        "extra_body.thinking_budget": Annotated[int, Field(ge=1)],
    },
    total=False,
)
setattr(Qwen3_7_FlashParams, "__pydantic_config__", _PARAMS_CONFIG)

Qwen3_7_MaxParams = TypedDict(
    "Qwen3_7_MaxParams",
    {
        "max_completion_tokens": Annotated[int, Field(ge=1)],
        "temperature": Annotated[float, Field(ge=0, le=1.9)],
        "top_p": Annotated[float, Field(ge=0, le=1)],
        "extra_body.top_k": Annotated[int, Field(ge=0)],
        "extra_body.enable_thinking": bool,
        "extra_body.thinking_budget": Annotated[int, Field(ge=1)],
    },
    total=False,
)
setattr(Qwen3_7_MaxParams, "__pydantic_config__", _PARAMS_CONFIG)

Qwen3_7_Max_PreviewParams = TypedDict(
    "Qwen3_7_Max_PreviewParams",
    {
        "max_completion_tokens": Annotated[int, Field(ge=1)],
        "temperature": Annotated[float, Field(ge=0, le=1.9)],
        "top_p": Annotated[float, Field(ge=0, le=1)],
        "extra_body.top_k": Annotated[int, Field(ge=0)],
        "extra_body.enable_thinking": bool,
        "extra_body.thinking_budget": Annotated[int, Field(ge=1)],
    },
    total=False,
)
setattr(Qwen3_7_Max_PreviewParams, "__pydantic_config__", _PARAMS_CONFIG)

Qwen3_7_PlusParams = TypedDict(
    "Qwen3_7_PlusParams",
    {
        "max_completion_tokens": Annotated[int, Field(ge=1)],
        "temperature": Annotated[float, Field(ge=0, le=1.9)],
        "top_p": Annotated[float, Field(ge=0, le=1)],
        "extra_body.top_k": Annotated[int, Field(ge=0)],
        "extra_body.enable_thinking": bool,
        "extra_body.thinking_budget": Annotated[int, Field(ge=1)],
    },
    total=False,
)
setattr(Qwen3_7_PlusParams, "__pydantic_config__", _PARAMS_CONFIG)

Qwen3_8_2_4t_A95bParams = TypedDict(
    "Qwen3_8_2_4t_A95bParams",
    {
        "max_completion_tokens": Annotated[int, Field(ge=1)],
        "temperature": Annotated[float, Field(ge=0, le=1.9)],
        "top_p": Annotated[float, Field(ge=0, le=1)],
        "extra_body.top_k": Annotated[int, Field(ge=0)],
        "extra_body.enable_thinking": bool,
        "extra_body.thinking_budget": Annotated[int, Field(ge=1)],
    },
    total=False,
)
setattr(Qwen3_8_2_4t_A95bParams, "__pydantic_config__", _PARAMS_CONFIG)

Qwen3_8_27bParams = TypedDict(
    "Qwen3_8_27bParams",
    {
        "max_completion_tokens": Annotated[int, Field(ge=1)],
        "temperature": Annotated[float, Field(ge=0, le=1.9)],
        "top_p": Annotated[float, Field(ge=0, le=1)],
        "extra_body.top_k": Annotated[int, Field(ge=0)],
        "extra_body.enable_thinking": bool,
        "extra_body.thinking_budget": Annotated[int, Field(ge=1)],
    },
    total=False,
)
setattr(Qwen3_8_27bParams, "__pydantic_config__", _PARAMS_CONFIG)

Qwen3_8_FlashParams = TypedDict(
    "Qwen3_8_FlashParams",
    {
        "max_completion_tokens": Annotated[int, Field(ge=1)],
        "temperature": Annotated[float, Field(ge=0, le=1.9)],
        "top_p": Annotated[float, Field(ge=0, le=1)],
        "extra_body.top_k": Annotated[int, Field(ge=0)],
        "extra_body.enable_thinking": bool,
        "extra_body.thinking_budget": Annotated[int, Field(ge=1)],
    },
    total=False,
)
setattr(Qwen3_8_FlashParams, "__pydantic_config__", _PARAMS_CONFIG)

Qwen3_8_MaxParams = TypedDict(
    "Qwen3_8_MaxParams",
    {
        "max_completion_tokens": Annotated[int, Field(ge=1)],
        "temperature": Annotated[float, Field(ge=0, le=1.9)],
        "top_p": Annotated[float, Field(ge=0, le=1)],
        "extra_body.top_k": Annotated[int, Field(ge=0)],
        "extra_body.enable_thinking": bool,
        "extra_body.thinking_budget": Annotated[int, Field(ge=1)],
    },
    total=False,
)
setattr(Qwen3_8_MaxParams, "__pydantic_config__", _PARAMS_CONFIG)

Qwen3_8_Max_0902Params = TypedDict(
    "Qwen3_8_Max_0902Params",
    {
        "max_completion_tokens": Annotated[int, Field(ge=1)],
        "temperature": Annotated[float, Field(ge=0, le=1.9)],
        "top_p": Annotated[float, Field(ge=0, le=1)],
        "extra_body.top_k": Annotated[int, Field(ge=0)],
        "extra_body.enable_thinking": bool,
        "extra_body.thinking_budget": Annotated[int, Field(ge=1)],
    },
    total=False,
)
setattr(Qwen3_8_Max_0902Params, "__pydantic_config__", _PARAMS_CONFIG)

Qwen3_8_Omni_FlashParams = TypedDict(
    "Qwen3_8_Omni_FlashParams",
    {
        "max_completion_tokens": Annotated[int, Field(ge=1)],
        "temperature": Annotated[float, Field(ge=0, le=1.9)],
        "top_p": Annotated[float, Field(ge=0, le=1)],
        "extra_body.top_k": Annotated[int, Field(ge=0)],
        "extra_body.enable_thinking": bool,
        "extra_body.thinking_budget": Annotated[int, Field(ge=1)],
    },
    total=False,
)
setattr(Qwen3_8_Omni_FlashParams, "__pydantic_config__", _PARAMS_CONFIG)

Qwq_PlusParams = TypedDict(
    "Qwq_PlusParams",
    {
        "max_tokens": Annotated[int, Field(ge=1)],
        "temperature": Annotated[float, Field(ge=0, le=1.9)],
        "top_p": Annotated[float, Field(ge=0, le=1)],
        "extra_body.top_k": Annotated[int, Field(ge=1)],
    },
    total=False,
)
setattr(Qwq_PlusParams, "__pydantic_config__", _PARAMS_CONFIG)

__all__ = [
    "Deepseek_V3_2Params",
    "Deepseek_V4_FlashParams",
    "Deepseek_V4_Flash_0731Params",
    "Deepseek_V4_ProParams",
    "Deepseek_V4_Pro_0813Params",
    "Deepseek_V4_1_FlashParams",
    "Glm_5_1Params",
    "Glm_5_2Params",
    "Glm_5_2_Fast_PreviewParams",
    "Glm_5_3Params",
    "Glm_5_3_PrimeParams",
    "Kimi_K2_7_CodeParams",
    "Kimi_K3Params",
    "Qvq_MaxParams",
    "Qwen_Coder_PlusParams",
    "Qwen_FlashParams",
    "Qwen_Flash_CharacterParams",
    "Qwen_MaxParams",
    "Qwen_PlusParams",
    "Qwen_Plus_CharacterParams",
    "Qwen_Plus_LatestParams",
    "Qwen_TurboParams",
    "Qwen_Vl_MaxParams",
    "Qwen_Vl_PlusParams",
    "Qwen3_14bParams",
    "Qwen3_235b_A22bParams",
    "Qwen3_235b_A22b_Instruct_2507Params",
    "Qwen3_235b_A22b_Thinking_2507Params",
    "Qwen3_30b_A3bParams",
    "Qwen3_30b_A3b_Instruct_2507Params",
    "Qwen3_30b_A3b_Thinking_2507Params",
    "Qwen3_8bParams",
    "Qwen3_Coder_480b_A35b_InstructParams",
    "Qwen3_Coder_FlashParams",
    "Qwen3_Coder_NextParams",
    "Qwen3_Coder_PlusParams",
    "Qwen3_MaxParams",
    "Qwen3_Max_PreviewParams",
    "Qwen3_Next_80b_A3b_InstructParams",
    "Qwen3_Next_80b_A3b_ThinkingParams",
    "Qwen3_Omni_FlashParams",
    "Qwen3_Omni_Flash_2025_09_15Params",
    "Qwen3_Omni_Flash_2025_12_01Params",
    "Qwen3_Vl_235b_A22b_InstructParams",
    "Qwen3_Vl_235b_A22b_ThinkingParams",
    "Qwen3_Vl_FlashParams",
    "Qwen3_Vl_Flash_2026_01_22Params",
    "Qwen3_Vl_PlusParams",
    "Qwen3_Vl_Plus_2025_09_23Params",
    "Qwen3_Vl_Plus_2025_12_19Params",
    "Qwen3_5Params",
    "Qwen3_5_122b_A10bParams",
    "Qwen3_5_27bParams",
    "Qwen3_5_35b_A3bParams",
    "Qwen3_5_397b_A17bParams",
    "Qwen3_5_FlashParams",
    "Qwen3_5_Omni_FlashParams",
    "Qwen3_5_Omni_Flash_2026_03_15Params",
    "Qwen3_5_Omni_PlusParams",
    "Qwen3_5_Omni_Plus_2026_03_15Params",
    "Qwen3_5_PlusParams",
    "Qwen3_5_Plus_2026_02_15Params",
    "Qwen3_5_Plus_2026_04_20Params",
    "Qwen3_6_27bParams",
    "Qwen3_6_35b_A3bParams",
    "Qwen3_6_FlashParams",
    "Qwen3_6_Max_PreviewParams",
    "Qwen3_6_PlusParams",
    "Qwen3_7_FlashParams",
    "Qwen3_7_MaxParams",
    "Qwen3_7_Max_PreviewParams",
    "Qwen3_7_PlusParams",
    "Qwen3_8_2_4t_A95bParams",
    "Qwen3_8_27bParams",
    "Qwen3_8_FlashParams",
    "Qwen3_8_MaxParams",
    "Qwen3_8_Max_0902Params",
    "Qwen3_8_Omni_FlashParams",
    "Qwq_PlusParams",
]
