# AUTO-GENERATED by packages/modelparams-python/scripts/codegen.ts.
# Do not edit by hand; the YAML catalog under /models is the source of truth.

# ruff: noqa: F401

from typing import Annotated, Literal

from pydantic import ConfigDict, Field
from typing_extensions import TypedDict

_PARAMS_CONFIG = ConfigDict(strict=True, extra="forbid")

Qwen_FlashParams = TypedDict(
    "Qwen_FlashParams",
    {
        "max_tokens": Annotated[int, Field(ge=1)],
        "temperature": Annotated[float, Field(ge=0, le=2)],
        "top_p": Annotated[float, Field(ge=0, le=1)],
        "extra_body.top_k": Annotated[int, Field(ge=1)],
        "extra_body.chat_template_kwargs.enable_thinking": bool,
    },
    total=False,
)
setattr(Qwen_FlashParams, "__pydantic_config__", _PARAMS_CONFIG)

Qwen_PlusParams = TypedDict(
    "Qwen_PlusParams",
    {
        "max_tokens": Annotated[int, Field(ge=1)],
        "temperature": Annotated[float, Field(ge=0, le=2)],
        "top_p": Annotated[float, Field(ge=0, le=1)],
        "extra_body.top_k": Annotated[int, Field(ge=1)],
        "extra_body.chat_template_kwargs.enable_thinking": bool,
    },
    total=False,
)
setattr(Qwen_PlusParams, "__pydantic_config__", _PARAMS_CONFIG)

Qwen3_Coder_FlashParams = TypedDict(
    "Qwen3_Coder_FlashParams",
    {
        "max_tokens": Annotated[int, Field(ge=1)],
        "temperature": Annotated[float, Field(ge=0, le=2)],
        "top_p": Annotated[float, Field(ge=0, le=1)],
        "extra_body.top_k": Annotated[int, Field(ge=1)],
    },
    total=False,
)
setattr(Qwen3_Coder_FlashParams, "__pydantic_config__", _PARAMS_CONFIG)

Qwen3_Coder_PlusParams = TypedDict(
    "Qwen3_Coder_PlusParams",
    {
        "max_tokens": Annotated[int, Field(ge=1)],
        "temperature": Annotated[float, Field(ge=0, le=2)],
        "top_p": Annotated[float, Field(ge=0, le=1)],
        "extra_body.top_k": Annotated[int, Field(ge=1)],
    },
    total=False,
)
setattr(Qwen3_Coder_PlusParams, "__pydantic_config__", _PARAMS_CONFIG)

Qwen3_MaxParams = TypedDict(
    "Qwen3_MaxParams",
    {
        "max_tokens": Annotated[int, Field(ge=1)],
        "temperature": Annotated[float, Field(ge=0, le=2)],
        "top_p": Annotated[float, Field(ge=0, le=1)],
        "extra_body.top_k": Annotated[int, Field(ge=1)],
        "extra_body.chat_template_kwargs.enable_thinking": bool,
    },
    total=False,
)
setattr(Qwen3_MaxParams, "__pydantic_config__", _PARAMS_CONFIG)

Qwen3_5Params = TypedDict(
    "Qwen3_5Params",
    {
        "max_tokens": Annotated[int, Field(ge=1)],
        "temperature": Annotated[float, Field(ge=0, le=2)],
        "top_p": Annotated[float, Field(ge=0, le=1)],
        "extra_body.top_k": Annotated[int, Field(ge=1)],
        "extra_body.chat_template_kwargs.enable_thinking": bool,
    },
    total=False,
)
setattr(Qwen3_5Params, "__pydantic_config__", _PARAMS_CONFIG)

Qwen3_5_FlashParams = TypedDict(
    "Qwen3_5_FlashParams",
    {
        "max_tokens": Annotated[int, Field(ge=1)],
        "temperature": Annotated[float, Field(ge=0, le=2)],
        "top_p": Annotated[float, Field(ge=0, le=1)],
        "extra_body.top_k": Annotated[int, Field(ge=1)],
        "extra_body.chat_template_kwargs.enable_thinking": bool,
    },
    total=False,
)
setattr(Qwen3_5_FlashParams, "__pydantic_config__", _PARAMS_CONFIG)

Qwq_PlusParams = TypedDict(
    "Qwq_PlusParams",
    {
        "max_tokens": Annotated[int, Field(ge=1)],
        "temperature": Annotated[float, Field(ge=0, le=2)],
        "top_p": Annotated[float, Field(ge=0, le=1)],
        "extra_body.top_k": Annotated[int, Field(ge=1)],
    },
    total=False,
)
setattr(Qwq_PlusParams, "__pydantic_config__", _PARAMS_CONFIG)

__all__ = [
    "Qwen_FlashParams",
    "Qwen_PlusParams",
    "Qwen3_Coder_FlashParams",
    "Qwen3_Coder_PlusParams",
    "Qwen3_MaxParams",
    "Qwen3_5Params",
    "Qwen3_5_FlashParams",
    "Qwq_PlusParams",
]
