# AUTO-GENERATED by packages/modelparams-python/scripts/codegen.ts.
# Do not edit by hand; the YAML catalog under /models is the source of truth.

# ruff: noqa: F401

from typing import Annotated, Literal

from pydantic import ConfigDict, Field
from typing_extensions import TypedDict

_PARAMS_CONFIG = ConfigDict(strict=True, extra="forbid")

Claude_3_5_Haiku_20241022Params = TypedDict(
    "Claude_3_5_Haiku_20241022Params",
    {
        "max_tokens": Annotated[int, Field(ge=1)],
        "temperature": Annotated[float, Field(ge=0, le=1)],
        "top_p": Annotated[float, Field(ge=0, le=1)],
        "top_k": Annotated[int, Field(ge=0)],
    },
    total=False,
)
setattr(Claude_3_5_Haiku_20241022Params, "__pydantic_config__", _PARAMS_CONFIG)

Claude_3_5_Haiku_LatestParams = TypedDict(
    "Claude_3_5_Haiku_LatestParams",
    {
        "max_tokens": Annotated[int, Field(ge=1)],
        "temperature": Annotated[float, Field(ge=0, le=1)],
        "top_p": Annotated[float, Field(ge=0, le=1)],
        "top_k": Annotated[int, Field(ge=0)],
    },
    total=False,
)
setattr(Claude_3_5_Haiku_LatestParams, "__pydantic_config__", _PARAMS_CONFIG)

Claude_3_5_Sonnet_20241022Params = TypedDict(
    "Claude_3_5_Sonnet_20241022Params",
    {
        "max_tokens": Annotated[int, Field(ge=1)],
        "temperature": Annotated[float, Field(ge=0, le=1)],
        "top_p": Annotated[float, Field(ge=0, le=1)],
        "top_k": Annotated[int, Field(ge=0)],
    },
    total=False,
)
setattr(Claude_3_5_Sonnet_20241022Params, "__pydantic_config__", _PARAMS_CONFIG)

Claude_3_5_Sonnet_LatestParams = TypedDict(
    "Claude_3_5_Sonnet_LatestParams",
    {
        "max_tokens": Annotated[int, Field(ge=1)],
        "temperature": Annotated[float, Field(ge=0, le=1)],
        "top_p": Annotated[float, Field(ge=0, le=1)],
        "top_k": Annotated[int, Field(ge=0)],
    },
    total=False,
)
setattr(Claude_3_5_Sonnet_LatestParams, "__pydantic_config__", _PARAMS_CONFIG)

Claude_3_7_Sonnet_20250219Params = TypedDict(
    "Claude_3_7_Sonnet_20250219Params",
    {
        "max_tokens": Annotated[int, Field(ge=1)],
        "temperature": Annotated[float, Field(ge=0, le=1)],
        "top_p": Annotated[float, Field(ge=0, le=1)],
        "top_k": Annotated[int, Field(ge=0)],
        "thinking.type": Literal["disabled", "enabled"],
        "thinking.budget_tokens": Annotated[int, Field(ge=1024)],
    },
    total=False,
)
setattr(Claude_3_7_Sonnet_20250219Params, "__pydantic_config__", _PARAMS_CONFIG)

Claude_3_7_Sonnet_LatestParams = TypedDict(
    "Claude_3_7_Sonnet_LatestParams",
    {
        "max_tokens": Annotated[int, Field(ge=1)],
        "temperature": Annotated[float, Field(ge=0, le=1)],
        "top_p": Annotated[float, Field(ge=0, le=1)],
        "top_k": Annotated[int, Field(ge=0)],
        "thinking.type": Literal["disabled", "enabled"],
        "thinking.budget_tokens": Annotated[int, Field(ge=1024)],
    },
    total=False,
)
setattr(Claude_3_7_Sonnet_LatestParams, "__pydantic_config__", _PARAMS_CONFIG)

Claude_3_Opus_20240229Params = TypedDict(
    "Claude_3_Opus_20240229Params",
    {
        "max_tokens": Annotated[int, Field(ge=1)],
        "temperature": Annotated[float, Field(ge=0, le=1)],
        "top_p": Annotated[float, Field(ge=0, le=1)],
        "top_k": Annotated[int, Field(ge=0)],
    },
    total=False,
)
setattr(Claude_3_Opus_20240229Params, "__pydantic_config__", _PARAMS_CONFIG)

Claude_3_Opus_LatestParams = TypedDict(
    "Claude_3_Opus_LatestParams",
    {
        "max_tokens": Annotated[int, Field(ge=1)],
        "temperature": Annotated[float, Field(ge=0, le=1)],
        "top_p": Annotated[float, Field(ge=0, le=1)],
        "top_k": Annotated[int, Field(ge=0)],
    },
    total=False,
)
setattr(Claude_3_Opus_LatestParams, "__pydantic_config__", _PARAMS_CONFIG)

Claude_Fable_5Params = TypedDict(
    "Claude_Fable_5Params",
    {
        "max_tokens": Annotated[int, Field(ge=1)],
        "thinking.type": Literal["adaptive"],
        "thinking.display": Literal["summarized", "omitted"],
        "output_config.effort": Literal["low", "medium", "high", "xhigh", "max"],
    },
    total=False,
)
setattr(Claude_Fable_5Params, "__pydantic_config__", _PARAMS_CONFIG)

Claude_Fable_5_SubscriptionParams = TypedDict(
    "Claude_Fable_5_SubscriptionParams",
    {
        "max_tokens": Annotated[int, Field(ge=1)],
        "thinking.type": Literal["adaptive"],
        "thinking.display": Literal["summarized", "omitted"],
        "output_config.effort": Literal["low", "medium", "high", "xhigh", "max"],
    },
    total=False,
)
setattr(Claude_Fable_5_SubscriptionParams, "__pydantic_config__", _PARAMS_CONFIG)

Claude_Haiku_4Params = TypedDict(
    "Claude_Haiku_4Params",
    {
        "max_tokens": Annotated[int, Field(ge=1)],
        "temperature": Annotated[float, Field(ge=0, le=1)],
        "top_p": Annotated[float, Field(ge=0, le=1)],
        "top_k": Annotated[int, Field(ge=0)],
        "thinking.type": Literal["disabled", "enabled"],
        "thinking.budget_tokens": Annotated[int, Field(ge=1024)],
    },
    total=False,
)
setattr(Claude_Haiku_4Params, "__pydantic_config__", _PARAMS_CONFIG)

Claude_Haiku_4_5Params = TypedDict(
    "Claude_Haiku_4_5Params",
    {
        "max_tokens": Annotated[int, Field(ge=1)],
        "temperature": Annotated[float, Field(ge=0, le=1)],
        "top_p": Annotated[float, Field(ge=0, le=1)],
        "top_k": Annotated[int, Field(ge=0)],
        "thinking.type": Literal["disabled", "enabled"],
        "thinking.budget_tokens": Annotated[int, Field(ge=1024)],
    },
    total=False,
)
setattr(Claude_Haiku_4_5Params, "__pydantic_config__", _PARAMS_CONFIG)

Claude_Haiku_4_5_20251001Params = TypedDict(
    "Claude_Haiku_4_5_20251001Params",
    {
        "max_tokens": Annotated[int, Field(ge=1)],
        "temperature": Annotated[float, Field(ge=0, le=1)],
        "top_p": Annotated[float, Field(ge=0, le=1)],
        "top_k": Annotated[int, Field(ge=0)],
        "thinking.type": Literal["disabled", "enabled"],
        "thinking.budget_tokens": Annotated[int, Field(ge=1024)],
    },
    total=False,
)
setattr(Claude_Haiku_4_5_20251001Params, "__pydantic_config__", _PARAMS_CONFIG)

Claude_Haiku_4_5_20251001_SubscriptionParams = TypedDict(
    "Claude_Haiku_4_5_20251001_SubscriptionParams",
    {
        "max_tokens": Annotated[int, Field(ge=1)],
        "temperature": Annotated[float, Field(ge=0, le=1)],
        "top_p": Annotated[float, Field(ge=0, le=1)],
        "top_k": Annotated[int, Field(ge=0)],
        "thinking.type": Literal["disabled", "enabled"],
        "thinking.budget_tokens": Annotated[int, Field(ge=1024)],
    },
    total=False,
)
setattr(Claude_Haiku_4_5_20251001_SubscriptionParams, "__pydantic_config__", _PARAMS_CONFIG)

Claude_Haiku_4_5_SubscriptionParams = TypedDict(
    "Claude_Haiku_4_5_SubscriptionParams",
    {
        "max_tokens": Annotated[int, Field(ge=1)],
        "temperature": Annotated[float, Field(ge=0, le=1)],
        "top_p": Annotated[float, Field(ge=0, le=1)],
        "top_k": Annotated[int, Field(ge=0)],
        "thinking.type": Literal["disabled", "enabled"],
        "thinking.budget_tokens": Annotated[int, Field(ge=1024)],
    },
    total=False,
)
setattr(Claude_Haiku_4_5_SubscriptionParams, "__pydantic_config__", _PARAMS_CONFIG)

Claude_Haiku_4_SubscriptionParams = TypedDict(
    "Claude_Haiku_4_SubscriptionParams",
    {
        "max_tokens": Annotated[int, Field(ge=1)],
        "temperature": Annotated[float, Field(ge=0, le=1)],
        "top_p": Annotated[float, Field(ge=0, le=1)],
        "top_k": Annotated[int, Field(ge=0)],
        "thinking.type": Literal["disabled", "enabled"],
        "thinking.budget_tokens": Annotated[int, Field(ge=1024)],
    },
    total=False,
)
setattr(Claude_Haiku_4_SubscriptionParams, "__pydantic_config__", _PARAMS_CONFIG)

Claude_Opus_4_1_20250805Params = TypedDict(
    "Claude_Opus_4_1_20250805Params",
    {
        "max_tokens": Annotated[int, Field(ge=1)],
        "temperature": Annotated[float, Field(ge=0, le=1)],
        "top_p": Annotated[float, Field(ge=0, le=1)],
        "top_k": Annotated[int, Field(ge=0)],
        "thinking.type": Literal["disabled", "enabled"],
        "thinking.budget_tokens": Annotated[int, Field(ge=1024)],
        "thinking.display": Literal["summarized", "omitted"],
    },
    total=False,
)
setattr(Claude_Opus_4_1_20250805Params, "__pydantic_config__", _PARAMS_CONFIG)

Claude_Opus_4_1_20250805_SubscriptionParams = TypedDict(
    "Claude_Opus_4_1_20250805_SubscriptionParams",
    {
        "max_tokens": Annotated[int, Field(ge=1)],
        "temperature": Annotated[float, Field(ge=0, le=1)],
        "top_p": Annotated[float, Field(ge=0, le=1)],
        "top_k": Annotated[int, Field(ge=0)],
        "thinking.type": Literal["disabled", "enabled"],
        "thinking.budget_tokens": Annotated[int, Field(ge=1024)],
        "thinking.display": Literal["summarized", "omitted"],
    },
    total=False,
)
setattr(Claude_Opus_4_1_20250805_SubscriptionParams, "__pydantic_config__", _PARAMS_CONFIG)

Claude_Opus_4_20250514Params = TypedDict(
    "Claude_Opus_4_20250514Params",
    {
        "max_tokens": Annotated[int, Field(ge=1)],
        "temperature": Annotated[float, Field(ge=0, le=1)],
        "top_p": Annotated[float, Field(ge=0, le=1)],
        "top_k": Annotated[int, Field(ge=0)],
        "thinking.type": Literal["disabled", "enabled"],
        "thinking.budget_tokens": Annotated[int, Field(ge=1024)],
        "thinking.display": Literal["summarized", "omitted"],
    },
    total=False,
)
setattr(Claude_Opus_4_20250514Params, "__pydantic_config__", _PARAMS_CONFIG)

Claude_Opus_4_20250514_SubscriptionParams = TypedDict(
    "Claude_Opus_4_20250514_SubscriptionParams",
    {
        "max_tokens": Annotated[int, Field(ge=1)],
        "temperature": Annotated[float, Field(ge=0, le=1)],
        "top_p": Annotated[float, Field(ge=0, le=1)],
        "top_k": Annotated[int, Field(ge=0)],
        "thinking.type": Literal["disabled", "enabled"],
        "thinking.budget_tokens": Annotated[int, Field(ge=1024)],
        "thinking.display": Literal["summarized", "omitted"],
    },
    total=False,
)
setattr(Claude_Opus_4_20250514_SubscriptionParams, "__pydantic_config__", _PARAMS_CONFIG)

Claude_Opus_4_5_20251101Params = TypedDict(
    "Claude_Opus_4_5_20251101Params",
    {
        "max_tokens": Annotated[int, Field(ge=1)],
        "temperature": Annotated[float, Field(ge=0, le=1)],
        "top_p": Annotated[float, Field(ge=0, le=1)],
        "top_k": Annotated[int, Field(ge=0)],
        "thinking.type": Literal["disabled", "enabled"],
        "thinking.budget_tokens": Annotated[int, Field(ge=1024)],
        "thinking.display": Literal["summarized", "omitted"],
        "output_config.effort": Literal["low", "medium", "high"],
    },
    total=False,
)
setattr(Claude_Opus_4_5_20251101Params, "__pydantic_config__", _PARAMS_CONFIG)

Claude_Opus_4_5_20251101_SubscriptionParams = TypedDict(
    "Claude_Opus_4_5_20251101_SubscriptionParams",
    {
        "max_tokens": Annotated[int, Field(ge=1)],
        "temperature": Annotated[float, Field(ge=0, le=1)],
        "top_p": Annotated[float, Field(ge=0, le=1)],
        "top_k": Annotated[int, Field(ge=0)],
        "thinking.type": Literal["disabled", "enabled"],
        "thinking.budget_tokens": Annotated[int, Field(ge=1024)],
        "thinking.display": Literal["summarized", "omitted"],
        "output_config.effort": Literal["low", "medium", "high"],
    },
    total=False,
)
setattr(Claude_Opus_4_5_20251101_SubscriptionParams, "__pydantic_config__", _PARAMS_CONFIG)

Claude_Opus_4_6Params = TypedDict(
    "Claude_Opus_4_6Params",
    {
        "max_tokens": Annotated[int, Field(ge=1)],
        "temperature": Annotated[float, Field(ge=0, le=1)],
        "top_p": Annotated[float, Field(ge=0, le=1)],
        "top_k": Annotated[int, Field(ge=0)],
        "thinking.type": Literal["disabled", "adaptive", "enabled"],
        "thinking.budget_tokens": Annotated[int, Field(ge=1024)],
        "thinking.display": Literal["summarized", "omitted"],
        "output_config.effort": Literal["low", "medium", "high", "max"],
    },
    total=False,
)
setattr(Claude_Opus_4_6Params, "__pydantic_config__", _PARAMS_CONFIG)

Claude_Opus_4_6_SubscriptionParams = TypedDict(
    "Claude_Opus_4_6_SubscriptionParams",
    {
        "max_tokens": Annotated[int, Field(ge=1)],
        "temperature": Annotated[float, Field(ge=0, le=1)],
        "top_p": Annotated[float, Field(ge=0, le=1)],
        "top_k": Annotated[int, Field(ge=0)],
        "thinking.type": Literal["disabled", "adaptive", "enabled"],
        "thinking.budget_tokens": Annotated[int, Field(ge=1024)],
        "thinking.display": Literal["summarized", "omitted"],
        "output_config.effort": Literal["low", "medium", "high", "max"],
    },
    total=False,
)
setattr(Claude_Opus_4_6_SubscriptionParams, "__pydantic_config__", _PARAMS_CONFIG)

Claude_Opus_4_7Params = TypedDict(
    "Claude_Opus_4_7Params",
    {
        "max_tokens": Annotated[int, Field(ge=1)],
        "thinking.type": Literal["disabled", "adaptive"],
        "thinking.display": Literal["summarized", "omitted"],
        "output_config.effort": Literal["low", "medium", "high", "xhigh", "max"],
    },
    total=False,
)
setattr(Claude_Opus_4_7Params, "__pydantic_config__", _PARAMS_CONFIG)

Claude_Opus_4_7_SubscriptionParams = TypedDict(
    "Claude_Opus_4_7_SubscriptionParams",
    {
        "max_tokens": Annotated[int, Field(ge=1)],
        "thinking.type": Literal["disabled", "adaptive"],
        "thinking.display": Literal["summarized", "omitted"],
        "output_config.effort": Literal["low", "medium", "high", "xhigh", "max"],
    },
    total=False,
)
setattr(Claude_Opus_4_7_SubscriptionParams, "__pydantic_config__", _PARAMS_CONFIG)

Claude_Opus_4_8Params = TypedDict(
    "Claude_Opus_4_8Params",
    {
        "max_tokens": Annotated[int, Field(ge=1)],
        "thinking.type": Literal["disabled", "adaptive"],
        "thinking.display": Literal["summarized", "omitted"],
        "output_config.effort": Literal["low", "medium", "high", "xhigh", "max"],
    },
    total=False,
)
setattr(Claude_Opus_4_8Params, "__pydantic_config__", _PARAMS_CONFIG)

Claude_Opus_4_8_SubscriptionParams = TypedDict(
    "Claude_Opus_4_8_SubscriptionParams",
    {
        "max_tokens": Annotated[int, Field(ge=1)],
        "thinking.type": Literal["disabled", "adaptive"],
        "thinking.display": Literal["summarized", "omitted"],
        "output_config.effort": Literal["low", "medium", "high", "xhigh", "max"],
    },
    total=False,
)
setattr(Claude_Opus_4_8_SubscriptionParams, "__pydantic_config__", _PARAMS_CONFIG)

Claude_Opus_4_SubscriptionParams = TypedDict(
    "Claude_Opus_4_SubscriptionParams",
    {
        "max_tokens": Annotated[int, Field(ge=1)],
        "temperature": Annotated[float, Field(ge=0, le=1)],
        "top_p": Annotated[float, Field(ge=0, le=1)],
        "top_k": Annotated[int, Field(ge=0)],
        "thinking.type": Literal["disabled", "adaptive", "enabled"],
        "thinking.budget_tokens": Annotated[int, Field(ge=1024)],
    },
    total=False,
)
setattr(Claude_Opus_4_SubscriptionParams, "__pydantic_config__", _PARAMS_CONFIG)

Claude_Opus_5Params = TypedDict(
    "Claude_Opus_5Params",
    {
        "max_tokens": Annotated[int, Field(ge=1)],
        "thinking.type": Literal["disabled", "adaptive"],
        "thinking.display": Literal["summarized", "omitted"],
        "output_config.effort": Literal["low", "medium", "high", "xhigh", "max"],
    },
    total=False,
)
setattr(Claude_Opus_5Params, "__pydantic_config__", _PARAMS_CONFIG)

Claude_Opus_5_SubscriptionParams = TypedDict(
    "Claude_Opus_5_SubscriptionParams",
    {
        "max_tokens": Annotated[int, Field(ge=1)],
        "thinking.type": Literal["disabled", "adaptive"],
        "thinking.display": Literal["summarized", "omitted"],
        "output_config.effort": Literal["low", "medium", "high", "xhigh", "max"],
    },
    total=False,
)
setattr(Claude_Opus_5_SubscriptionParams, "__pydantic_config__", _PARAMS_CONFIG)

Claude_Sonnet_4_20250514Params = TypedDict(
    "Claude_Sonnet_4_20250514Params",
    {
        "max_tokens": Annotated[int, Field(ge=1)],
        "temperature": Annotated[float, Field(ge=0, le=1)],
        "top_p": Annotated[float, Field(ge=0, le=1)],
        "top_k": Annotated[int, Field(ge=0)],
        "thinking.type": Literal["disabled", "enabled"],
        "thinking.budget_tokens": Annotated[int, Field(ge=1024)],
        "thinking.display": Literal["summarized", "omitted"],
    },
    total=False,
)
setattr(Claude_Sonnet_4_20250514Params, "__pydantic_config__", _PARAMS_CONFIG)

Claude_Sonnet_4_20250514_SubscriptionParams = TypedDict(
    "Claude_Sonnet_4_20250514_SubscriptionParams",
    {
        "max_tokens": Annotated[int, Field(ge=1)],
        "temperature": Annotated[float, Field(ge=0, le=1)],
        "top_p": Annotated[float, Field(ge=0, le=1)],
        "top_k": Annotated[int, Field(ge=0)],
        "thinking.type": Literal["disabled", "enabled"],
        "thinking.budget_tokens": Annotated[int, Field(ge=1024)],
        "thinking.display": Literal["summarized", "omitted"],
    },
    total=False,
)
setattr(Claude_Sonnet_4_20250514_SubscriptionParams, "__pydantic_config__", _PARAMS_CONFIG)

Claude_Sonnet_4_5Params = TypedDict(
    "Claude_Sonnet_4_5Params",
    {
        "max_tokens": Annotated[int, Field(ge=1)],
        "temperature": Annotated[float, Field(ge=0, le=1)],
        "top_p": Annotated[float, Field(ge=0, le=1)],
        "top_k": Annotated[int, Field(ge=0)],
        "thinking.type": Literal["disabled", "adaptive", "enabled"],
        "thinking.budget_tokens": Annotated[int, Field(ge=1024)],
    },
    total=False,
)
setattr(Claude_Sonnet_4_5Params, "__pydantic_config__", _PARAMS_CONFIG)

Claude_Sonnet_4_5_20250929Params = TypedDict(
    "Claude_Sonnet_4_5_20250929Params",
    {
        "max_tokens": Annotated[int, Field(ge=1)],
        "temperature": Annotated[float, Field(ge=0, le=1)],
        "top_p": Annotated[float, Field(ge=0, le=1)],
        "top_k": Annotated[int, Field(ge=0)],
        "thinking.type": Literal["disabled", "enabled"],
        "thinking.budget_tokens": Annotated[int, Field(ge=1024)],
    },
    total=False,
)
setattr(Claude_Sonnet_4_5_20250929Params, "__pydantic_config__", _PARAMS_CONFIG)

Claude_Sonnet_4_5_20250929_SubscriptionParams = TypedDict(
    "Claude_Sonnet_4_5_20250929_SubscriptionParams",
    {
        "max_tokens": Annotated[int, Field(ge=1)],
        "temperature": Annotated[float, Field(ge=0, le=1)],
        "top_p": Annotated[float, Field(ge=0, le=1)],
        "top_k": Annotated[int, Field(ge=0)],
        "thinking.type": Literal["disabled", "enabled"],
        "thinking.budget_tokens": Annotated[int, Field(ge=1024)],
    },
    total=False,
)
setattr(Claude_Sonnet_4_5_20250929_SubscriptionParams, "__pydantic_config__", _PARAMS_CONFIG)

Claude_Sonnet_4_5_SubscriptionParams = TypedDict(
    "Claude_Sonnet_4_5_SubscriptionParams",
    {
        "max_tokens": Annotated[int, Field(ge=1)],
        "temperature": Annotated[float, Field(ge=0, le=1)],
        "top_p": Annotated[float, Field(ge=0, le=1)],
        "top_k": Annotated[int, Field(ge=0)],
        "thinking.type": Literal["disabled", "adaptive", "enabled"],
        "thinking.budget_tokens": Annotated[int, Field(ge=1024)],
    },
    total=False,
)
setattr(Claude_Sonnet_4_5_SubscriptionParams, "__pydantic_config__", _PARAMS_CONFIG)

Claude_Sonnet_4_6Params = TypedDict(
    "Claude_Sonnet_4_6Params",
    {
        "max_tokens": Annotated[int, Field(ge=1)],
        "temperature": Annotated[float, Field(ge=0, le=1)],
        "top_p": Annotated[float, Field(ge=0, le=1)],
        "top_k": Annotated[int, Field(ge=0)],
        "thinking.type": Literal["disabled", "adaptive", "enabled"],
        "thinking.budget_tokens": Annotated[int, Field(ge=1024)],
        "thinking.display": Literal["summarized", "omitted"],
        "output_config.effort": Literal["low", "medium", "high", "max"],
    },
    total=False,
)
setattr(Claude_Sonnet_4_6Params, "__pydantic_config__", _PARAMS_CONFIG)

Claude_Sonnet_4_6_SubscriptionParams = TypedDict(
    "Claude_Sonnet_4_6_SubscriptionParams",
    {
        "max_tokens": Annotated[int, Field(ge=1)],
        "temperature": Annotated[float, Field(ge=0, le=1)],
        "top_p": Annotated[float, Field(ge=0, le=1)],
        "top_k": Annotated[int, Field(ge=0)],
        "thinking.type": Literal["disabled", "adaptive", "enabled"],
        "thinking.budget_tokens": Annotated[int, Field(ge=1024)],
        "thinking.display": Literal["summarized", "omitted"],
        "output_config.effort": Literal["low", "medium", "high", "max"],
    },
    total=False,
)
setattr(Claude_Sonnet_4_6_SubscriptionParams, "__pydantic_config__", _PARAMS_CONFIG)

Claude_Sonnet_4_SubscriptionParams = TypedDict(
    "Claude_Sonnet_4_SubscriptionParams",
    {
        "max_tokens": Annotated[int, Field(ge=1)],
        "temperature": Annotated[float, Field(ge=0, le=1)],
        "top_p": Annotated[float, Field(ge=0, le=1)],
        "top_k": Annotated[int, Field(ge=0)],
        "thinking.type": Literal["disabled", "adaptive", "enabled"],
        "thinking.budget_tokens": Annotated[int, Field(ge=1024)],
    },
    total=False,
)
setattr(Claude_Sonnet_4_SubscriptionParams, "__pydantic_config__", _PARAMS_CONFIG)

Claude_Sonnet_5Params = TypedDict(
    "Claude_Sonnet_5Params",
    {
        "max_tokens": Annotated[int, Field(ge=1)],
        "temperature": Annotated[float, Field(ge=0, le=1)],
        "top_p": Annotated[float, Field(ge=0, le=1)],
        "top_k": Annotated[int, Field(ge=0)],
        "thinking.type": Literal["disabled", "adaptive"],
        "thinking.display": Literal["summarized", "omitted"],
        "output_config.effort": Literal["low", "medium", "high", "xhigh", "max"],
    },
    total=False,
)
setattr(Claude_Sonnet_5Params, "__pydantic_config__", _PARAMS_CONFIG)

__all__ = [
    "Claude_3_5_Haiku_20241022Params",
    "Claude_3_5_Haiku_LatestParams",
    "Claude_3_5_Sonnet_20241022Params",
    "Claude_3_5_Sonnet_LatestParams",
    "Claude_3_7_Sonnet_20250219Params",
    "Claude_3_7_Sonnet_LatestParams",
    "Claude_3_Opus_20240229Params",
    "Claude_3_Opus_LatestParams",
    "Claude_Fable_5Params",
    "Claude_Fable_5_SubscriptionParams",
    "Claude_Haiku_4Params",
    "Claude_Haiku_4_5Params",
    "Claude_Haiku_4_5_20251001Params",
    "Claude_Haiku_4_5_20251001_SubscriptionParams",
    "Claude_Haiku_4_5_SubscriptionParams",
    "Claude_Haiku_4_SubscriptionParams",
    "Claude_Opus_4_1_20250805Params",
    "Claude_Opus_4_1_20250805_SubscriptionParams",
    "Claude_Opus_4_20250514Params",
    "Claude_Opus_4_20250514_SubscriptionParams",
    "Claude_Opus_4_5_20251101Params",
    "Claude_Opus_4_5_20251101_SubscriptionParams",
    "Claude_Opus_4_6Params",
    "Claude_Opus_4_6_SubscriptionParams",
    "Claude_Opus_4_7Params",
    "Claude_Opus_4_7_SubscriptionParams",
    "Claude_Opus_4_8Params",
    "Claude_Opus_4_8_SubscriptionParams",
    "Claude_Opus_4_SubscriptionParams",
    "Claude_Opus_5Params",
    "Claude_Opus_5_SubscriptionParams",
    "Claude_Sonnet_4_20250514Params",
    "Claude_Sonnet_4_20250514_SubscriptionParams",
    "Claude_Sonnet_4_5Params",
    "Claude_Sonnet_4_5_20250929Params",
    "Claude_Sonnet_4_5_20250929_SubscriptionParams",
    "Claude_Sonnet_4_5_SubscriptionParams",
    "Claude_Sonnet_4_6Params",
    "Claude_Sonnet_4_6_SubscriptionParams",
    "Claude_Sonnet_4_SubscriptionParams",
    "Claude_Sonnet_5Params",
]
