# AUTO-GENERATED by packages/modelparams-python/scripts/codegen.ts.
# Do not edit by hand; the YAML catalog under /models is the source of truth.

# ruff: noqa: F401

from typing import Annotated, Literal

from pydantic import ConfigDict, Field
from typing_extensions import TypedDict

_PARAMS_CONFIG = ConfigDict(strict=True, extra="forbid")

Claude_Haiku_4_5Params = TypedDict(
    "Claude_Haiku_4_5Params",
    {
        "inferenceConfig.maxTokens": Annotated[int, Field(ge=1)],
        "inferenceConfig.temperature": Annotated[float, Field(ge=0, le=1)],
        "inferenceConfig.topP": Annotated[float, Field(ge=0, le=1)],
        "inferenceConfig.stopSequences": str,
        "additionalModelRequestFields.top_k": Annotated[int, Field(ge=0)],
        "additionalModelRequestFields.thinking.type": Literal["disabled", "enabled"],
        "additionalModelRequestFields.thinking.budget_tokens": Annotated[int, Field(ge=1024)],
    },
    total=False,
)
setattr(Claude_Haiku_4_5Params, "__pydantic_config__", _PARAMS_CONFIG)

Claude_Sonnet_4_5Params = TypedDict(
    "Claude_Sonnet_4_5Params",
    {
        "inferenceConfig.maxTokens": Annotated[int, Field(ge=1)],
        "inferenceConfig.temperature": Annotated[float, Field(ge=0, le=1)],
        "inferenceConfig.topP": Annotated[float, Field(ge=0, le=1)],
        "inferenceConfig.stopSequences": str,
        "additionalModelRequestFields.top_k": Annotated[int, Field(ge=0)],
        "additionalModelRequestFields.thinking.type": Literal["disabled", "enabled"],
        "additionalModelRequestFields.thinking.budget_tokens": Annotated[int, Field(ge=1024)],
    },
    total=False,
)
setattr(Claude_Sonnet_4_5Params, "__pydantic_config__", _PARAMS_CONFIG)

Nova_LiteParams = TypedDict(
    "Nova_LiteParams",
    {
        "inferenceConfig.maxTokens": Annotated[int, Field(ge=1)],
        "inferenceConfig.temperature": Annotated[float, Field(ge=0, le=1)],
        "inferenceConfig.topP": Annotated[float, Field(ge=0, le=1)],
        "inferenceConfig.stopSequences": str,
        "additionalModelRequestFields.inferenceConfig.topK": Annotated[int, Field(ge=1)],
    },
    total=False,
)
setattr(Nova_LiteParams, "__pydantic_config__", _PARAMS_CONFIG)

Nova_MicroParams = TypedDict(
    "Nova_MicroParams",
    {
        "inferenceConfig.maxTokens": Annotated[int, Field(ge=1)],
        "inferenceConfig.temperature": Annotated[float, Field(ge=0, le=1)],
        "inferenceConfig.topP": Annotated[float, Field(ge=0, le=1)],
        "inferenceConfig.stopSequences": str,
        "additionalModelRequestFields.inferenceConfig.topK": Annotated[int, Field(ge=1)],
    },
    total=False,
)
setattr(Nova_MicroParams, "__pydantic_config__", _PARAMS_CONFIG)

Nova_ProParams = TypedDict(
    "Nova_ProParams",
    {
        "inferenceConfig.maxTokens": Annotated[int, Field(ge=1)],
        "inferenceConfig.temperature": Annotated[float, Field(ge=0, le=1)],
        "inferenceConfig.topP": Annotated[float, Field(ge=0, le=1)],
        "inferenceConfig.stopSequences": str,
        "additionalModelRequestFields.inferenceConfig.topK": Annotated[int, Field(ge=1)],
    },
    total=False,
)
setattr(Nova_ProParams, "__pydantic_config__", _PARAMS_CONFIG)

__all__ = [
    "Claude_Haiku_4_5Params",
    "Claude_Sonnet_4_5Params",
    "Nova_LiteParams",
    "Nova_MicroParams",
    "Nova_ProParams",
]
