# AUTO-GENERATED by packages/modelparams-python/scripts/codegen.ts.
# Do not edit by hand; the YAML catalog under /models is the source of truth.

# ruff: noqa: F401

from typing import Annotated, Literal

from pydantic import ConfigDict, Field
from typing_extensions import TypedDict

_PARAMS_CONFIG = ConfigDict(strict=True, extra="forbid")

Zai_Glm_4_7Params = TypedDict(
    "Zai_Glm_4_7Params",
    {
        "max_completion_tokens": Annotated[int, Field(ge=1)],
        "temperature": Annotated[float, Field(ge=0, le=2)],
        "top_p": Annotated[float, Field(ge=0, le=1)],
        "frequency_penalty": Annotated[float, Field(ge=-2, le=2)],
        "presence_penalty": Annotated[float, Field(ge=-2, le=2)],
        "seed": int,
        "stop": str,
        "reasoning_effort": Literal["none", "low", "medium", "high"],
        "clear_thinking": bool,
        "response_format.type": Literal["text", "json_object"],
    },
    total=False,
)
setattr(Zai_Glm_4_7Params, "__pydantic_config__", _PARAMS_CONFIG)

__all__ = [
    "Zai_Glm_4_7Params",
]
