# AUTO-GENERATED by packages/modelparams-python/scripts/codegen.ts.
# Do not edit by hand; the YAML catalog under /models is the source of truth.

# ruff: noqa: F401

from typing import Annotated, Literal

from pydantic import ConfigDict, Field
from typing_extensions import TypedDict

_PARAMS_CONFIG = ConfigDict(strict=True, extra="forbid")

Command_A_03_2025Params = TypedDict(
    "Command_A_03_2025Params",
    {
        "max_tokens": Annotated[int, Field(ge=1)],
        "stop_sequences": str,
        "temperature": Annotated[float, Field(ge=0)],
        "p": Annotated[float, Field(ge=0.01, le=0.99)],
        "k": Annotated[int, Field(ge=0, le=500)],
        "frequency_penalty": Annotated[float, Field(ge=0, le=1)],
        "presence_penalty": Annotated[float, Field(ge=0, le=1)],
        "seed": int,
        "response_format.type": Literal["text", "json_object"],
        "logprobs": bool,
        "tool_choice": Literal["REQUIRED", "NONE"],
        "safety_mode": Literal["CONTEXTUAL", "STRICT"],
    },
    total=False,
)
setattr(Command_A_03_2025Params, "__pydantic_config__", _PARAMS_CONFIG)

Command_A_Plus_05_2026Params = TypedDict(
    "Command_A_Plus_05_2026Params",
    {
        "max_tokens": Annotated[int, Field(ge=1)],
        "stop_sequences": str,
        "temperature": Annotated[float, Field(ge=0)],
        "p": Annotated[float, Field(ge=0.01, le=0.99)],
        "k": Annotated[int, Field(ge=0, le=500)],
        "frequency_penalty": Annotated[float, Field(ge=0, le=1)],
        "presence_penalty": Annotated[float, Field(ge=0, le=1)],
        "seed": int,
        "response_format.type": Literal["text", "json_object"],
        "logprobs": bool,
        "tool_choice": Literal["REQUIRED", "NONE"],
        "safety_mode": Literal["CONTEXTUAL", "STRICT"],
    },
    total=False,
)
setattr(Command_A_Plus_05_2026Params, "__pydantic_config__", _PARAMS_CONFIG)

Command_A_Reasoning_08_2025Params = TypedDict(
    "Command_A_Reasoning_08_2025Params",
    {
        "max_tokens": Annotated[int, Field(ge=1)],
        "stop_sequences": str,
        "temperature": Annotated[float, Field(ge=0)],
        "p": Annotated[float, Field(ge=0.01, le=0.99)],
        "k": Annotated[int, Field(ge=0, le=500)],
        "frequency_penalty": Annotated[float, Field(ge=0, le=1)],
        "presence_penalty": Annotated[float, Field(ge=0, le=1)],
        "seed": int,
        "thinking.type": Literal["enabled", "disabled"],
        "thinking.token_budget": Annotated[int, Field(ge=1)],
        "response_format.type": Literal["text", "json_object"],
        "logprobs": bool,
        "tool_choice": Literal["REQUIRED", "NONE"],
        "safety_mode": Literal["CONTEXTUAL", "STRICT"],
    },
    total=False,
)
setattr(Command_A_Reasoning_08_2025Params, "__pydantic_config__", _PARAMS_CONFIG)

Command_A_Translate_08_2025Params = TypedDict(
    "Command_A_Translate_08_2025Params",
    {
        "max_tokens": Annotated[int, Field(ge=1)],
        "stop_sequences": str,
        "temperature": Annotated[float, Field(ge=0)],
        "p": Annotated[float, Field(ge=0.01, le=0.99)],
        "k": Annotated[int, Field(ge=0, le=500)],
        "frequency_penalty": Annotated[float, Field(ge=0, le=1)],
        "presence_penalty": Annotated[float, Field(ge=0, le=1)],
        "seed": int,
        "response_format.type": Literal["text", "json_object"],
        "logprobs": bool,
        "tool_choice": Literal["REQUIRED", "NONE"],
        "safety_mode": Literal["CONTEXTUAL", "STRICT"],
    },
    total=False,
)
setattr(Command_A_Translate_08_2025Params, "__pydantic_config__", _PARAMS_CONFIG)

Command_A_Vision_07_2025Params = TypedDict(
    "Command_A_Vision_07_2025Params",
    {
        "max_tokens": Annotated[int, Field(ge=1)],
        "stop_sequences": str,
        "temperature": Annotated[float, Field(ge=0)],
        "p": Annotated[float, Field(ge=0.01, le=0.99)],
        "k": Annotated[int, Field(ge=0, le=500)],
        "frequency_penalty": Annotated[float, Field(ge=0, le=1)],
        "presence_penalty": Annotated[float, Field(ge=0, le=1)],
        "seed": int,
        "response_format.type": Literal["text", "json_object"],
        "logprobs": bool,
        "tool_choice": Literal["REQUIRED", "NONE"],
        "safety_mode": Literal["CONTEXTUAL", "STRICT"],
    },
    total=False,
)
setattr(Command_A_Vision_07_2025Params, "__pydantic_config__", _PARAMS_CONFIG)

Command_R_08_2024Params = TypedDict(
    "Command_R_08_2024Params",
    {
        "max_tokens": Annotated[int, Field(ge=1)],
        "stop_sequences": str,
        "temperature": Annotated[float, Field(ge=0)],
        "p": Annotated[float, Field(ge=0.01, le=0.99)],
        "k": Annotated[int, Field(ge=0, le=500)],
        "frequency_penalty": Annotated[float, Field(ge=0, le=1)],
        "presence_penalty": Annotated[float, Field(ge=0, le=1)],
        "seed": int,
        "response_format.type": Literal["text", "json_object"],
        "logprobs": bool,
        "safety_mode": Literal["CONTEXTUAL", "STRICT", "OFF"],
    },
    total=False,
)
setattr(Command_R_08_2024Params, "__pydantic_config__", _PARAMS_CONFIG)

Command_R_Plus_08_2024Params = TypedDict(
    "Command_R_Plus_08_2024Params",
    {
        "max_tokens": Annotated[int, Field(ge=1)],
        "stop_sequences": str,
        "temperature": Annotated[float, Field(ge=0)],
        "p": Annotated[float, Field(ge=0.01, le=0.99)],
        "k": Annotated[int, Field(ge=0, le=500)],
        "frequency_penalty": Annotated[float, Field(ge=0, le=1)],
        "presence_penalty": Annotated[float, Field(ge=0, le=1)],
        "seed": int,
        "response_format.type": Literal["text", "json_object"],
        "logprobs": bool,
        "safety_mode": Literal["CONTEXTUAL", "STRICT", "OFF"],
    },
    total=False,
)
setattr(Command_R_Plus_08_2024Params, "__pydantic_config__", _PARAMS_CONFIG)

Command_R7b_12_2024Params = TypedDict(
    "Command_R7b_12_2024Params",
    {
        "max_tokens": Annotated[int, Field(ge=1)],
        "stop_sequences": str,
        "temperature": Annotated[float, Field(ge=0)],
        "p": Annotated[float, Field(ge=0.01, le=0.99)],
        "k": Annotated[int, Field(ge=0, le=500)],
        "frequency_penalty": Annotated[float, Field(ge=0, le=1)],
        "presence_penalty": Annotated[float, Field(ge=0, le=1)],
        "seed": int,
        "response_format.type": Literal["text", "json_object"],
        "logprobs": bool,
        "tool_choice": Literal["REQUIRED", "NONE"],
        "safety_mode": Literal["CONTEXTUAL", "STRICT"],
    },
    total=False,
)
setattr(Command_R7b_12_2024Params, "__pydantic_config__", _PARAMS_CONFIG)

__all__ = [
    "Command_A_03_2025Params",
    "Command_A_Plus_05_2026Params",
    "Command_A_Reasoning_08_2025Params",
    "Command_A_Translate_08_2025Params",
    "Command_A_Vision_07_2025Params",
    "Command_R_08_2024Params",
    "Command_R_Plus_08_2024Params",
    "Command_R7b_12_2024Params",
]
