# AUTO-GENERATED by packages/modelparams-python/scripts/codegen.ts.
# Do not edit by hand; the YAML catalog under /models is the source of truth.

# ruff: noqa: F401

from typing import Annotated, Literal

from pydantic import ConfigDict, Field
from typing_extensions import TypedDict

_PARAMS_CONFIG = ConfigDict(strict=True, extra="forbid")

Deepseek_ChatParams = TypedDict(
    "Deepseek_ChatParams",
    {
        "max_tokens": Annotated[int, Field(ge=1)],
        "temperature": Annotated[float, Field(ge=0, le=2)],
        "top_p": Annotated[float, Field(ge=0, le=1)],
        "thinking.type": Literal["disabled", "enabled"],
    },
    total=False,
)
setattr(Deepseek_ChatParams, "__pydantic_config__", _PARAMS_CONFIG)

Deepseek_ReasonerParams = TypedDict(
    "Deepseek_ReasonerParams",
    {
        "max_tokens": Annotated[int, Field(ge=1)],
        "temperature": Annotated[float, Field(ge=0, le=2)],
        "top_p": Annotated[float, Field(ge=0, le=1)],
        "thinking.type": Literal["enabled", "disabled"],
        "reasoning_effort": Literal["high", "max"],
    },
    total=False,
)
setattr(Deepseek_ReasonerParams, "__pydantic_config__", _PARAMS_CONFIG)

Deepseek_V4_FlashParams = TypedDict(
    "Deepseek_V4_FlashParams",
    {
        "max_tokens": Annotated[int, Field(ge=1)],
        "temperature": Annotated[float, Field(ge=0, le=2)],
        "top_p": Annotated[float, Field(ge=0, le=1)],
        "thinking.type": Literal["enabled", "disabled"],
        "reasoning_effort": Literal["high", "max"],
    },
    total=False,
)
setattr(Deepseek_V4_FlashParams, "__pydantic_config__", _PARAMS_CONFIG)

Deepseek_V4_ProParams = TypedDict(
    "Deepseek_V4_ProParams",
    {
        "max_tokens": Annotated[int, Field(ge=1)],
        "temperature": Annotated[float, Field(ge=0, le=2)],
        "top_p": Annotated[float, Field(ge=0, le=1)],
        "thinking.type": Literal["enabled", "disabled"],
        "reasoning_effort": Literal["high", "max"],
    },
    total=False,
)
setattr(Deepseek_V4_ProParams, "__pydantic_config__", _PARAMS_CONFIG)

__all__ = [
    "Deepseek_ChatParams",
    "Deepseek_ReasonerParams",
    "Deepseek_V4_FlashParams",
    "Deepseek_V4_ProParams",
]
