# AUTO-GENERATED by packages/modelparams-python/scripts/codegen.ts.
# Do not edit by hand; the YAML catalog under /models is the source of truth.

# ruff: noqa: F401

from typing import Annotated, Literal

from pydantic import ConfigDict, Field
from typing_extensions import TypedDict

_PARAMS_CONFIG = ConfigDict(strict=True, extra="forbid")

Deepseek_V4_Flash_0731Params = TypedDict(
    "Deepseek_V4_Flash_0731Params",
    {
        "max_tokens": Annotated[int, Field(ge=1)],
        "temperature": Annotated[float, Field(ge=0, le=2)],
        "top_p": Annotated[float, Field(ge=0, le=1)],
        "top_k": Annotated[int, Field(ge=1, le=100)],
        "presence_penalty": Annotated[float, Field(ge=-2, le=2)],
        "frequency_penalty": Annotated[float, Field(ge=-2, le=2)],
        "response_format.type": Literal["text", "json_object"],
    },
    total=False,
)
setattr(Deepseek_V4_Flash_0731Params, "__pydantic_config__", _PARAMS_CONFIG)

Deepseek_V4_ProParams = TypedDict(
    "Deepseek_V4_ProParams",
    {
        "max_tokens": Annotated[int, Field(ge=1)],
        "temperature": Annotated[float, Field(ge=0, le=2)],
        "top_p": Annotated[float, Field(ge=0, le=1)],
        "top_k": Annotated[int, Field(ge=1, le=100)],
        "presence_penalty": Annotated[float, Field(ge=-2, le=2)],
        "frequency_penalty": Annotated[float, Field(ge=-2, le=2)],
        "response_format.type": Literal["text", "json_object"],
    },
    total=False,
)
setattr(Deepseek_V4_ProParams, "__pydantic_config__", _PARAMS_CONFIG)

Deepseek_V4_Pro_0813Params = TypedDict(
    "Deepseek_V4_Pro_0813Params",
    {
        "max_tokens": Annotated[int, Field(ge=1)],
        "temperature": Annotated[float, Field(ge=0, le=2)],
        "top_p": Annotated[float, Field(ge=0, le=1)],
        "top_k": Annotated[int, Field(ge=1, le=100)],
        "presence_penalty": Annotated[float, Field(ge=-2, le=2)],
        "frequency_penalty": Annotated[float, Field(ge=-2, le=2)],
        "response_format.type": Literal["text", "json_object"],
    },
    total=False,
)
setattr(Deepseek_V4_Pro_0813Params, "__pydantic_config__", _PARAMS_CONFIG)

Glm_5p2Params = TypedDict(
    "Glm_5p2Params",
    {
        "max_tokens": Annotated[int, Field(ge=1)],
        "temperature": Annotated[float, Field(ge=0, le=2)],
        "top_p": Annotated[float, Field(ge=0, le=1)],
        "top_k": Annotated[int, Field(ge=1, le=100)],
        "presence_penalty": Annotated[float, Field(ge=-2, le=2)],
        "frequency_penalty": Annotated[float, Field(ge=-2, le=2)],
        "response_format.type": Literal["text", "json_object"],
    },
    total=False,
)
setattr(Glm_5p2Params, "__pydantic_config__", _PARAMS_CONFIG)

Gpt_Oss_120bParams = TypedDict(
    "Gpt_Oss_120bParams",
    {
        "max_tokens": Annotated[int, Field(ge=1)],
        "temperature": Annotated[float, Field(ge=0, le=2)],
        "top_p": Annotated[float, Field(ge=0, le=1)],
        "top_k": Annotated[int, Field(ge=1, le=100)],
        "presence_penalty": Annotated[float, Field(ge=-2, le=2)],
        "frequency_penalty": Annotated[float, Field(ge=-2, le=2)],
        "response_format.type": Literal["text", "json_object"],
    },
    total=False,
)
setattr(Gpt_Oss_120bParams, "__pydantic_config__", _PARAMS_CONFIG)

InklingParams = TypedDict(
    "InklingParams",
    {
        "max_tokens": Annotated[int, Field(ge=1)],
        "temperature": Annotated[float, Field(ge=0, le=2)],
        "top_p": Annotated[float, Field(ge=0, le=1)],
        "top_k": Annotated[int, Field(ge=1, le=100)],
        "presence_penalty": Annotated[float, Field(ge=-2, le=2)],
        "frequency_penalty": Annotated[float, Field(ge=-2, le=2)],
        "response_format.type": Literal["text", "json_object"],
    },
    total=False,
)
setattr(InklingParams, "__pydantic_config__", _PARAMS_CONFIG)

Kimi_K2p7_CodeParams = TypedDict(
    "Kimi_K2p7_CodeParams",
    {
        "max_tokens": Annotated[int, Field(ge=1)],
        "temperature": Annotated[float, Field(ge=0, le=2)],
        "top_p": Annotated[float, Field(ge=0, le=1)],
        "top_k": Annotated[int, Field(ge=1, le=100)],
        "presence_penalty": Annotated[float, Field(ge=-2, le=2)],
        "frequency_penalty": Annotated[float, Field(ge=-2, le=2)],
        "response_format.type": Literal["text", "json_object"],
    },
    total=False,
)
setattr(Kimi_K2p7_CodeParams, "__pydantic_config__", _PARAMS_CONFIG)

Kimi_K3Params = TypedDict(
    "Kimi_K3Params",
    {
        "max_tokens": Annotated[int, Field(ge=1)],
        "temperature": Annotated[float, Field(ge=0, le=2)],
        "top_p": Annotated[float, Field(ge=0, le=1)],
        "top_k": Annotated[int, Field(ge=1, le=100)],
        "presence_penalty": Annotated[float, Field(ge=-2, le=2)],
        "frequency_penalty": Annotated[float, Field(ge=-2, le=2)],
        "response_format.type": Literal["text", "json_object"],
    },
    total=False,
)
setattr(Kimi_K3Params, "__pydantic_config__", _PARAMS_CONFIG)

Minimax_M2p7Params = TypedDict(
    "Minimax_M2p7Params",
    {
        "max_tokens": Annotated[int, Field(ge=1)],
        "temperature": Annotated[float, Field(ge=0, le=2)],
        "top_p": Annotated[float, Field(ge=0, le=1)],
        "top_k": Annotated[int, Field(ge=1, le=100)],
        "presence_penalty": Annotated[float, Field(ge=-2, le=2)],
        "frequency_penalty": Annotated[float, Field(ge=-2, le=2)],
        "response_format.type": Literal["text", "json_object"],
    },
    total=False,
)
setattr(Minimax_M2p7Params, "__pydantic_config__", _PARAMS_CONFIG)

Muse_Glimmer_30bParams = TypedDict(
    "Muse_Glimmer_30bParams",
    {
        "max_tokens": Annotated[int, Field(ge=1)],
        "temperature": Annotated[float, Field(ge=0, le=2)],
        "top_p": Annotated[float, Field(ge=0, le=1)],
        "top_k": Annotated[int, Field(ge=1, le=100)],
        "presence_penalty": Annotated[float, Field(ge=-2, le=2)],
        "frequency_penalty": Annotated[float, Field(ge=-2, le=2)],
        "response_format.type": Literal["text", "json_object"],
    },
    total=False,
)
setattr(Muse_Glimmer_30bParams, "__pydantic_config__", _PARAMS_CONFIG)

Qwen3p8_2p4t_A95bParams = TypedDict(
    "Qwen3p8_2p4t_A95bParams",
    {
        "max_tokens": Annotated[int, Field(ge=1)],
        "temperature": Annotated[float, Field(ge=0, le=2)],
        "top_p": Annotated[float, Field(ge=0, le=1)],
        "top_k": Annotated[int, Field(ge=1, le=100)],
        "presence_penalty": Annotated[float, Field(ge=-2, le=2)],
        "frequency_penalty": Annotated[float, Field(ge=-2, le=2)],
        "response_format.type": Literal["text", "json_object"],
    },
    total=False,
)
setattr(Qwen3p8_2p4t_A95bParams, "__pydantic_config__", _PARAMS_CONFIG)

__all__ = [
    "Deepseek_V4_Flash_0731Params",
    "Deepseek_V4_ProParams",
    "Deepseek_V4_Pro_0813Params",
    "Glm_5p2Params",
    "Gpt_Oss_120bParams",
    "InklingParams",
    "Kimi_K2p7_CodeParams",
    "Kimi_K3Params",
    "Minimax_M2p7Params",
    "Muse_Glimmer_30bParams",
    "Qwen3p8_2p4t_A95bParams",
]
