# AUTO-GENERATED by packages/modelparams-python/scripts/codegen.ts.
# Do not edit by hand; the YAML catalog under /models is the source of truth.

# ruff: noqa: F401

from typing import Annotated, Literal

from pydantic import ConfigDict, Field
from typing_extensions import TypedDict

_PARAMS_CONFIG = ConfigDict(strict=True, extra="forbid")

Deepseek_V4_Flash_0731Params = TypedDict(
    "Deepseek_V4_Flash_0731Params",
    {
        "max_tokens": Annotated[int, Field(ge=1)],
        "temperature": Annotated[float, Field(ge=0, le=2)],
        "top_p": Annotated[float, Field(ge=0, le=1)],
        "top_k": Annotated[int, Field(ge=1, le=100)],
        "presence_penalty": Annotated[float, Field(ge=-2, le=2)],
        "frequency_penalty": Annotated[float, Field(ge=-2, le=2)],
        "response_format.type": Literal["text", "json_object"],
    },
    total=False,
)
setattr(Deepseek_V4_Flash_0731Params, "__pydantic_config__", _PARAMS_CONFIG)

Kimi_K3Params = TypedDict(
    "Kimi_K3Params",
    {
        "max_tokens": Annotated[int, Field(ge=1)],
        "temperature": Annotated[float, Field(ge=0, le=2)],
        "top_p": Annotated[float, Field(ge=0, le=1)],
        "top_k": Annotated[int, Field(ge=1, le=100)],
        "presence_penalty": Annotated[float, Field(ge=-2, le=2)],
        "frequency_penalty": Annotated[float, Field(ge=-2, le=2)],
        "response_format.type": Literal["text", "json_object"],
    },
    total=False,
)
setattr(Kimi_K3Params, "__pydantic_config__", _PARAMS_CONFIG)

__all__ = [
    "Deepseek_V4_Flash_0731Params",
    "Kimi_K3Params",
]
