# AUTO-GENERATED by packages/modelparams-python/scripts/codegen.ts.
# Do not edit by hand; the YAML catalog under /models is the source of truth.

# ruff: noqa: F401

from typing import Annotated, Literal

from pydantic import ConfigDict, Field
from typing_extensions import TypedDict

_PARAMS_CONFIG = ConfigDict(strict=True, extra="forbid")

Gemini_2_5_FlashParams = TypedDict(
    "Gemini_2_5_FlashParams",
    {
        "generationConfig.maxOutputTokens": Annotated[int, Field(ge=1, le=65536)],
        "generationConfig.temperature": Annotated[float, Field(ge=0, le=2)],
        "generationConfig.topP": Annotated[float, Field(ge=0, le=1)],
        "generationConfig.topK": Annotated[int, Field(ge=0)],
        "generationConfig.seed": int,
        "generationConfig.thinkingConfig.thinkingBudget": Annotated[int, Field(ge=-1, le=24576)],
        "generationConfig.thinkingConfig.includeThoughts": bool,
        "generationConfig.responseMimeType": Literal["text/plain", "application/json"],
    },
    total=False,
)
setattr(Gemini_2_5_FlashParams, "__pydantic_config__", _PARAMS_CONFIG)

Gemini_2_5_Flash_LiteParams = TypedDict(
    "Gemini_2_5_Flash_LiteParams",
    {
        "generationConfig.maxOutputTokens": Annotated[int, Field(ge=1, le=65536)],
        "generationConfig.temperature": Annotated[float, Field(ge=0, le=2)],
        "generationConfig.topP": Annotated[float, Field(ge=0, le=1)],
        "generationConfig.topK": Annotated[int, Field(ge=0)],
        "generationConfig.seed": int,
        "generationConfig.thinkingConfig.thinkingBudget": int,
        "generationConfig.thinkingConfig.includeThoughts": bool,
        "generationConfig.responseMimeType": Literal["text/plain", "application/json"],
    },
    total=False,
)
setattr(Gemini_2_5_Flash_LiteParams, "__pydantic_config__", _PARAMS_CONFIG)

Gemini_2_5_Flash_Lite_SubscriptionParams = TypedDict(
    "Gemini_2_5_Flash_Lite_SubscriptionParams",
    {
        "generationConfig.maxOutputTokens": Annotated[int, Field(ge=1, le=65536)],
        "generationConfig.temperature": Annotated[float, Field(ge=0, le=2)],
        "generationConfig.topP": Annotated[float, Field(ge=0, le=1)],
        "generationConfig.topK": Annotated[int, Field(ge=0)],
        "generationConfig.seed": int,
        "generationConfig.thinkingConfig.thinkingBudget": int,
        "generationConfig.thinkingConfig.includeThoughts": bool,
        "generationConfig.responseMimeType": Literal["text/plain", "application/json"],
    },
    total=False,
)
setattr(Gemini_2_5_Flash_Lite_SubscriptionParams, "__pydantic_config__", _PARAMS_CONFIG)

Gemini_2_5_Flash_SubscriptionParams = TypedDict(
    "Gemini_2_5_Flash_SubscriptionParams",
    {
        "generationConfig.maxOutputTokens": Annotated[int, Field(ge=1, le=65536)],
        "generationConfig.temperature": Annotated[float, Field(ge=0, le=2)],
        "generationConfig.topP": Annotated[float, Field(ge=0, le=1)],
        "generationConfig.topK": Annotated[int, Field(ge=0)],
        "generationConfig.seed": int,
        "generationConfig.thinkingConfig.thinkingBudget": Annotated[int, Field(ge=-1, le=24576)],
        "generationConfig.thinkingConfig.includeThoughts": bool,
        "generationConfig.responseMimeType": Literal["text/plain", "application/json"],
    },
    total=False,
)
setattr(Gemini_2_5_Flash_SubscriptionParams, "__pydantic_config__", _PARAMS_CONFIG)

Gemini_2_5_ProParams = TypedDict(
    "Gemini_2_5_ProParams",
    {
        "generationConfig.maxOutputTokens": Annotated[int, Field(ge=1, le=65536)],
        "generationConfig.temperature": Annotated[float, Field(ge=0, le=2)],
        "generationConfig.topP": Annotated[float, Field(ge=0, le=1)],
        "generationConfig.topK": Annotated[int, Field(ge=0)],
        "generationConfig.seed": int,
        "generationConfig.thinkingConfig.thinkingBudget": Annotated[int, Field(ge=128, le=32768)],
        "generationConfig.thinkingConfig.includeThoughts": bool,
        "generationConfig.responseMimeType": Literal["text/plain", "application/json"],
    },
    total=False,
)
setattr(Gemini_2_5_ProParams, "__pydantic_config__", _PARAMS_CONFIG)

Gemini_2_5_Pro_SubscriptionParams = TypedDict(
    "Gemini_2_5_Pro_SubscriptionParams",
    {
        "generationConfig.maxOutputTokens": Annotated[int, Field(ge=1, le=65536)],
        "generationConfig.temperature": Annotated[float, Field(ge=0, le=2)],
        "generationConfig.topP": Annotated[float, Field(ge=0, le=1)],
        "generationConfig.topK": Annotated[int, Field(ge=0)],
        "generationConfig.seed": int,
        "generationConfig.thinkingConfig.thinkingBudget": Annotated[int, Field(ge=128, le=32768)],
        "generationConfig.thinkingConfig.includeThoughts": bool,
        "generationConfig.responseMimeType": Literal["text/plain", "application/json"],
    },
    total=False,
)
setattr(Gemini_2_5_Pro_SubscriptionParams, "__pydantic_config__", _PARAMS_CONFIG)

Gemini_3_Flash_Preview_SubscriptionParams = TypedDict(
    "Gemini_3_Flash_Preview_SubscriptionParams",
    {
        "generationConfig.maxOutputTokens": Annotated[int, Field(ge=1, le=65536)],
        "generationConfig.temperature": Annotated[float, Field(ge=0, le=2)],
        "generationConfig.topP": Annotated[float, Field(ge=0, le=1)],
        "generationConfig.topK": Annotated[int, Field(ge=0)],
        "generationConfig.seed": int,
        "generationConfig.thinkingConfig.thinkingLevel": Literal["minimal", "low", "medium", "high"],
        "generationConfig.thinkingConfig.includeThoughts": bool,
        "generationConfig.responseMimeType": Literal["text/plain", "application/json"],
    },
    total=False,
)
setattr(Gemini_3_Flash_Preview_SubscriptionParams, "__pydantic_config__", _PARAMS_CONFIG)

Gemini_3_Pro_ImageParams = TypedDict(
    "Gemini_3_Pro_ImageParams",
    {
        "generationConfig.maxOutputTokens": Annotated[int, Field(ge=1, le=65536)],
        "generationConfig.temperature": Annotated[float, Field(ge=0, le=2)],
        "generationConfig.topP": Annotated[float, Field(ge=0, le=1)],
        "generationConfig.topK": Annotated[int, Field(ge=0)],
        "generationConfig.seed": int,
        "generationConfig.thinkingConfig.thinkingLevel": Literal["minimal", "low", "medium", "high"],
        "generationConfig.thinkingConfig.includeThoughts": bool,
        "generationConfig.responseMimeType": Literal["text/plain", "application/json"],
    },
    total=False,
)
setattr(Gemini_3_Pro_ImageParams, "__pydantic_config__", _PARAMS_CONFIG)

Gemini_3_1_Flash_ImageParams = TypedDict(
    "Gemini_3_1_Flash_ImageParams",
    {
        "generationConfig.maxOutputTokens": Annotated[int, Field(ge=1, le=65536)],
        "generationConfig.temperature": Annotated[float, Field(ge=0, le=2)],
        "generationConfig.topP": Annotated[float, Field(ge=0, le=1)],
        "generationConfig.topK": Annotated[int, Field(ge=0)],
        "generationConfig.seed": int,
        "generationConfig.thinkingConfig.thinkingLevel": Literal["minimal", "high"],
        "generationConfig.thinkingConfig.includeThoughts": bool,
        "generationConfig.responseMimeType": Literal["text/plain", "application/json"],
    },
    total=False,
)
setattr(Gemini_3_1_Flash_ImageParams, "__pydantic_config__", _PARAMS_CONFIG)

Gemini_3_1_Flash_LiteParams = TypedDict(
    "Gemini_3_1_Flash_LiteParams",
    {
        "generationConfig.maxOutputTokens": Annotated[int, Field(ge=1, le=65536)],
        "generationConfig.temperature": Annotated[float, Field(ge=0, le=2)],
        "generationConfig.topP": Annotated[float, Field(ge=0, le=1)],
        "generationConfig.topK": Annotated[int, Field(ge=0)],
        "generationConfig.seed": int,
        "generationConfig.thinkingConfig.thinkingLevel": Literal["minimal", "low", "medium", "high"],
        "generationConfig.thinkingConfig.includeThoughts": bool,
        "generationConfig.responseMimeType": Literal["text/plain", "application/json"],
    },
    total=False,
)
setattr(Gemini_3_1_Flash_LiteParams, "__pydantic_config__", _PARAMS_CONFIG)

Gemini_3_1_Flash_Lite_Preview_SubscriptionParams = TypedDict(
    "Gemini_3_1_Flash_Lite_Preview_SubscriptionParams",
    {
        "generationConfig.maxOutputTokens": Annotated[int, Field(ge=1, le=65536)],
        "generationConfig.temperature": Annotated[float, Field(ge=0, le=2)],
        "generationConfig.topP": Annotated[float, Field(ge=0, le=1)],
        "generationConfig.topK": Annotated[int, Field(ge=0)],
        "generationConfig.seed": int,
        "generationConfig.thinkingConfig.thinkingLevel": Literal["minimal", "low", "medium", "high"],
        "generationConfig.thinkingConfig.includeThoughts": bool,
        "generationConfig.responseMimeType": Literal["text/plain", "application/json"],
    },
    total=False,
)
setattr(Gemini_3_1_Flash_Lite_Preview_SubscriptionParams, "__pydantic_config__", _PARAMS_CONFIG)

Gemini_3_1_Flash_Lite_SubscriptionParams = TypedDict(
    "Gemini_3_1_Flash_Lite_SubscriptionParams",
    {
        "generationConfig.maxOutputTokens": Annotated[int, Field(ge=1, le=65536)],
        "generationConfig.temperature": Annotated[float, Field(ge=0, le=2)],
        "generationConfig.topP": Annotated[float, Field(ge=0, le=1)],
        "generationConfig.topK": Annotated[int, Field(ge=0)],
        "generationConfig.seed": int,
        "generationConfig.thinkingConfig.thinkingLevel": Literal["minimal", "low", "medium", "high"],
        "generationConfig.thinkingConfig.includeThoughts": bool,
        "generationConfig.responseMimeType": Literal["text/plain", "application/json"],
    },
    total=False,
)
setattr(Gemini_3_1_Flash_Lite_SubscriptionParams, "__pydantic_config__", _PARAMS_CONFIG)

Gemini_3_1_Pro_Preview_SubscriptionParams = TypedDict(
    "Gemini_3_1_Pro_Preview_SubscriptionParams",
    {
        "generationConfig.maxOutputTokens": Annotated[int, Field(ge=1, le=65536)],
        "generationConfig.temperature": Annotated[float, Field(ge=0, le=2)],
        "generationConfig.topP": Annotated[float, Field(ge=0, le=1)],
        "generationConfig.topK": Annotated[int, Field(ge=0)],
        "generationConfig.seed": int,
        "generationConfig.thinkingConfig.thinkingLevel": Literal["low", "high"],
        "generationConfig.thinkingConfig.includeThoughts": bool,
        "generationConfig.responseMimeType": Literal["text/plain", "application/json"],
    },
    total=False,
)
setattr(Gemini_3_1_Pro_Preview_SubscriptionParams, "__pydantic_config__", _PARAMS_CONFIG)

Gemini_3_5_FlashParams = TypedDict(
    "Gemini_3_5_FlashParams",
    {
        "generationConfig.maxOutputTokens": Annotated[int, Field(ge=1, le=65536)],
        "generationConfig.temperature": Annotated[float, Field(ge=0, le=2)],
        "generationConfig.topP": Annotated[float, Field(ge=0, le=1)],
        "generationConfig.topK": Annotated[int, Field(ge=0)],
        "generationConfig.seed": int,
        "generationConfig.thinkingConfig.thinkingLevel": Literal["minimal", "low", "medium", "high"],
        "generationConfig.thinkingConfig.includeThoughts": bool,
        "generationConfig.responseMimeType": Literal["text/plain", "application/json"],
    },
    total=False,
)
setattr(Gemini_3_5_FlashParams, "__pydantic_config__", _PARAMS_CONFIG)

Gemini_3_5_Flash_LiteParams = TypedDict(
    "Gemini_3_5_Flash_LiteParams",
    {
        "generationConfig.maxOutputTokens": Annotated[int, Field(ge=1, le=65536)],
        "generationConfig.temperature": Annotated[float, Field(ge=0, le=2)],
        "generationConfig.topP": Annotated[float, Field(ge=0, le=1)],
        "generationConfig.topK": Annotated[int, Field(ge=0)],
        "generationConfig.seed": int,
        "generationConfig.thinkingConfig.thinkingLevel": Literal["minimal", "low", "medium", "high"],
        "generationConfig.thinkingConfig.includeThoughts": bool,
        "generationConfig.responseMimeType": Literal["text/plain", "application/json"],
    },
    total=False,
)
setattr(Gemini_3_5_Flash_LiteParams, "__pydantic_config__", _PARAMS_CONFIG)

Gemini_3_6_FlashParams = TypedDict(
    "Gemini_3_6_FlashParams",
    {
        "generationConfig.maxOutputTokens": Annotated[int, Field(ge=1, le=65536)],
        "generationConfig.temperature": Annotated[float, Field(ge=0, le=2)],
        "generationConfig.topP": Annotated[float, Field(ge=0, le=1)],
        "generationConfig.topK": Annotated[int, Field(ge=0)],
        "generationConfig.seed": int,
        "generationConfig.thinkingConfig.thinkingLevel": Literal["minimal", "low", "medium", "high"],
        "generationConfig.thinkingConfig.includeThoughts": bool,
        "generationConfig.responseMimeType": Literal["text/plain", "application/json"],
    },
    total=False,
)
setattr(Gemini_3_6_FlashParams, "__pydantic_config__", _PARAMS_CONFIG)

Gemini_3_7_FlashParams = TypedDict(
    "Gemini_3_7_FlashParams",
    {
        "generationConfig.maxOutputTokens": Annotated[int, Field(ge=1, le=65536)],
        "generationConfig.temperature": Annotated[float, Field(ge=0, le=2)],
        "generationConfig.topP": Annotated[float, Field(ge=0, le=1)],
        "generationConfig.topK": Annotated[int, Field(ge=0)],
        "generationConfig.seed": int,
        "generationConfig.thinkingConfig.thinkingLevel": Literal["minimal", "low", "medium", "high"],
        "generationConfig.thinkingConfig.includeThoughts": bool,
        "generationConfig.responseMimeType": Literal["text/plain", "application/json"],
    },
    total=False,
)
setattr(Gemini_3_7_FlashParams, "__pydantic_config__", _PARAMS_CONFIG)

Gemini_Flash_LatestParams = TypedDict(
    "Gemini_Flash_LatestParams",
    {
        "generationConfig.maxOutputTokens": Annotated[int, Field(ge=1, le=65536)],
        "generationConfig.temperature": Annotated[float, Field(ge=0, le=2)],
        "generationConfig.topP": Annotated[float, Field(ge=0, le=1)],
        "generationConfig.topK": Annotated[int, Field(ge=0)],
        "generationConfig.seed": int,
        "generationConfig.thinkingConfig.thinkingBudget": int,
        "generationConfig.thinkingConfig.includeThoughts": bool,
        "generationConfig.responseMimeType": Literal["text/plain", "application/json"],
    },
    total=False,
)
setattr(Gemini_Flash_LatestParams, "__pydantic_config__", _PARAMS_CONFIG)

Gemma_3_12b_ItParams = TypedDict(
    "Gemma_3_12b_ItParams",
    {
        "max_completion_tokens": Annotated[int, Field(ge=1, le=131072)],
        "temperature": float,
        "top_p": Annotated[float, Field(ge=0, le=1)],
        "top_k": Annotated[int, Field(ge=0)],
    },
    total=False,
)
setattr(Gemma_3_12b_ItParams, "__pydantic_config__", _PARAMS_CONFIG)

Gemma_3_1b_ItParams = TypedDict(
    "Gemma_3_1b_ItParams",
    {
        "max_completion_tokens": Annotated[int, Field(ge=1, le=32768)],
        "temperature": float,
        "top_p": Annotated[float, Field(ge=0, le=1)],
        "top_k": Annotated[int, Field(ge=0)],
    },
    total=False,
)
setattr(Gemma_3_1b_ItParams, "__pydantic_config__", _PARAMS_CONFIG)

Gemma_3_27b_ItParams = TypedDict(
    "Gemma_3_27b_ItParams",
    {
        "max_completion_tokens": Annotated[int, Field(ge=1, le=131072)],
        "temperature": float,
        "top_p": Annotated[float, Field(ge=0, le=1)],
        "top_k": Annotated[int, Field(ge=0)],
    },
    total=False,
)
setattr(Gemma_3_27b_ItParams, "__pydantic_config__", _PARAMS_CONFIG)

Gemma_3_4b_ItParams = TypedDict(
    "Gemma_3_4b_ItParams",
    {
        "max_completion_tokens": Annotated[int, Field(ge=1, le=131072)],
        "temperature": float,
        "top_p": Annotated[float, Field(ge=0, le=1)],
        "top_k": Annotated[int, Field(ge=0)],
    },
    total=False,
)
setattr(Gemma_3_4b_ItParams, "__pydantic_config__", _PARAMS_CONFIG)

Gemma_3n_E2b_ItParams = TypedDict(
    "Gemma_3n_E2b_ItParams",
    {
        "max_completion_tokens": Annotated[int, Field(ge=1, le=32768)],
        "temperature": float,
        "top_p": Annotated[float, Field(ge=0, le=1)],
        "top_k": Annotated[int, Field(ge=0)],
    },
    total=False,
)
setattr(Gemma_3n_E2b_ItParams, "__pydantic_config__", _PARAMS_CONFIG)

Gemma_3n_E4b_ItParams = TypedDict(
    "Gemma_3n_E4b_ItParams",
    {
        "max_completion_tokens": Annotated[int, Field(ge=1, le=32768)],
        "temperature": float,
        "top_p": Annotated[float, Field(ge=0, le=1)],
        "top_k": Annotated[int, Field(ge=0)],
    },
    total=False,
)
setattr(Gemma_3n_E4b_ItParams, "__pydantic_config__", _PARAMS_CONFIG)

Gemma_4_12b_ItParams = TypedDict(
    "Gemma_4_12b_ItParams",
    {
        "max_completion_tokens": Annotated[int, Field(ge=1)],
        "temperature": float,
        "top_p": Annotated[float, Field(ge=0, le=1)],
        "top_k": Annotated[int, Field(ge=0)],
    },
    total=False,
)
setattr(Gemma_4_12b_ItParams, "__pydantic_config__", _PARAMS_CONFIG)

Gemma_4_26b_A4b_ItParams = TypedDict(
    "Gemma_4_26b_A4b_ItParams",
    {
        "generationConfig.maxOutputTokens": Annotated[int, Field(ge=1, le=65536)],
        "generationConfig.temperature": Annotated[float, Field(ge=0, le=2)],
        "generationConfig.topP": Annotated[float, Field(ge=0, le=1)],
        "generationConfig.topK": Annotated[int, Field(ge=0)],
        "generationConfig.seed": int,
        "generationConfig.thinkingConfig.thinkingBudget": int,
        "generationConfig.thinkingConfig.thinkingLevel": Literal["minimal", "high"],
        "generationConfig.thinkingConfig.includeThoughts": bool,
        "generationConfig.responseMimeType": Literal["text/plain", "application/json"],
    },
    total=False,
)
setattr(Gemma_4_26b_A4b_ItParams, "__pydantic_config__", _PARAMS_CONFIG)

Gemma_4_31b_ItParams = TypedDict(
    "Gemma_4_31b_ItParams",
    {
        "generationConfig.maxOutputTokens": Annotated[int, Field(ge=1, le=65536)],
        "generationConfig.temperature": Annotated[float, Field(ge=0, le=2)],
        "generationConfig.topP": Annotated[float, Field(ge=0, le=1)],
        "generationConfig.topK": Annotated[int, Field(ge=0)],
        "generationConfig.seed": int,
        "generationConfig.thinkingConfig.thinkingBudget": int,
        "generationConfig.thinkingConfig.thinkingLevel": Literal["minimal", "high"],
        "generationConfig.thinkingConfig.includeThoughts": bool,
        "generationConfig.responseMimeType": Literal["text/plain", "application/json"],
    },
    total=False,
)
setattr(Gemma_4_31b_ItParams, "__pydantic_config__", _PARAMS_CONFIG)

Gemma_4_E2b_ItParams = TypedDict(
    "Gemma_4_E2b_ItParams",
    {
        "max_completion_tokens": Annotated[int, Field(ge=1)],
        "temperature": float,
        "top_p": Annotated[float, Field(ge=0, le=1)],
        "top_k": Annotated[int, Field(ge=0)],
    },
    total=False,
)
setattr(Gemma_4_E2b_ItParams, "__pydantic_config__", _PARAMS_CONFIG)

Gemma_4_E4b_ItParams = TypedDict(
    "Gemma_4_E4b_ItParams",
    {
        "max_completion_tokens": Annotated[int, Field(ge=1)],
        "temperature": float,
        "top_p": Annotated[float, Field(ge=0, le=1)],
        "top_k": Annotated[int, Field(ge=0)],
    },
    total=False,
)
setattr(Gemma_4_E4b_ItParams, "__pydantic_config__", _PARAMS_CONFIG)

__all__ = [
    "Gemini_2_5_FlashParams",
    "Gemini_2_5_Flash_LiteParams",
    "Gemini_2_5_Flash_Lite_SubscriptionParams",
    "Gemini_2_5_Flash_SubscriptionParams",
    "Gemini_2_5_ProParams",
    "Gemini_2_5_Pro_SubscriptionParams",
    "Gemini_3_Flash_Preview_SubscriptionParams",
    "Gemini_3_Pro_ImageParams",
    "Gemini_3_1_Flash_ImageParams",
    "Gemini_3_1_Flash_LiteParams",
    "Gemini_3_1_Flash_Lite_Preview_SubscriptionParams",
    "Gemini_3_1_Flash_Lite_SubscriptionParams",
    "Gemini_3_1_Pro_Preview_SubscriptionParams",
    "Gemini_3_5_FlashParams",
    "Gemini_3_5_Flash_LiteParams",
    "Gemini_3_6_FlashParams",
    "Gemini_3_7_FlashParams",
    "Gemini_Flash_LatestParams",
    "Gemma_3_12b_ItParams",
    "Gemma_3_1b_ItParams",
    "Gemma_3_27b_ItParams",
    "Gemma_3_4b_ItParams",
    "Gemma_3n_E2b_ItParams",
    "Gemma_3n_E4b_ItParams",
    "Gemma_4_12b_ItParams",
    "Gemma_4_26b_A4b_ItParams",
    "Gemma_4_31b_ItParams",
    "Gemma_4_E2b_ItParams",
    "Gemma_4_E4b_ItParams",
]
