# AUTO-GENERATED by packages/modelparams-python/scripts/codegen.ts.
# Do not edit by hand; the YAML catalog under /models is the source of truth.

# ruff: noqa: F401

from typing import Annotated, Literal

from pydantic import ConfigDict, Field
from typing_extensions import TypedDict

_PARAMS_CONFIG = ConfigDict(strict=True, extra="forbid")

Llama_3_3_70b_InstructParams = TypedDict(
    "Llama_3_3_70b_InstructParams",
    {
        "max_completion_tokens": Annotated[int, Field(ge=1)],
        "temperature": float,
        "top_p": float,
        "top_k": int,
        "repetition_penalty": float,
        "response_format.type": Literal["text", "json_schema"],
        "tool_choice": Literal["auto", "none", "required"],
    },
    total=False,
)
setattr(Llama_3_3_70b_InstructParams, "__pydantic_config__", _PARAMS_CONFIG)

Llama_3_3_8b_InstructParams = TypedDict(
    "Llama_3_3_8b_InstructParams",
    {
        "max_completion_tokens": Annotated[int, Field(ge=1)],
        "temperature": float,
        "top_p": float,
        "top_k": int,
        "repetition_penalty": float,
        "response_format.type": Literal["text", "json_schema"],
        "tool_choice": Literal["auto", "none", "required"],
    },
    total=False,
)
setattr(Llama_3_3_8b_InstructParams, "__pydantic_config__", _PARAMS_CONFIG)

Llama_4_Maverick_17b_128e_Instruct_Fp8Params = TypedDict(
    "Llama_4_Maverick_17b_128e_Instruct_Fp8Params",
    {
        "max_completion_tokens": Annotated[int, Field(ge=1)],
        "temperature": float,
        "top_p": float,
        "top_k": int,
        "repetition_penalty": float,
        "response_format.type": Literal["text", "json_schema"],
        "tool_choice": Literal["auto", "none", "required"],
    },
    total=False,
)
setattr(Llama_4_Maverick_17b_128e_Instruct_Fp8Params, "__pydantic_config__", _PARAMS_CONFIG)

Llama_4_Scout_17b_16e_Instruct_Fp8Params = TypedDict(
    "Llama_4_Scout_17b_16e_Instruct_Fp8Params",
    {
        "max_completion_tokens": Annotated[int, Field(ge=1)],
        "temperature": float,
        "top_p": float,
        "top_k": int,
        "repetition_penalty": float,
        "response_format.type": Literal["text", "json_schema"],
        "tool_choice": Literal["auto", "none", "required"],
    },
    total=False,
)
setattr(Llama_4_Scout_17b_16e_Instruct_Fp8Params, "__pydantic_config__", _PARAMS_CONFIG)

__all__ = [
    "Llama_3_3_70b_InstructParams",
    "Llama_3_3_8b_InstructParams",
    "Llama_4_Maverick_17b_128e_Instruct_Fp8Params",
    "Llama_4_Scout_17b_16e_Instruct_Fp8Params",
]
