# AUTO-GENERATED by packages/modelparams-python/scripts/codegen.ts.
# Do not edit by hand; the YAML catalog under /models is the source of truth.

# ruff: noqa: F401

from typing import Annotated, Literal

from pydantic import ConfigDict, Field
from typing_extensions import TypedDict

_PARAMS_CONFIG = ConfigDict(strict=True, extra="forbid")

Minimax_M2Params = TypedDict(
    "Minimax_M2Params",
    {
        "max_completion_tokens": Annotated[int, Field(ge=1)],
        "temperature": Annotated[float, Field(ge=0.01, le=1)],
        "top_p": Annotated[float, Field(ge=0.01, le=1)],
        "reasoning_split": bool,
    },
    total=False,
)
setattr(Minimax_M2Params, "__pydantic_config__", _PARAMS_CONFIG)

Minimax_M2_SubscriptionParams = TypedDict(
    "Minimax_M2_SubscriptionParams",
    {
        "max_tokens": Annotated[int, Field(ge=1)],
        "temperature": Annotated[float, Field(ge=0.01, le=1)],
        "top_p": Annotated[float, Field(ge=0.01, le=1)],
    },
    total=False,
)
setattr(Minimax_M2_SubscriptionParams, "__pydantic_config__", _PARAMS_CONFIG)

Minimax_M2_1Params = TypedDict(
    "Minimax_M2_1Params",
    {
        "max_completion_tokens": Annotated[int, Field(ge=1)],
        "temperature": Annotated[float, Field(ge=0.01, le=1)],
        "top_p": Annotated[float, Field(ge=0.01, le=1)],
        "reasoning_split": bool,
    },
    total=False,
)
setattr(Minimax_M2_1Params, "__pydantic_config__", _PARAMS_CONFIG)

Minimax_M2_1_HighspeedParams = TypedDict(
    "Minimax_M2_1_HighspeedParams",
    {
        "max_completion_tokens": Annotated[int, Field(ge=1)],
        "temperature": Annotated[float, Field(ge=0.01, le=1)],
        "top_p": Annotated[float, Field(ge=0.01, le=1)],
        "reasoning_split": bool,
    },
    total=False,
)
setattr(Minimax_M2_1_HighspeedParams, "__pydantic_config__", _PARAMS_CONFIG)

Minimax_M2_1_Highspeed_SubscriptionParams = TypedDict(
    "Minimax_M2_1_Highspeed_SubscriptionParams",
    {
        "max_tokens": Annotated[int, Field(ge=1)],
        "temperature": Annotated[float, Field(ge=0.01, le=1)],
        "top_p": Annotated[float, Field(ge=0.01, le=1)],
    },
    total=False,
)
setattr(Minimax_M2_1_Highspeed_SubscriptionParams, "__pydantic_config__", _PARAMS_CONFIG)

Minimax_M2_1_SubscriptionParams = TypedDict(
    "Minimax_M2_1_SubscriptionParams",
    {
        "max_tokens": Annotated[int, Field(ge=1)],
        "temperature": Annotated[float, Field(ge=0.01, le=1)],
        "top_p": Annotated[float, Field(ge=0.01, le=1)],
    },
    total=False,
)
setattr(Minimax_M2_1_SubscriptionParams, "__pydantic_config__", _PARAMS_CONFIG)

Minimax_M2_5Params = TypedDict(
    "Minimax_M2_5Params",
    {
        "max_completion_tokens": Annotated[int, Field(ge=1)],
        "temperature": Annotated[float, Field(ge=0.01, le=1)],
        "top_p": Annotated[float, Field(ge=0.01, le=1)],
        "reasoning_split": bool,
    },
    total=False,
)
setattr(Minimax_M2_5Params, "__pydantic_config__", _PARAMS_CONFIG)

Minimax_M2_5_HighspeedParams = TypedDict(
    "Minimax_M2_5_HighspeedParams",
    {
        "max_completion_tokens": Annotated[int, Field(ge=1)],
        "temperature": Annotated[float, Field(ge=0.01, le=1)],
        "top_p": Annotated[float, Field(ge=0.01, le=1)],
        "reasoning_split": bool,
    },
    total=False,
)
setattr(Minimax_M2_5_HighspeedParams, "__pydantic_config__", _PARAMS_CONFIG)

Minimax_M2_5_Highspeed_SubscriptionParams = TypedDict(
    "Minimax_M2_5_Highspeed_SubscriptionParams",
    {
        "max_tokens": Annotated[int, Field(ge=1)],
        "temperature": Annotated[float, Field(ge=0.01, le=1)],
        "top_p": Annotated[float, Field(ge=0.01, le=1)],
    },
    total=False,
)
setattr(Minimax_M2_5_Highspeed_SubscriptionParams, "__pydantic_config__", _PARAMS_CONFIG)

Minimax_M2_5_SubscriptionParams = TypedDict(
    "Minimax_M2_5_SubscriptionParams",
    {
        "max_tokens": Annotated[int, Field(ge=1)],
        "temperature": Annotated[float, Field(ge=0.01, le=1)],
        "top_p": Annotated[float, Field(ge=0.01, le=1)],
    },
    total=False,
)
setattr(Minimax_M2_5_SubscriptionParams, "__pydantic_config__", _PARAMS_CONFIG)

Minimax_M2_7Params = TypedDict(
    "Minimax_M2_7Params",
    {
        "max_completion_tokens": Annotated[int, Field(ge=1)],
        "temperature": Annotated[float, Field(ge=0.01, le=1)],
        "top_p": Annotated[float, Field(ge=0.01, le=1)],
        "reasoning_split": bool,
    },
    total=False,
)
setattr(Minimax_M2_7Params, "__pydantic_config__", _PARAMS_CONFIG)

Minimax_M2_7_HighspeedParams = TypedDict(
    "Minimax_M2_7_HighspeedParams",
    {
        "max_completion_tokens": Annotated[int, Field(ge=1)],
        "temperature": Annotated[float, Field(ge=0.01, le=1)],
        "top_p": Annotated[float, Field(ge=0.01, le=1)],
        "reasoning_split": bool,
    },
    total=False,
)
setattr(Minimax_M2_7_HighspeedParams, "__pydantic_config__", _PARAMS_CONFIG)

Minimax_M2_7_Highspeed_SubscriptionParams = TypedDict(
    "Minimax_M2_7_Highspeed_SubscriptionParams",
    {
        "max_tokens": Annotated[int, Field(ge=1)],
        "temperature": Annotated[float, Field(ge=0.01, le=1)],
        "top_p": Annotated[float, Field(ge=0.01, le=1)],
    },
    total=False,
)
setattr(Minimax_M2_7_Highspeed_SubscriptionParams, "__pydantic_config__", _PARAMS_CONFIG)

Minimax_M2_7_SubscriptionParams = TypedDict(
    "Minimax_M2_7_SubscriptionParams",
    {
        "max_tokens": Annotated[int, Field(ge=1)],
        "temperature": Annotated[float, Field(ge=0.01, le=1)],
        "top_p": Annotated[float, Field(ge=0.01, le=1)],
    },
    total=False,
)
setattr(Minimax_M2_7_SubscriptionParams, "__pydantic_config__", _PARAMS_CONFIG)

Minimax_M3Params = TypedDict(
    "Minimax_M3Params",
    {
        "max_completion_tokens": Annotated[int, Field(ge=1)],
        "temperature": Annotated[float, Field(ge=0.01, le=1)],
        "top_p": Annotated[float, Field(ge=0.01, le=1)],
        "reasoning_split": bool,
    },
    total=False,
)
setattr(Minimax_M3Params, "__pydantic_config__", _PARAMS_CONFIG)

Minimax_M3_SubscriptionParams = TypedDict(
    "Minimax_M3_SubscriptionParams",
    {
        "max_tokens": Annotated[int, Field(ge=1)],
        "temperature": Annotated[float, Field(ge=0.01, le=1)],
        "top_p": Annotated[float, Field(ge=0.01, le=1)],
    },
    total=False,
)
setattr(Minimax_M3_SubscriptionParams, "__pydantic_config__", _PARAMS_CONFIG)

__all__ = [
    "Minimax_M2Params",
    "Minimax_M2_SubscriptionParams",
    "Minimax_M2_1Params",
    "Minimax_M2_1_HighspeedParams",
    "Minimax_M2_1_Highspeed_SubscriptionParams",
    "Minimax_M2_1_SubscriptionParams",
    "Minimax_M2_5Params",
    "Minimax_M2_5_HighspeedParams",
    "Minimax_M2_5_Highspeed_SubscriptionParams",
    "Minimax_M2_5_SubscriptionParams",
    "Minimax_M2_7Params",
    "Minimax_M2_7_HighspeedParams",
    "Minimax_M2_7_Highspeed_SubscriptionParams",
    "Minimax_M2_7_SubscriptionParams",
    "Minimax_M3Params",
    "Minimax_M3_SubscriptionParams",
]
