# AUTO-GENERATED by packages/modelparams-python/scripts/codegen.ts.
# Do not edit by hand; the YAML catalog under /models is the source of truth.

# ruff: noqa: F401

from typing import Annotated, Literal

from pydantic import ConfigDict, Field
from typing_extensions import TypedDict

_PARAMS_CONFIG = ConfigDict(strict=True, extra="forbid")

Codestral_LatestParams = TypedDict(
    "Codestral_LatestParams",
    {
        "max_tokens": Annotated[int, Field(ge=1)],
        "stop": str,
        "temperature": Annotated[float, Field(ge=0, le=1.5)],
        "top_p": Annotated[float, Field(ge=0, le=1)],
        "random_seed": Annotated[int, Field(ge=0)],
        "presence_penalty": Annotated[float, Field(ge=-2, le=2)],
        "frequency_penalty": Annotated[float, Field(ge=-2, le=2)],
        "response_format.type": Literal["text", "json_object"],
        "safe_prompt": bool,
    },
    total=False,
)
setattr(Codestral_LatestParams, "__pydantic_config__", _PARAMS_CONFIG)

Devstral_2512Params = TypedDict(
    "Devstral_2512Params",
    {
        "max_tokens": Annotated[int, Field(ge=1)],
        "stop": str,
        "temperature": Annotated[float, Field(ge=0, le=1.5)],
        "top_p": Annotated[float, Field(ge=0, le=1)],
        "random_seed": Annotated[int, Field(ge=0)],
        "presence_penalty": Annotated[float, Field(ge=-2, le=2)],
        "frequency_penalty": Annotated[float, Field(ge=-2, le=2)],
        "response_format.type": Literal["text", "json_object"],
        "safe_prompt": bool,
    },
    total=False,
)
setattr(Devstral_2512Params, "__pydantic_config__", _PARAMS_CONFIG)

Devstral_LatestParams = TypedDict(
    "Devstral_LatestParams",
    {
        "max_tokens": Annotated[int, Field(ge=1)],
        "stop": str,
        "temperature": Annotated[float, Field(ge=0, le=1.5)],
        "top_p": Annotated[float, Field(ge=0, le=1)],
        "random_seed": Annotated[int, Field(ge=0)],
        "presence_penalty": Annotated[float, Field(ge=-2, le=2)],
        "frequency_penalty": Annotated[float, Field(ge=-2, le=2)],
        "response_format.type": Literal["text", "json_object"],
        "safe_prompt": bool,
    },
    total=False,
)
setattr(Devstral_LatestParams, "__pydantic_config__", _PARAMS_CONFIG)

Magistral_Medium_LatestParams = TypedDict(
    "Magistral_Medium_LatestParams",
    {
        "max_tokens": Annotated[int, Field(ge=1)],
        "stop": str,
        "temperature": Annotated[float, Field(ge=0, le=1.5)],
        "top_p": Annotated[float, Field(ge=0, le=1)],
        "random_seed": Annotated[int, Field(ge=0)],
        "presence_penalty": Annotated[float, Field(ge=-2, le=2)],
        "frequency_penalty": Annotated[float, Field(ge=-2, le=2)],
        "prompt_mode": Literal["reasoning"],
        "response_format.type": Literal["text", "json_object"],
        "safe_prompt": bool,
    },
    total=False,
)
setattr(Magistral_Medium_LatestParams, "__pydantic_config__", _PARAMS_CONFIG)

Magistral_Small_LatestParams = TypedDict(
    "Magistral_Small_LatestParams",
    {
        "max_tokens": Annotated[int, Field(ge=1)],
        "stop": str,
        "temperature": Annotated[float, Field(ge=0, le=1.5)],
        "top_p": Annotated[float, Field(ge=0, le=1)],
        "random_seed": Annotated[int, Field(ge=0)],
        "presence_penalty": Annotated[float, Field(ge=-2, le=2)],
        "frequency_penalty": Annotated[float, Field(ge=-2, le=2)],
        "prompt_mode": Literal["reasoning"],
        "response_format.type": Literal["text", "json_object"],
        "safe_prompt": bool,
    },
    total=False,
)
setattr(Magistral_Small_LatestParams, "__pydantic_config__", _PARAMS_CONFIG)

Ministral_14b_LatestParams = TypedDict(
    "Ministral_14b_LatestParams",
    {
        "max_tokens": Annotated[int, Field(ge=1)],
        "stop": str,
        "temperature": Annotated[float, Field(ge=0, le=1.5)],
        "top_p": Annotated[float, Field(ge=0, le=1)],
        "random_seed": Annotated[int, Field(ge=0)],
        "presence_penalty": Annotated[float, Field(ge=-2, le=2)],
        "frequency_penalty": Annotated[float, Field(ge=-2, le=2)],
        "response_format.type": Literal["text", "json_object"],
        "safe_prompt": bool,
    },
    total=False,
)
setattr(Ministral_14b_LatestParams, "__pydantic_config__", _PARAMS_CONFIG)

Ministral_3b_LatestParams = TypedDict(
    "Ministral_3b_LatestParams",
    {
        "max_tokens": Annotated[int, Field(ge=1)],
        "stop": str,
        "temperature": Annotated[float, Field(ge=0, le=1.5)],
        "top_p": Annotated[float, Field(ge=0, le=1)],
        "random_seed": Annotated[int, Field(ge=0)],
        "presence_penalty": Annotated[float, Field(ge=-2, le=2)],
        "frequency_penalty": Annotated[float, Field(ge=-2, le=2)],
        "response_format.type": Literal["text", "json_object"],
        "safe_prompt": bool,
    },
    total=False,
)
setattr(Ministral_3b_LatestParams, "__pydantic_config__", _PARAMS_CONFIG)

Ministral_8b_LatestParams = TypedDict(
    "Ministral_8b_LatestParams",
    {
        "max_tokens": Annotated[int, Field(ge=1)],
        "stop": str,
        "temperature": Annotated[float, Field(ge=0, le=1.5)],
        "top_p": Annotated[float, Field(ge=0, le=1)],
        "random_seed": Annotated[int, Field(ge=0)],
        "presence_penalty": Annotated[float, Field(ge=-2, le=2)],
        "frequency_penalty": Annotated[float, Field(ge=-2, le=2)],
        "response_format.type": Literal["text", "json_object"],
        "safe_prompt": bool,
    },
    total=False,
)
setattr(Ministral_8b_LatestParams, "__pydantic_config__", _PARAMS_CONFIG)

Mistral_Large_LatestParams = TypedDict(
    "Mistral_Large_LatestParams",
    {
        "max_tokens": Annotated[int, Field(ge=1)],
        "stop": str,
        "temperature": Annotated[float, Field(ge=0, le=1.5)],
        "top_p": Annotated[float, Field(ge=0, le=1)],
        "random_seed": Annotated[int, Field(ge=0)],
        "presence_penalty": Annotated[float, Field(ge=-2, le=2)],
        "frequency_penalty": Annotated[float, Field(ge=-2, le=2)],
        "response_format.type": Literal["text", "json_object"],
        "safe_prompt": bool,
    },
    total=False,
)
setattr(Mistral_Large_LatestParams, "__pydantic_config__", _PARAMS_CONFIG)

Mistral_Medium_3_5Params = TypedDict(
    "Mistral_Medium_3_5Params",
    {
        "max_tokens": Annotated[int, Field(ge=1)],
        "stop": str,
        "temperature": Annotated[float, Field(ge=0, le=1.5)],
        "top_p": Annotated[float, Field(ge=0, le=1)],
        "random_seed": Annotated[int, Field(ge=0)],
        "presence_penalty": Annotated[float, Field(ge=-2, le=2)],
        "frequency_penalty": Annotated[float, Field(ge=-2, le=2)],
        "response_format.type": Literal["text", "json_object"],
        "safe_prompt": bool,
    },
    total=False,
)
setattr(Mistral_Medium_3_5Params, "__pydantic_config__", _PARAMS_CONFIG)

Mistral_Medium_LatestParams = TypedDict(
    "Mistral_Medium_LatestParams",
    {
        "max_tokens": Annotated[int, Field(ge=1)],
        "stop": str,
        "temperature": Annotated[float, Field(ge=0, le=1.5)],
        "top_p": Annotated[float, Field(ge=0, le=1)],
        "random_seed": Annotated[int, Field(ge=0)],
        "presence_penalty": Annotated[float, Field(ge=-2, le=2)],
        "frequency_penalty": Annotated[float, Field(ge=-2, le=2)],
        "response_format.type": Literal["text", "json_object"],
        "safe_prompt": bool,
    },
    total=False,
)
setattr(Mistral_Medium_LatestParams, "__pydantic_config__", _PARAMS_CONFIG)

Mistral_Small_LatestParams = TypedDict(
    "Mistral_Small_LatestParams",
    {
        "max_tokens": Annotated[int, Field(ge=1)],
        "stop": str,
        "temperature": Annotated[float, Field(ge=0, le=1.5)],
        "top_p": Annotated[float, Field(ge=0, le=1)],
        "random_seed": Annotated[int, Field(ge=0)],
        "presence_penalty": Annotated[float, Field(ge=-2, le=2)],
        "frequency_penalty": Annotated[float, Field(ge=-2, le=2)],
        "response_format.type": Literal["text", "json_object"],
        "safe_prompt": bool,
    },
    total=False,
)
setattr(Mistral_Small_LatestParams, "__pydantic_config__", _PARAMS_CONFIG)

Open_Mistral_NemoParams = TypedDict(
    "Open_Mistral_NemoParams",
    {
        "max_tokens": Annotated[int, Field(ge=1)],
        "stop": str,
        "temperature": Annotated[float, Field(ge=0, le=1.5)],
        "top_p": Annotated[float, Field(ge=0, le=1)],
        "random_seed": Annotated[int, Field(ge=0)],
        "presence_penalty": Annotated[float, Field(ge=-2, le=2)],
        "frequency_penalty": Annotated[float, Field(ge=-2, le=2)],
        "response_format.type": Literal["text", "json_object"],
        "safe_prompt": bool,
    },
    total=False,
)
setattr(Open_Mistral_NemoParams, "__pydantic_config__", _PARAMS_CONFIG)

__all__ = [
    "Codestral_LatestParams",
    "Devstral_2512Params",
    "Devstral_LatestParams",
    "Magistral_Medium_LatestParams",
    "Magistral_Small_LatestParams",
    "Ministral_14b_LatestParams",
    "Ministral_3b_LatestParams",
    "Ministral_8b_LatestParams",
    "Mistral_Large_LatestParams",
    "Mistral_Medium_3_5Params",
    "Mistral_Medium_LatestParams",
    "Mistral_Small_LatestParams",
    "Open_Mistral_NemoParams",
]
