# AUTO-GENERATED by packages/modelparams-python/scripts/codegen.ts.
# Do not edit by hand; the YAML catalog under /models is the source of truth.

# ruff: noqa: F401

from typing import Annotated, Literal

from pydantic import ConfigDict, Field
from typing_extensions import TypedDict

_PARAMS_CONFIG = ConfigDict(strict=True, extra="forbid")

Kimi_K2_5Params = TypedDict(
    "Kimi_K2_5Params",
    {
        "max_completion_tokens": Annotated[int, Field(ge=1)],
        "stop": str,
        "thinking.type": Literal["enabled", "disabled"],
        "response_format.type": Literal["text", "json_object"],
        "tool_choice": Literal["auto", "none"],
        "logprobs": bool,
        "top_logprobs": Annotated[int, Field(ge=0, le=20)],
    },
    total=False,
)
setattr(Kimi_K2_5Params, "__pydantic_config__", _PARAMS_CONFIG)

Kimi_K2_6Params = TypedDict(
    "Kimi_K2_6Params",
    {
        "max_completion_tokens": Annotated[int, Field(ge=1)],
        "stop": str,
        "thinking.type": Literal["enabled", "disabled"],
        "thinking.keep": Literal["all", None],
        "response_format.type": Literal["text", "json_object"],
        "tool_choice": Literal["auto", "none"],
        "logprobs": bool,
        "top_logprobs": Annotated[int, Field(ge=0, le=20)],
    },
    total=False,
)
setattr(Kimi_K2_6Params, "__pydantic_config__", _PARAMS_CONFIG)

Kimi_K2_6_SubscriptionParams = TypedDict(
    "Kimi_K2_6_SubscriptionParams",
    {
        "max_completion_tokens": Annotated[int, Field(ge=1)],
        "thinking.type": Literal["enabled", "disabled"],
        "thinking.keep": Literal["all", None],
        "response_format.type": Literal["text", "json_object"],
    },
    total=False,
)
setattr(Kimi_K2_6_SubscriptionParams, "__pydantic_config__", _PARAMS_CONFIG)

Kimi_K2_7_CodeParams = TypedDict(
    "Kimi_K2_7_CodeParams",
    {
        "max_completion_tokens": Annotated[int, Field(ge=1)],
        "stop": str,
        "thinking.type": Literal["enabled"],
        "response_format.type": Literal["text", "json_object", "json_schema"],
        "tool_choice": Literal["auto", "none"],
        "logprobs": bool,
        "top_logprobs": Annotated[int, Field(ge=0, le=20)],
    },
    total=False,
)
setattr(Kimi_K2_7_CodeParams, "__pydantic_config__", _PARAMS_CONFIG)

Kimi_K2_7_Code_HighspeedParams = TypedDict(
    "Kimi_K2_7_Code_HighspeedParams",
    {
        "max_completion_tokens": Annotated[int, Field(ge=1)],
        "stop": str,
        "thinking.type": Literal["enabled"],
        "response_format.type": Literal["text", "json_object", "json_schema"],
        "tool_choice": Literal["auto", "none"],
        "logprobs": bool,
        "top_logprobs": Annotated[int, Field(ge=0, le=20)],
    },
    total=False,
)
setattr(Kimi_K2_7_Code_HighspeedParams, "__pydantic_config__", _PARAMS_CONFIG)

Kimi_K2_7_Code_Highspeed_SubscriptionParams = TypedDict(
    "Kimi_K2_7_Code_Highspeed_SubscriptionParams",
    {
        "max_completion_tokens": Annotated[int, Field(ge=1)],
        "thinking.type": Literal["enabled"],
        "response_format.type": Literal["text", "json_object"],
    },
    total=False,
)
setattr(Kimi_K2_7_Code_Highspeed_SubscriptionParams, "__pydantic_config__", _PARAMS_CONFIG)

Kimi_K2_7_Code_SubscriptionParams = TypedDict(
    "Kimi_K2_7_Code_SubscriptionParams",
    {
        "max_completion_tokens": Annotated[int, Field(ge=1)],
        "thinking.type": Literal["enabled"],
        "response_format.type": Literal["text", "json_object"],
    },
    total=False,
)
setattr(Kimi_K2_7_Code_SubscriptionParams, "__pydantic_config__", _PARAMS_CONFIG)

Kimi_K3Params = TypedDict(
    "Kimi_K3Params",
    {
        "max_completion_tokens": Annotated[int, Field(ge=1)],
        "stop": str,
        "thinking.type": Literal["enabled", "disabled"],
        "reasoning_effort": Literal["low", "high", "max"],
        "response_format.type": Literal["text", "json_object", "json_schema"],
        "tool_choice": Literal["auto", "none", "required"],
    },
    total=False,
)
setattr(Kimi_K3Params, "__pydantic_config__", _PARAMS_CONFIG)

Moonshot_V1_128kParams = TypedDict(
    "Moonshot_V1_128kParams",
    {
        "max_completion_tokens": Annotated[int, Field(ge=1)],
        "stop": str,
        "temperature": Annotated[float, Field(ge=0, le=1)],
        "top_p": Annotated[float, Field(ge=0, le=1)],
        "n": Annotated[int, Field(ge=1, le=5)],
        "presence_penalty": Annotated[float, Field(ge=-2, le=2)],
        "frequency_penalty": Annotated[float, Field(ge=-2, le=2)],
        "response_format.type": Literal["text", "json_object"],
        "tool_choice": Literal["auto", "none", "required"],
        "logprobs": bool,
        "top_logprobs": Annotated[int, Field(ge=0, le=20)],
    },
    total=False,
)
setattr(Moonshot_V1_128kParams, "__pydantic_config__", _PARAMS_CONFIG)

Moonshot_V1_32kParams = TypedDict(
    "Moonshot_V1_32kParams",
    {
        "max_completion_tokens": Annotated[int, Field(ge=1)],
        "stop": str,
        "temperature": Annotated[float, Field(ge=0, le=1)],
        "top_p": Annotated[float, Field(ge=0, le=1)],
        "n": Annotated[int, Field(ge=1, le=5)],
        "presence_penalty": Annotated[float, Field(ge=-2, le=2)],
        "frequency_penalty": Annotated[float, Field(ge=-2, le=2)],
        "response_format.type": Literal["text", "json_object"],
        "tool_choice": Literal["auto", "none", "required"],
        "logprobs": bool,
        "top_logprobs": Annotated[int, Field(ge=0, le=20)],
    },
    total=False,
)
setattr(Moonshot_V1_32kParams, "__pydantic_config__", _PARAMS_CONFIG)

Moonshot_V1_8kParams = TypedDict(
    "Moonshot_V1_8kParams",
    {
        "max_completion_tokens": Annotated[int, Field(ge=1)],
        "stop": str,
        "temperature": Annotated[float, Field(ge=0, le=1)],
        "top_p": Annotated[float, Field(ge=0, le=1)],
        "n": Annotated[int, Field(ge=1, le=5)],
        "presence_penalty": Annotated[float, Field(ge=-2, le=2)],
        "frequency_penalty": Annotated[float, Field(ge=-2, le=2)],
        "response_format.type": Literal["text", "json_object"],
        "tool_choice": Literal["auto", "none", "required"],
        "logprobs": bool,
        "top_logprobs": Annotated[int, Field(ge=0, le=20)],
    },
    total=False,
)
setattr(Moonshot_V1_8kParams, "__pydantic_config__", _PARAMS_CONFIG)

__all__ = [
    "Kimi_K2_5Params",
    "Kimi_K2_6Params",
    "Kimi_K2_6_SubscriptionParams",
    "Kimi_K2_7_CodeParams",
    "Kimi_K2_7_Code_HighspeedParams",
    "Kimi_K2_7_Code_Highspeed_SubscriptionParams",
    "Kimi_K2_7_Code_SubscriptionParams",
    "Kimi_K3Params",
    "Moonshot_V1_128kParams",
    "Moonshot_V1_32kParams",
    "Moonshot_V1_8kParams",
]
