# AUTO-GENERATED by packages/modelparams-python/scripts/codegen.ts.
# Do not edit by hand; the YAML catalog under /models is the source of truth.

# ruff: noqa: F401

from typing import Annotated, Literal

from pydantic import ConfigDict, Field
from typing_extensions import TypedDict

_PARAMS_CONFIG = ConfigDict(strict=True, extra="forbid")

Deepseek_V4_Flash_0731Params = TypedDict(
    "Deepseek_V4_Flash_0731Params",
    {
        "temperature": Annotated[float, Field(ge=0, le=1)],
        "top_p": Annotated[float, Field(le=1)],
        "max_tokens": Annotated[int, Field(ge=1, le=16384)],
        "frequency_penalty": Annotated[float, Field(ge=-2, le=2)],
        "presence_penalty": Annotated[float, Field(ge=-2, le=2)],
        "seed": Annotated[int, Field(ge=0, le=18446744073709552000)],
        "stop": str,
    },
    total=False,
)
setattr(Deepseek_V4_Flash_0731Params, "__pydantic_config__", _PARAMS_CONFIG)

Deepseek_V4_Pro_0813Params = TypedDict(
    "Deepseek_V4_Pro_0813Params",
    {
        "temperature": Annotated[float, Field(ge=0, le=1)],
        "top_p": Annotated[float, Field(le=1)],
        "max_tokens": Annotated[int, Field(ge=1, le=16384)],
        "frequency_penalty": Annotated[float, Field(ge=-2, le=2)],
        "presence_penalty": Annotated[float, Field(ge=-2, le=2)],
        "seed": Annotated[int, Field(ge=0, le=18446744073709552000)],
        "stop": str,
    },
    total=False,
)
setattr(Deepseek_V4_Pro_0813Params, "__pydantic_config__", _PARAMS_CONFIG)

Gemma_4_31b_ItParams = TypedDict(
    "Gemma_4_31b_ItParams",
    {
        "temperature": Annotated[float, Field(ge=0, le=1)],
        "top_p": Annotated[float, Field(le=1)],
        "max_tokens": Annotated[int, Field(ge=1, le=16384)],
        "frequency_penalty": Annotated[float, Field(ge=-2, le=2)],
        "presence_penalty": Annotated[float, Field(ge=-2, le=2)],
        "seed": Annotated[int, Field(ge=0, le=18446744073709552000)],
        "stop": str,
    },
    total=False,
)
setattr(Gemma_4_31b_ItParams, "__pydantic_config__", _PARAMS_CONFIG)

Gliner_PiiParams = TypedDict(
    "Gliner_PiiParams",
    {
        "threshold": Annotated[float, Field(ge=0, le=1)],
        "chunk_length": Annotated[int, Field(ge=1, le=2048)],
        "overlap": Annotated[int, Field(ge=0, le=512)],
        "flat_ner": bool,
    },
    total=False,
)
setattr(Gliner_PiiParams, "__pydantic_config__", _PARAMS_CONFIG)

Llama_3_1_Nemoguard_8b_Topic_ControlParams = TypedDict(
    "Llama_3_1_Nemoguard_8b_Topic_ControlParams",
    {
        "temperature": Annotated[float, Field(ge=0, le=2)],
        "top_p": Annotated[float, Field(le=1)],
        "max_tokens": Annotated[int, Field(ge=1)],
        "frequency_penalty": Annotated[float, Field(ge=-2, le=2)],
        "presence_penalty": Annotated[float, Field(ge=-2, le=2)],
        "stop": str,
    },
    total=False,
)
setattr(Llama_3_1_Nemoguard_8b_Topic_ControlParams, "__pydantic_config__", _PARAMS_CONFIG)

Llama_3_1_Nemotron_Nano_8b_V1Params = TypedDict(
    "Llama_3_1_Nemotron_Nano_8b_V1Params",
    {
        "temperature": Annotated[float, Field(ge=0, le=1)],
        "top_p": Annotated[float, Field(le=1)],
        "max_tokens": Annotated[int, Field(ge=1, le=16384)],
        "frequency_penalty": Annotated[float, Field(ge=-2, le=2)],
        "presence_penalty": Annotated[float, Field(ge=-2, le=2)],
        "seed": Annotated[int, Field(ge=0, le=18446744073709552000)],
        "stop": str,
    },
    total=False,
)
setattr(Llama_3_1_Nemotron_Nano_8b_V1Params, "__pydantic_config__", _PARAMS_CONFIG)

Llama_3_1_Nemotron_Safety_Guard_8b_V3Params = TypedDict(
    "Llama_3_1_Nemotron_Safety_Guard_8b_V3Params",
    {
        "temperature": Annotated[float, Field(ge=0, le=1)],
    },
    total=False,
)
setattr(Llama_3_1_Nemotron_Safety_Guard_8b_V3Params, "__pydantic_config__", _PARAMS_CONFIG)

Llama_3_1_Nemotron_Ultra_253b_V1Params = TypedDict(
    "Llama_3_1_Nemotron_Ultra_253b_V1Params",
    {
        "temperature": Annotated[float, Field(ge=0, le=1)],
        "top_p": Annotated[float, Field(le=1)],
        "max_tokens": Annotated[int, Field(ge=1, le=16384)],
        "frequency_penalty": Annotated[float, Field(ge=-2, le=2)],
        "presence_penalty": Annotated[float, Field(ge=-2, le=2)],
        "seed": Annotated[int, Field(ge=0, le=18446744073709552000)],
        "stop": str,
    },
    total=False,
)
setattr(Llama_3_1_Nemotron_Ultra_253b_V1Params, "__pydantic_config__", _PARAMS_CONFIG)

Llama_3_3_Nemotron_Super_49b_V1Params = TypedDict(
    "Llama_3_3_Nemotron_Super_49b_V1Params",
    {
        "temperature": Annotated[float, Field(ge=0, le=1)],
        "top_p": Annotated[float, Field(le=1)],
        "max_tokens": Annotated[int, Field(ge=1, le=16384)],
        "frequency_penalty": Annotated[float, Field(ge=-2, le=2)],
        "presence_penalty": Annotated[float, Field(ge=-2, le=2)],
        "seed": Annotated[int, Field(ge=0, le=18446744073709552000)],
        "stop": str,
    },
    total=False,
)
setattr(Llama_3_3_Nemotron_Super_49b_V1Params, "__pydantic_config__", _PARAMS_CONFIG)

Llama_3_3_Nemotron_Super_49b_V1_5Params = TypedDict(
    "Llama_3_3_Nemotron_Super_49b_V1_5Params",
    {
        "temperature": Annotated[float, Field(ge=0, le=1)],
        "top_p": Annotated[float, Field(le=1)],
        "max_tokens": Annotated[int, Field(ge=1, le=65536)],
        "frequency_penalty": Annotated[float, Field(ge=-2, le=2)],
        "presence_penalty": Annotated[float, Field(ge=-2, le=2)],
        "seed": Annotated[int, Field(ge=0, le=18446744073709552000)],
        "stop": str,
    },
    total=False,
)
setattr(Llama_3_3_Nemotron_Super_49b_V1_5Params, "__pydantic_config__", _PARAMS_CONFIG)

Nemoguard_Jailbreak_DetectParams = TypedDict(
    "Nemoguard_Jailbreak_DetectParams",
    {

    },
    total=False,
)
setattr(Nemoguard_Jailbreak_DetectParams, "__pydantic_config__", _PARAMS_CONFIG)

Nemotron_3_Nano_30b_A3bParams = TypedDict(
    "Nemotron_3_Nano_30b_A3bParams",
    {
        "temperature": Annotated[float, Field(le=1)],
        "top_p": Annotated[float, Field(le=1)],
        "max_tokens": Annotated[int, Field(ge=1, le=32768)],
        "seed": Annotated[int, Field(ge=0, le=18446744073709552000)],
        "stop": str,
    },
    total=False,
)
setattr(Nemotron_3_Nano_30b_A3bParams, "__pydantic_config__", _PARAMS_CONFIG)

Nemotron_3_Super_120b_A12bParams = TypedDict(
    "Nemotron_3_Super_120b_A12bParams",
    {
        "temperature": Annotated[float, Field(le=1)],
        "top_p": Annotated[float, Field(le=1)],
        "max_tokens": Annotated[int, Field(ge=1, le=32768)],
        "reasoning_effort": Literal["none", "low", "high"],
        "reasoning_budget": Annotated[int, Field(ge=-1, le=32768)],
        "seed": Annotated[int, Field(ge=0, le=18446744073709552000)],
        "stop": str,
    },
    total=False,
)
setattr(Nemotron_3_Super_120b_A12bParams, "__pydantic_config__", _PARAMS_CONFIG)

Nemotron_3_Ultra_550b_A55bParams = TypedDict(
    "Nemotron_3_Ultra_550b_A55bParams",
    {
        "temperature": Annotated[float, Field(le=1)],
        "top_p": Annotated[float, Field(le=1)],
        "max_tokens": Annotated[int, Field(ge=1, le=32768)],
        "reasoning_effort": Literal["none", "medium", "high"],
        "reasoning_budget": Annotated[int, Field(ge=-1, le=32768)],
        "seed": Annotated[int, Field(ge=0, le=18446744073709552000)],
        "stop": str,
    },
    total=False,
)
setattr(Nemotron_3_Ultra_550b_A55bParams, "__pydantic_config__", _PARAMS_CONFIG)

Nemotron_3_Ultra_SubscriptionParams = TypedDict(
    "Nemotron_3_Ultra_SubscriptionParams",
    {
        "temperature": Annotated[float, Field(le=1)],
        "top_p": Annotated[float, Field(le=1)],
        "max_tokens": Annotated[int, Field(ge=1, le=32768)],
        "reasoning_effort": Literal["none", "medium", "high"],
        "reasoning_budget": Annotated[int, Field(ge=-1, le=32768)],
        "stop": str,
    },
    total=False,
)
setattr(Nemotron_3_Ultra_SubscriptionParams, "__pydantic_config__", _PARAMS_CONFIG)

Nemotron_Content_Safety_Reasoning_4bParams = TypedDict(
    "Nemotron_Content_Safety_Reasoning_4bParams",
    {
        "temperature": Annotated[float, Field(le=1)],
        "top_p": Annotated[float, Field(le=1)],
        "max_tokens": Annotated[int, Field(ge=1, le=32768)],
        "seed": Annotated[int, Field(ge=0, le=18446744073709552000)],
        "stop": str,
    },
    total=False,
)
setattr(Nemotron_Content_Safety_Reasoning_4bParams, "__pydantic_config__", _PARAMS_CONFIG)

Nemotron_Mini_4b_InstructParams = TypedDict(
    "Nemotron_Mini_4b_InstructParams",
    {
        "temperature": Annotated[float, Field(ge=0, le=1)],
        "top_p": Annotated[float, Field(le=1)],
        "max_tokens": Annotated[int, Field(ge=1, le=4096)],
        "frequency_penalty": Annotated[float, Field(ge=-2, le=2)],
        "presence_penalty": Annotated[float, Field(ge=-2, le=2)],
        "stop": str,
    },
    total=False,
)
setattr(Nemotron_Mini_4b_InstructParams, "__pydantic_config__", _PARAMS_CONFIG)

Riva_Translate_4b_Instruct_V1_1Params = TypedDict(
    "Riva_Translate_4b_Instruct_V1_1Params",
    {
        "temperature": Annotated[float, Field(ge=0, le=1)],
        "top_p": Annotated[float, Field(le=1)],
        "max_tokens": Annotated[int, Field(ge=1, le=4096)],
        "frequency_penalty": Annotated[float, Field(ge=-2, le=2)],
        "presence_penalty": Annotated[float, Field(ge=-2, le=2)],
        "stop": str,
    },
    total=False,
)
setattr(Riva_Translate_4b_Instruct_V1_1Params, "__pydantic_config__", _PARAMS_CONFIG)

Usdcode_Llama_3_1_70b_InstructParams = TypedDict(
    "Usdcode_Llama_3_1_70b_InstructParams",
    {
        "temperature": Annotated[float, Field(ge=0, le=1)],
        "top_p": Annotated[float, Field(le=1)],
        "max_tokens": Annotated[int, Field(ge=1, le=2048)],
        "expert_type": Literal["auto", "code", "knowledge", "helperfunction"],
    },
    total=False,
)
setattr(Usdcode_Llama_3_1_70b_InstructParams, "__pydantic_config__", _PARAMS_CONFIG)

__all__ = [
    "Deepseek_V4_Flash_0731Params",
    "Deepseek_V4_Pro_0813Params",
    "Gemma_4_31b_ItParams",
    "Gliner_PiiParams",
    "Llama_3_1_Nemoguard_8b_Topic_ControlParams",
    "Llama_3_1_Nemotron_Nano_8b_V1Params",
    "Llama_3_1_Nemotron_Safety_Guard_8b_V3Params",
    "Llama_3_1_Nemotron_Ultra_253b_V1Params",
    "Llama_3_3_Nemotron_Super_49b_V1Params",
    "Llama_3_3_Nemotron_Super_49b_V1_5Params",
    "Nemoguard_Jailbreak_DetectParams",
    "Nemotron_3_Nano_30b_A3bParams",
    "Nemotron_3_Super_120b_A12bParams",
    "Nemotron_3_Ultra_550b_A55bParams",
    "Nemotron_3_Ultra_SubscriptionParams",
    "Nemotron_Content_Safety_Reasoning_4bParams",
    "Nemotron_Mini_4b_InstructParams",
    "Riva_Translate_4b_Instruct_V1_1Params",
    "Usdcode_Llama_3_1_70b_InstructParams",
]
