# AUTO-GENERATED by packages/modelparams-python/scripts/codegen.ts.
# Do not edit by hand; the YAML catalog under /models is the source of truth.

# ruff: noqa: F401

from typing import Annotated, Literal

from pydantic import ConfigDict, Field
from typing_extensions import TypedDict

_PARAMS_CONFIG = ConfigDict(strict=True, extra="forbid")

Deepseek_V4_Flash_Vision_Exp_SubscriptionParams = TypedDict(
    "Deepseek_V4_Flash_Vision_Exp_SubscriptionParams",
    {
        "max_tokens": Annotated[int, Field(ge=1)],
        "temperature": Annotated[float, Field(ge=0, le=1.9)],
        "top_p": Annotated[float, Field(ge=0.01, le=1)],
        "top_k": Annotated[int, Field(ge=1)],
        "presence_penalty": Annotated[float, Field(ge=-2, le=2)],
        "frequency_penalty": Annotated[float, Field(ge=-2, le=2)],
        "response_format.type": Literal["text", "json_object"],
    },
    total=False,
)
setattr(Deepseek_V4_Flash_Vision_Exp_SubscriptionParams, "__pydantic_config__", _PARAMS_CONFIG)

Glm_5_3_Flash_SubscriptionParams = TypedDict(
    "Glm_5_3_Flash_SubscriptionParams",
    {
        "max_tokens": Annotated[int, Field(ge=1)],
        "temperature": Annotated[float, Field(ge=0, le=1.9)],
        "top_p": Annotated[float, Field(ge=0, le=1)],
        "top_k": Annotated[int, Field(ge=1)],
        "presence_penalty": Annotated[float, Field(ge=-2, le=2)],
        "frequency_penalty": Annotated[float, Field(ge=-2, le=2)],
        "response_format.type": Literal["text", "json_object"],
    },
    total=False,
)
setattr(Glm_5_3_Flash_SubscriptionParams, "__pydantic_config__", _PARAMS_CONFIG)

Glm_5_3_SubscriptionParams = TypedDict(
    "Glm_5_3_SubscriptionParams",
    {
        "max_tokens": Annotated[int, Field(ge=1)],
        "temperature": Annotated[float, Field(ge=0, le=1.9)],
        "top_p": Annotated[float, Field(ge=0.01, le=1)],
        "top_k": Annotated[int, Field(ge=1)],
        "presence_penalty": Annotated[float, Field(ge=-2, le=2)],
        "frequency_penalty": Annotated[float, Field(ge=-2, le=2)],
        "response_format.type": Literal["text", "json_object"],
    },
    total=False,
)
setattr(Glm_5_3_SubscriptionParams, "__pydantic_config__", _PARAMS_CONFIG)

Grok_4_6_SubscriptionParams = TypedDict(
    "Grok_4_6_SubscriptionParams",
    {
        "max_output_tokens": Annotated[int, Field(ge=16)],
        "temperature": Annotated[float, Field(ge=0, le=2)],
        "top_p": Annotated[float, Field(ge=0.01, le=1)],
    },
    total=False,
)
setattr(Grok_4_6_SubscriptionParams, "__pydantic_config__", _PARAMS_CONFIG)

Hy4_Preview_SubscriptionParams = TypedDict(
    "Hy4_Preview_SubscriptionParams",
    {
        "max_tokens": Annotated[int, Field(ge=1)],
        "temperature": Annotated[float, Field(ge=0, le=1.9)],
        "top_p": Annotated[float, Field(ge=0, le=1)],
        "top_k": Annotated[int, Field(ge=1)],
        "presence_penalty": Annotated[float, Field(ge=-2, le=2)],
        "frequency_penalty": Annotated[float, Field(ge=-2, le=2)],
        "response_format.type": Literal["text", "json_object"],
    },
    total=False,
)
setattr(Hy4_Preview_SubscriptionParams, "__pydantic_config__", _PARAMS_CONFIG)

Longcat_2_0_SubscriptionParams = TypedDict(
    "Longcat_2_0_SubscriptionParams",
    {
        "max_tokens": Annotated[int, Field(ge=1)],
        "temperature": Annotated[float, Field(ge=0, le=1)],
        "top_p": Annotated[float, Field(ge=0.01, le=1)],
        "top_k": Annotated[int, Field(ge=1)],
        "presence_penalty": Annotated[float, Field(ge=-2, le=2)],
        "frequency_penalty": Annotated[float, Field(ge=-2, le=2)],
        "response_format.type": Literal["text", "json_object"],
    },
    total=False,
)
setattr(Longcat_2_0_SubscriptionParams, "__pydantic_config__", _PARAMS_CONFIG)

Qwen3_8_Flash_SubscriptionParams = TypedDict(
    "Qwen3_8_Flash_SubscriptionParams",
    {
        "max_tokens": Annotated[int, Field(ge=1)],
        "temperature": Annotated[float, Field(ge=0, le=1.9)],
        "top_p": Annotated[float, Field(ge=0, le=1)],
        "top_k": Annotated[int, Field(ge=1)],
        "presence_penalty": Annotated[float, Field(ge=-2, le=2)],
        "frequency_penalty": Annotated[float, Field(ge=-2, le=2)],
        "response_format.type": Literal["text", "json_object"],
    },
    total=False,
)
setattr(Qwen3_8_Flash_SubscriptionParams, "__pydantic_config__", _PARAMS_CONFIG)

Qwen3_8_Max_SubscriptionParams = TypedDict(
    "Qwen3_8_Max_SubscriptionParams",
    {
        "max_tokens": Annotated[int, Field(ge=1)],
        "temperature": Annotated[float, Field(ge=0, le=1.9)],
        "top_p": Annotated[float, Field(ge=0, le=1)],
        "top_k": Annotated[int, Field(ge=1)],
        "presence_penalty": Annotated[float, Field(ge=-2, le=2)],
        "frequency_penalty": Annotated[float, Field(ge=-2, le=2)],
        "response_format.type": Literal["text", "json_object"],
    },
    total=False,
)
setattr(Qwen3_8_Max_SubscriptionParams, "__pydantic_config__", _PARAMS_CONFIG)

__all__ = [
    "Deepseek_V4_Flash_Vision_Exp_SubscriptionParams",
    "Glm_5_3_Flash_SubscriptionParams",
    "Glm_5_3_SubscriptionParams",
    "Grok_4_6_SubscriptionParams",
    "Hy4_Preview_SubscriptionParams",
    "Longcat_2_0_SubscriptionParams",
    "Qwen3_8_Flash_SubscriptionParams",
    "Qwen3_8_Max_SubscriptionParams",
]
