# AUTO-GENERATED by packages/modelparams-python/scripts/codegen.ts.
# Do not edit by hand; the YAML catalog under /models is the source of truth.

# ruff: noqa: F401

from typing import Annotated, Literal

from pydantic import ConfigDict, Field
from typing_extensions import TypedDict

_PARAMS_CONFIG = ConfigDict(strict=True, extra="forbid")

Chatgpt_4o_LatestParams = TypedDict(
    "Chatgpt_4o_LatestParams",
    {
        "max_tokens": Annotated[int, Field(ge=1)],
        "temperature": Annotated[float, Field(ge=0, le=2)],
        "top_p": Annotated[float, Field(ge=0, le=1)],
    },
    total=False,
)
setattr(Chatgpt_4o_LatestParams, "__pydantic_config__", _PARAMS_CONFIG)

Gpt_3_5_TurboParams = TypedDict(
    "Gpt_3_5_TurboParams",
    {
        "max_tokens": Annotated[int, Field(ge=1)],
        "temperature": Annotated[float, Field(ge=0, le=2)],
        "top_p": Annotated[float, Field(ge=0, le=1)],
    },
    total=False,
)
setattr(Gpt_3_5_TurboParams, "__pydantic_config__", _PARAMS_CONFIG)

Gpt_4_TurboParams = TypedDict(
    "Gpt_4_TurboParams",
    {
        "max_tokens": Annotated[int, Field(ge=1)],
        "temperature": Annotated[float, Field(ge=0, le=2)],
        "top_p": Annotated[float, Field(ge=0, le=1)],
    },
    total=False,
)
setattr(Gpt_4_TurboParams, "__pydantic_config__", _PARAMS_CONFIG)

Gpt_4_Turbo_2024_04_09Params = TypedDict(
    "Gpt_4_Turbo_2024_04_09Params",
    {
        "max_tokens": Annotated[int, Field(ge=1)],
        "temperature": Annotated[float, Field(ge=0, le=2)],
        "top_p": Annotated[float, Field(ge=0, le=1)],
    },
    total=False,
)
setattr(Gpt_4_Turbo_2024_04_09Params, "__pydantic_config__", _PARAMS_CONFIG)

Gpt_4_1Params = TypedDict(
    "Gpt_4_1Params",
    {
        "max_tokens": Annotated[int, Field(ge=1)],
        "temperature": Annotated[float, Field(ge=0, le=2)],
        "top_p": Annotated[float, Field(ge=0, le=1)],
    },
    total=False,
)
setattr(Gpt_4_1Params, "__pydantic_config__", _PARAMS_CONFIG)

Gpt_4_1_MiniParams = TypedDict(
    "Gpt_4_1_MiniParams",
    {
        "max_tokens": Annotated[int, Field(ge=1)],
        "temperature": Annotated[float, Field(ge=0, le=2)],
        "top_p": Annotated[float, Field(ge=0, le=1)],
    },
    total=False,
)
setattr(Gpt_4_1_MiniParams, "__pydantic_config__", _PARAMS_CONFIG)

Gpt_4_1_NanoParams = TypedDict(
    "Gpt_4_1_NanoParams",
    {
        "max_tokens": Annotated[int, Field(ge=1)],
        "temperature": Annotated[float, Field(ge=0, le=2)],
        "top_p": Annotated[float, Field(ge=0, le=1)],
    },
    total=False,
)
setattr(Gpt_4_1_NanoParams, "__pydantic_config__", _PARAMS_CONFIG)

Gpt_4oParams = TypedDict(
    "Gpt_4oParams",
    {
        "max_tokens": Annotated[int, Field(ge=1)],
        "temperature": Annotated[float, Field(ge=0, le=2)],
        "top_p": Annotated[float, Field(ge=0, le=1)],
    },
    total=False,
)
setattr(Gpt_4oParams, "__pydantic_config__", _PARAMS_CONFIG)

Gpt_4o_2024_11_20Params = TypedDict(
    "Gpt_4o_2024_11_20Params",
    {
        "max_tokens": Annotated[int, Field(ge=1)],
        "temperature": Annotated[float, Field(ge=0, le=2)],
        "top_p": Annotated[float, Field(ge=0, le=1)],
    },
    total=False,
)
setattr(Gpt_4o_2024_11_20Params, "__pydantic_config__", _PARAMS_CONFIG)

Gpt_4o_MiniParams = TypedDict(
    "Gpt_4o_MiniParams",
    {
        "max_tokens": Annotated[int, Field(ge=1)],
        "temperature": Annotated[float, Field(ge=0, le=2)],
        "top_p": Annotated[float, Field(ge=0, le=1)],
    },
    total=False,
)
setattr(Gpt_4o_MiniParams, "__pydantic_config__", _PARAMS_CONFIG)

Gpt_5Params = TypedDict(
    "Gpt_5Params",
    {
        "max_completion_tokens": Annotated[int, Field(ge=16)],
        "reasoning_effort": Literal["minimal", "low", "medium", "high"],
    },
    total=False,
)
setattr(Gpt_5Params, "__pydantic_config__", _PARAMS_CONFIG)

Gpt_5_Chat_LatestParams = TypedDict(
    "Gpt_5_Chat_LatestParams",
    {
        "max_completion_tokens": Annotated[int, Field(ge=16)],
    },
    total=False,
)
setattr(Gpt_5_Chat_LatestParams, "__pydantic_config__", _PARAMS_CONFIG)

Gpt_5_MiniParams = TypedDict(
    "Gpt_5_MiniParams",
    {
        "max_completion_tokens": Annotated[int, Field(ge=16)],
        "reasoning_effort": Literal["minimal", "low", "medium", "high"],
    },
    total=False,
)
setattr(Gpt_5_MiniParams, "__pydantic_config__", _PARAMS_CONFIG)

Gpt_5_NanoParams = TypedDict(
    "Gpt_5_NanoParams",
    {
        "max_completion_tokens": Annotated[int, Field(ge=16)],
        "reasoning_effort": Literal["minimal", "low", "medium", "high"],
    },
    total=False,
)
setattr(Gpt_5_NanoParams, "__pydantic_config__", _PARAMS_CONFIG)

Gpt_5_1Params = TypedDict(
    "Gpt_5_1Params",
    {
        "max_completion_tokens": Annotated[int, Field(ge=16)],
        "reasoning_effort": Literal["none", "low", "medium", "high"],
    },
    total=False,
)
setattr(Gpt_5_1Params, "__pydantic_config__", _PARAMS_CONFIG)

Gpt_5_1_Codex_Max_SubscriptionParams = TypedDict(
    "Gpt_5_1_Codex_Max_SubscriptionParams",
    {
        "reasoning.effort": Literal["minimal", "low", "medium", "high", "xhigh"],
        "reasoning.summary": Literal["auto", "concise", "detailed", "none"],
        "text.verbosity": Literal["low", "medium", "high"],
    },
    total=False,
)
setattr(Gpt_5_1_Codex_Max_SubscriptionParams, "__pydantic_config__", _PARAMS_CONFIG)

Gpt_5_1_Codex_SubscriptionParams = TypedDict(
    "Gpt_5_1_Codex_SubscriptionParams",
    {
        "reasoning.effort": Literal["minimal", "low", "medium", "high"],
        "reasoning.summary": Literal["auto", "concise", "detailed", "none"],
        "text.verbosity": Literal["low", "medium", "high"],
    },
    total=False,
)
setattr(Gpt_5_1_Codex_SubscriptionParams, "__pydantic_config__", _PARAMS_CONFIG)

Gpt_5_2Params = TypedDict(
    "Gpt_5_2Params",
    {
        "max_completion_tokens": Annotated[int, Field(ge=16)],
        "reasoning_effort": Literal["none", "low", "medium", "high", "xhigh"],
    },
    total=False,
)
setattr(Gpt_5_2Params, "__pydantic_config__", _PARAMS_CONFIG)

Gpt_5_2_Codex_SubscriptionParams = TypedDict(
    "Gpt_5_2_Codex_SubscriptionParams",
    {
        "reasoning.effort": Literal["minimal", "low", "medium", "high", "xhigh"],
        "reasoning.summary": Literal["auto", "concise", "detailed", "none"],
        "text.verbosity": Literal["low", "medium", "high"],
    },
    total=False,
)
setattr(Gpt_5_2_Codex_SubscriptionParams, "__pydantic_config__", _PARAMS_CONFIG)

Gpt_5_2_SubscriptionParams = TypedDict(
    "Gpt_5_2_SubscriptionParams",
    {
        "reasoning.effort": Literal["minimal", "low", "medium", "high", "xhigh"],
        "reasoning.summary": Literal["auto", "concise", "detailed", "none"],
        "text.verbosity": Literal["low", "medium", "high"],
    },
    total=False,
)
setattr(Gpt_5_2_SubscriptionParams, "__pydantic_config__", _PARAMS_CONFIG)

Gpt_5_3_CodexParams = TypedDict(
    "Gpt_5_3_CodexParams",
    {
        "max_completion_tokens": Annotated[int, Field(ge=16)],
        "reasoning_effort": Literal["low", "medium", "high", "xhigh"],
    },
    total=False,
)
setattr(Gpt_5_3_CodexParams, "__pydantic_config__", _PARAMS_CONFIG)

Gpt_5_3_Codex_Spark_SubscriptionParams = TypedDict(
    "Gpt_5_3_Codex_Spark_SubscriptionParams",
    {
        "reasoning.effort": Literal["minimal", "low", "medium", "high", "xhigh"],
        "reasoning.summary": Literal["auto", "concise", "detailed", "none"],
        "text.verbosity": Literal["low", "medium", "high"],
    },
    total=False,
)
setattr(Gpt_5_3_Codex_Spark_SubscriptionParams, "__pydantic_config__", _PARAMS_CONFIG)

Gpt_5_3_Codex_SubscriptionParams = TypedDict(
    "Gpt_5_3_Codex_SubscriptionParams",
    {
        "reasoning.effort": Literal["minimal", "low", "medium", "high", "xhigh"],
        "reasoning.summary": Literal["auto", "concise", "detailed", "none"],
        "text.verbosity": Literal["low", "medium", "high"],
    },
    total=False,
)
setattr(Gpt_5_3_Codex_SubscriptionParams, "__pydantic_config__", _PARAMS_CONFIG)

Gpt_5_4Params = TypedDict(
    "Gpt_5_4Params",
    {
        "max_completion_tokens": Annotated[int, Field(ge=16)],
        "reasoning_effort": Literal["none", "low", "medium", "high", "xhigh"],
    },
    total=False,
)
setattr(Gpt_5_4Params, "__pydantic_config__", _PARAMS_CONFIG)

Gpt_5_4_MiniParams = TypedDict(
    "Gpt_5_4_MiniParams",
    {
        "max_completion_tokens": Annotated[int, Field(ge=16)],
        "reasoning_effort": Literal["none", "low", "medium", "high", "xhigh"],
    },
    total=False,
)
setattr(Gpt_5_4_MiniParams, "__pydantic_config__", _PARAMS_CONFIG)

Gpt_5_4_Mini_SubscriptionParams = TypedDict(
    "Gpt_5_4_Mini_SubscriptionParams",
    {
        "reasoning.effort": Literal["minimal", "low", "medium", "high", "xhigh"],
        "reasoning.summary": Literal["auto", "concise", "detailed", "none"],
        "text.verbosity": Literal["low", "medium", "high"],
    },
    total=False,
)
setattr(Gpt_5_4_Mini_SubscriptionParams, "__pydantic_config__", _PARAMS_CONFIG)

Gpt_5_4_NanoParams = TypedDict(
    "Gpt_5_4_NanoParams",
    {
        "max_completion_tokens": Annotated[int, Field(ge=16)],
        "reasoning_effort": Literal["none", "low", "medium", "high", "xhigh"],
    },
    total=False,
)
setattr(Gpt_5_4_NanoParams, "__pydantic_config__", _PARAMS_CONFIG)

Gpt_5_4_ProParams = TypedDict(
    "Gpt_5_4_ProParams",
    {
        "max_completion_tokens": Annotated[int, Field(ge=16)],
        "reasoning_effort": Literal["medium", "high", "xhigh"],
    },
    total=False,
)
setattr(Gpt_5_4_ProParams, "__pydantic_config__", _PARAMS_CONFIG)

Gpt_5_4_Pro_SubscriptionParams = TypedDict(
    "Gpt_5_4_Pro_SubscriptionParams",
    {
        "reasoning.effort": Literal["medium", "high", "xhigh"],
        "reasoning.summary": Literal["auto", "concise", "detailed", "none"],
        "text.verbosity": Literal["low", "medium", "high"],
    },
    total=False,
)
setattr(Gpt_5_4_Pro_SubscriptionParams, "__pydantic_config__", _PARAMS_CONFIG)

Gpt_5_4_SubscriptionParams = TypedDict(
    "Gpt_5_4_SubscriptionParams",
    {
        "reasoning.effort": Literal["minimal", "low", "medium", "high", "xhigh"],
        "reasoning.summary": Literal["auto", "concise", "detailed", "none"],
        "text.verbosity": Literal["low", "medium", "high"],
    },
    total=False,
)
setattr(Gpt_5_4_SubscriptionParams, "__pydantic_config__", _PARAMS_CONFIG)

Gpt_5_5Params = TypedDict(
    "Gpt_5_5Params",
    {
        "max_completion_tokens": Annotated[int, Field(ge=16)],
        "reasoning_effort": Literal["none", "low", "medium", "high", "xhigh"],
    },
    total=False,
)
setattr(Gpt_5_5Params, "__pydantic_config__", _PARAMS_CONFIG)

Gpt_5_5_ProParams = TypedDict(
    "Gpt_5_5_ProParams",
    {
        "max_completion_tokens": Annotated[int, Field(ge=16)],
        "reasoning_effort": Literal["medium", "high", "xhigh"],
    },
    total=False,
)
setattr(Gpt_5_5_ProParams, "__pydantic_config__", _PARAMS_CONFIG)

Gpt_5_5_Pro_SubscriptionParams = TypedDict(
    "Gpt_5_5_Pro_SubscriptionParams",
    {
        "reasoning.effort": Literal["medium", "high", "xhigh"],
        "reasoning.summary": Literal["auto", "concise", "detailed", "none"],
        "text.verbosity": Literal["low", "medium", "high"],
    },
    total=False,
)
setattr(Gpt_5_5_Pro_SubscriptionParams, "__pydantic_config__", _PARAMS_CONFIG)

Gpt_5_5_SubscriptionParams = TypedDict(
    "Gpt_5_5_SubscriptionParams",
    {
        "reasoning.effort": Literal["minimal", "low", "medium", "high", "xhigh"],
        "reasoning.summary": Literal["auto", "concise", "detailed", "none"],
        "text.verbosity": Literal["low", "medium", "high"],
    },
    total=False,
)
setattr(Gpt_5_5_SubscriptionParams, "__pydantic_config__", _PARAMS_CONFIG)

Gpt_5_6_LunaParams = TypedDict(
    "Gpt_5_6_LunaParams",
    {
        "max_completion_tokens": Annotated[int, Field(ge=16)],
        "reasoning_effort": Literal["none", "low", "medium", "high"],
    },
    total=False,
)
setattr(Gpt_5_6_LunaParams, "__pydantic_config__", _PARAMS_CONFIG)

Gpt_5_6_SolParams = TypedDict(
    "Gpt_5_6_SolParams",
    {
        "max_completion_tokens": Annotated[int, Field(ge=16)],
        "reasoning_effort": Literal["none", "low", "medium", "high"],
    },
    total=False,
)
setattr(Gpt_5_6_SolParams, "__pydantic_config__", _PARAMS_CONFIG)

Gpt_Oss_120bParams = TypedDict(
    "Gpt_Oss_120bParams",
    {
        "max_completion_tokens": Annotated[int, Field(ge=1, le=131072)],
        "reasoning_effort": Literal["low", "medium", "high"],
    },
    total=False,
)
setattr(Gpt_Oss_120bParams, "__pydantic_config__", _PARAMS_CONFIG)

Gpt_Oss_20bParams = TypedDict(
    "Gpt_Oss_20bParams",
    {
        "max_completion_tokens": Annotated[int, Field(ge=1, le=131072)],
        "reasoning_effort": Literal["low", "medium", "high"],
    },
    total=False,
)
setattr(Gpt_Oss_20bParams, "__pydantic_config__", _PARAMS_CONFIG)

O1Params = TypedDict(
    "O1Params",
    {
        "max_completion_tokens": Annotated[int, Field(ge=16)],
        "reasoning_effort": Literal["low", "medium", "high", "xhigh"],
    },
    total=False,
)
setattr(O1Params, "__pydantic_config__", _PARAMS_CONFIG)

O1_MiniParams = TypedDict(
    "O1_MiniParams",
    {
        "max_tokens": Annotated[int, Field(ge=1)],
        "reasoning_effort": Literal["minimal", "low", "medium", "high"],
    },
    total=False,
)
setattr(O1_MiniParams, "__pydantic_config__", _PARAMS_CONFIG)

O1_PreviewParams = TypedDict(
    "O1_PreviewParams",
    {
        "max_tokens": Annotated[int, Field(ge=1)],
        "reasoning_effort": Literal["minimal", "low", "medium", "high"],
    },
    total=False,
)
setattr(O1_PreviewParams, "__pydantic_config__", _PARAMS_CONFIG)

O3Params = TypedDict(
    "O3Params",
    {
        "max_completion_tokens": Annotated[int, Field(ge=16)],
        "reasoning_effort": Literal["low", "medium", "high", "xhigh"],
    },
    total=False,
)
setattr(O3Params, "__pydantic_config__", _PARAMS_CONFIG)

O3_MiniParams = TypedDict(
    "O3_MiniParams",
    {
        "max_completion_tokens": Annotated[int, Field(ge=16)],
        "reasoning_effort": Literal["low", "medium", "high", "xhigh"],
    },
    total=False,
)
setattr(O3_MiniParams, "__pydantic_config__", _PARAMS_CONFIG)

O3_ProParams = TypedDict(
    "O3_ProParams",
    {
        "max_completion_tokens": Annotated[int, Field(ge=16)],
        "reasoning_effort": Literal["low", "medium", "high", "xhigh"],
    },
    total=False,
)
setattr(O3_ProParams, "__pydantic_config__", _PARAMS_CONFIG)

O4_MiniParams = TypedDict(
    "O4_MiniParams",
    {
        "max_completion_tokens": Annotated[int, Field(ge=16)],
        "reasoning_effort": Literal["low", "medium", "high", "xhigh"],
    },
    total=False,
)
setattr(O4_MiniParams, "__pydantic_config__", _PARAMS_CONFIG)

__all__ = [
    "Chatgpt_4o_LatestParams",
    "Gpt_3_5_TurboParams",
    "Gpt_4_TurboParams",
    "Gpt_4_Turbo_2024_04_09Params",
    "Gpt_4_1Params",
    "Gpt_4_1_MiniParams",
    "Gpt_4_1_NanoParams",
    "Gpt_4oParams",
    "Gpt_4o_2024_11_20Params",
    "Gpt_4o_MiniParams",
    "Gpt_5Params",
    "Gpt_5_Chat_LatestParams",
    "Gpt_5_MiniParams",
    "Gpt_5_NanoParams",
    "Gpt_5_1Params",
    "Gpt_5_1_Codex_Max_SubscriptionParams",
    "Gpt_5_1_Codex_SubscriptionParams",
    "Gpt_5_2Params",
    "Gpt_5_2_Codex_SubscriptionParams",
    "Gpt_5_2_SubscriptionParams",
    "Gpt_5_3_CodexParams",
    "Gpt_5_3_Codex_Spark_SubscriptionParams",
    "Gpt_5_3_Codex_SubscriptionParams",
    "Gpt_5_4Params",
    "Gpt_5_4_MiniParams",
    "Gpt_5_4_Mini_SubscriptionParams",
    "Gpt_5_4_NanoParams",
    "Gpt_5_4_ProParams",
    "Gpt_5_4_Pro_SubscriptionParams",
    "Gpt_5_4_SubscriptionParams",
    "Gpt_5_5Params",
    "Gpt_5_5_ProParams",
    "Gpt_5_5_Pro_SubscriptionParams",
    "Gpt_5_5_SubscriptionParams",
    "Gpt_5_6_LunaParams",
    "Gpt_5_6_SolParams",
    "Gpt_Oss_120bParams",
    "Gpt_Oss_20bParams",
    "O1Params",
    "O1_MiniParams",
    "O1_PreviewParams",
    "O3Params",
    "O3_MiniParams",
    "O3_ProParams",
    "O4_MiniParams",
]
