# AUTO-GENERATED by packages/modelparams-python/scripts/codegen.ts.
# Do not edit by hand; the YAML catalog under /models is the source of truth.

# ruff: noqa: F401

from typing import Annotated, Literal

from pydantic import ConfigDict, Field
from typing_extensions import TypedDict

_PARAMS_CONFIG = ConfigDict(strict=True, extra="forbid")

SonarParams = TypedDict(
    "SonarParams",
    {
        "max_tokens": Annotated[int, Field(ge=1, le=128000)],
        "temperature": Annotated[float, Field(ge=0, le=2)],
        "top_p": Annotated[float, Field(ge=0, le=1)],
        "search_mode": Literal["web", "academic", "sec"],
        "search_recency_filter": Literal["hour", "day", "week", "month", "year"],
        "search_domain_filter": str,
        "search_after_date_filter": str,
        "search_before_date_filter": str,
        "web_search_options.search_context_size": Literal["low", "medium", "high"],
        "return_images": bool,
        "return_related_questions": bool,
        "disable_search": bool,
    },
    total=False,
)
setattr(SonarParams, "__pydantic_config__", _PARAMS_CONFIG)

Sonar_Deep_ResearchParams = TypedDict(
    "Sonar_Deep_ResearchParams",
    {
        "max_tokens": Annotated[int, Field(ge=1, le=128000)],
        "temperature": Annotated[float, Field(ge=0, le=2)],
        "top_p": Annotated[float, Field(ge=0, le=1)],
        "reasoning_effort": Literal["minimal", "low", "medium", "high"],
        "search_mode": Literal["web", "academic", "sec"],
        "search_recency_filter": Literal["hour", "day", "week", "month", "year"],
        "search_domain_filter": str,
        "search_after_date_filter": str,
        "search_before_date_filter": str,
        "web_search_options.search_context_size": Literal["low", "medium", "high"],
        "return_images": bool,
        "return_related_questions": bool,
    },
    total=False,
)
setattr(Sonar_Deep_ResearchParams, "__pydantic_config__", _PARAMS_CONFIG)

Sonar_ProParams = TypedDict(
    "Sonar_ProParams",
    {
        "max_tokens": Annotated[int, Field(ge=1, le=128000)],
        "temperature": Annotated[float, Field(ge=0, le=2)],
        "top_p": Annotated[float, Field(ge=0, le=1)],
        "search_mode": Literal["web", "academic", "sec"],
        "search_recency_filter": Literal["hour", "day", "week", "month", "year"],
        "search_domain_filter": str,
        "search_after_date_filter": str,
        "search_before_date_filter": str,
        "web_search_options.search_context_size": Literal["low", "medium", "high"],
        "return_images": bool,
        "return_related_questions": bool,
        "disable_search": bool,
    },
    total=False,
)
setattr(Sonar_ProParams, "__pydantic_config__", _PARAMS_CONFIG)

Sonar_Reasoning_ProParams = TypedDict(
    "Sonar_Reasoning_ProParams",
    {
        "max_tokens": Annotated[int, Field(ge=1, le=128000)],
        "temperature": Annotated[float, Field(ge=0, le=2)],
        "top_p": Annotated[float, Field(ge=0, le=1)],
        "search_mode": Literal["web", "academic", "sec"],
        "search_recency_filter": Literal["hour", "day", "week", "month", "year"],
        "search_domain_filter": str,
        "search_after_date_filter": str,
        "search_before_date_filter": str,
        "web_search_options.search_context_size": Literal["low", "medium", "high"],
        "return_images": bool,
        "return_related_questions": bool,
        "disable_search": bool,
    },
    total=False,
)
setattr(Sonar_Reasoning_ProParams, "__pydantic_config__", _PARAMS_CONFIG)

__all__ = [
    "SonarParams",
    "Sonar_Deep_ResearchParams",
    "Sonar_ProParams",
    "Sonar_Reasoning_ProParams",
]
