# AUTO-GENERATED by packages/modelparams-python/scripts/codegen.ts.
# Do not edit by hand; the YAML catalog under /models is the source of truth.

# ruff: noqa: F401

from typing import Annotated, Literal

from pydantic import ConfigDict, Field
from typing_extensions import TypedDict

_PARAMS_CONFIG = ConfigDict(strict=True, extra="forbid")

InklingParams = TypedDict(
    "InklingParams",
    {
        "max_tokens": Annotated[int, Field(ge=1)],
        "temperature": float,
        "top_p": Annotated[float, Field(ge=0, le=1)],
        "reasoning_effort": Literal["none", "minimal", "low", "medium", "high", "xhigh"],
        "separate_reasoning": bool,
    },
    total=False,
)
setattr(InklingParams, "__pydantic_config__", _PARAMS_CONFIG)

__all__ = [
    "InklingParams",
]
