# AUTO-GENERATED by packages/modelparams-python/scripts/codegen.ts.
# Do not edit by hand; the YAML catalog under /models is the source of truth.

# ruff: noqa: F401

from typing import Annotated, Literal

from pydantic import ConfigDict, Field
from typing_extensions import TypedDict

_PARAMS_CONFIG = ConfigDict(strict=True, extra="forbid")

Gemini_2_5_FlashParams = TypedDict(
    "Gemini_2_5_FlashParams",
    {
        "generationConfig.maxOutputTokens": Annotated[int, Field(ge=1, le=65536)],
        "generationConfig.temperature": Annotated[float, Field(ge=0, le=2)],
        "generationConfig.topP": Annotated[float, Field(ge=0, le=1)],
        "generationConfig.topK": Annotated[int, Field(ge=1)],
        "generationConfig.seed": int,
        "generationConfig.candidateCount": Annotated[int, Field(ge=1, le=8)],
        "generationConfig.stopSequences": str,
        "generationConfig.presencePenalty": Annotated[float, Field(ge=-2, le=1)],
        "generationConfig.frequencyPenalty": Annotated[float, Field(ge=-2, le=1)],
        "generationConfig.responseMimeType": Literal["text/plain", "application/json"],
        "generationConfig.thinkingConfig.thinkingBudget": Annotated[int, Field(ge=0)],
        "generationConfig.thinkingConfig.includeThoughts": bool,
    },
    total=False,
)
setattr(Gemini_2_5_FlashParams, "__pydantic_config__", _PARAMS_CONFIG)

Gemini_2_5_Flash_LiteParams = TypedDict(
    "Gemini_2_5_Flash_LiteParams",
    {
        "generationConfig.maxOutputTokens": Annotated[int, Field(ge=1, le=65536)],
        "generationConfig.temperature": Annotated[float, Field(ge=0, le=2)],
        "generationConfig.topP": Annotated[float, Field(ge=0, le=1)],
        "generationConfig.topK": Annotated[int, Field(ge=1)],
        "generationConfig.seed": int,
        "generationConfig.candidateCount": Annotated[int, Field(ge=1, le=8)],
        "generationConfig.stopSequences": str,
        "generationConfig.presencePenalty": Annotated[float, Field(ge=-2, le=1)],
        "generationConfig.frequencyPenalty": Annotated[float, Field(ge=-2, le=1)],
        "generationConfig.responseMimeType": Literal["text/plain", "application/json"],
    },
    total=False,
)
setattr(Gemini_2_5_Flash_LiteParams, "__pydantic_config__", _PARAMS_CONFIG)

Gemini_2_5_ProParams = TypedDict(
    "Gemini_2_5_ProParams",
    {
        "generationConfig.maxOutputTokens": Annotated[int, Field(ge=1, le=65536)],
        "generationConfig.temperature": Annotated[float, Field(ge=0, le=2)],
        "generationConfig.topP": Annotated[float, Field(ge=0, le=1)],
        "generationConfig.topK": Annotated[int, Field(ge=1)],
        "generationConfig.seed": int,
        "generationConfig.candidateCount": Annotated[int, Field(ge=1, le=8)],
        "generationConfig.stopSequences": str,
        "generationConfig.presencePenalty": Annotated[float, Field(ge=-2, le=1)],
        "generationConfig.frequencyPenalty": Annotated[float, Field(ge=-2, le=1)],
        "generationConfig.responseMimeType": Literal["text/plain", "application/json"],
        "generationConfig.thinkingConfig.thinkingBudget": Annotated[int, Field(ge=0)],
        "generationConfig.thinkingConfig.includeThoughts": bool,
    },
    total=False,
)
setattr(Gemini_2_5_ProParams, "__pydantic_config__", _PARAMS_CONFIG)

Gemini_3_Flash_PreviewParams = TypedDict(
    "Gemini_3_Flash_PreviewParams",
    {
        "generationConfig.maxOutputTokens": Annotated[int, Field(ge=1, le=65536)],
        "generationConfig.temperature": Annotated[float, Field(ge=0, le=2)],
        "generationConfig.topP": Annotated[float, Field(ge=0, le=1)],
        "generationConfig.topK": Annotated[int, Field(ge=1)],
        "generationConfig.seed": int,
        "generationConfig.candidateCount": Annotated[int, Field(ge=1, le=8)],
        "generationConfig.stopSequences": str,
        "generationConfig.presencePenalty": Annotated[float, Field(ge=-2, le=1)],
        "generationConfig.frequencyPenalty": Annotated[float, Field(ge=-2, le=1)],
        "generationConfig.responseMimeType": Literal["text/plain", "application/json"],
        "generationConfig.thinkingConfig.thinkingBudget": Annotated[int, Field(ge=0)],
        "generationConfig.thinkingConfig.includeThoughts": bool,
        "generationConfig.thinkingConfig.thinkingLevel": Literal["minimal", "low", "medium", "high"],
    },
    total=False,
)
setattr(Gemini_3_Flash_PreviewParams, "__pydantic_config__", _PARAMS_CONFIG)

Gemini_3_1_Flash_LiteParams = TypedDict(
    "Gemini_3_1_Flash_LiteParams",
    {
        "generationConfig.maxOutputTokens": Annotated[int, Field(ge=1, le=65536)],
        "generationConfig.temperature": Annotated[float, Field(ge=0, le=2)],
        "generationConfig.topP": Annotated[float, Field(ge=0, le=1)],
        "generationConfig.topK": Annotated[int, Field(ge=1)],
        "generationConfig.seed": int,
        "generationConfig.candidateCount": Annotated[int, Field(ge=1, le=8)],
        "generationConfig.stopSequences": str,
        "generationConfig.presencePenalty": Annotated[float, Field(ge=-2, le=1)],
        "generationConfig.frequencyPenalty": Annotated[float, Field(ge=-2, le=1)],
        "generationConfig.responseMimeType": Literal["text/plain", "application/json"],
        "generationConfig.thinkingConfig.thinkingBudget": Annotated[int, Field(ge=0)],
        "generationConfig.thinkingConfig.includeThoughts": bool,
        "generationConfig.thinkingConfig.thinkingLevel": Literal["minimal", "low", "medium", "high"],
    },
    total=False,
)
setattr(Gemini_3_1_Flash_LiteParams, "__pydantic_config__", _PARAMS_CONFIG)

Gemini_3_1_Pro_PreviewParams = TypedDict(
    "Gemini_3_1_Pro_PreviewParams",
    {
        "generationConfig.maxOutputTokens": Annotated[int, Field(ge=1, le=65536)],
        "generationConfig.temperature": Annotated[float, Field(ge=0, le=2)],
        "generationConfig.topP": Annotated[float, Field(ge=0, le=1)],
        "generationConfig.topK": Annotated[int, Field(ge=1)],
        "generationConfig.seed": int,
        "generationConfig.candidateCount": Annotated[int, Field(ge=1, le=8)],
        "generationConfig.stopSequences": str,
        "generationConfig.presencePenalty": Annotated[float, Field(ge=-2, le=1)],
        "generationConfig.frequencyPenalty": Annotated[float, Field(ge=-2, le=1)],
        "generationConfig.responseMimeType": Literal["text/plain", "application/json"],
        "generationConfig.thinkingConfig.thinkingBudget": Annotated[int, Field(ge=0)],
        "generationConfig.thinkingConfig.includeThoughts": bool,
        "generationConfig.thinkingConfig.thinkingLevel": Literal["minimal", "low", "medium", "high"],
    },
    total=False,
)
setattr(Gemini_3_1_Pro_PreviewParams, "__pydantic_config__", _PARAMS_CONFIG)

Gemini_3_1_Pro_Preview_CustomtoolsParams = TypedDict(
    "Gemini_3_1_Pro_Preview_CustomtoolsParams",
    {
        "generationConfig.maxOutputTokens": Annotated[int, Field(ge=1, le=65536)],
        "generationConfig.temperature": Annotated[float, Field(ge=0, le=2)],
        "generationConfig.topP": Annotated[float, Field(ge=0, le=1)],
        "generationConfig.topK": Annotated[int, Field(ge=1)],
        "generationConfig.seed": int,
        "generationConfig.candidateCount": Annotated[int, Field(ge=1, le=8)],
        "generationConfig.stopSequences": str,
        "generationConfig.presencePenalty": Annotated[float, Field(ge=-2, le=1)],
        "generationConfig.frequencyPenalty": Annotated[float, Field(ge=-2, le=1)],
        "generationConfig.responseMimeType": Literal["text/plain", "application/json"],
        "generationConfig.thinkingConfig.thinkingBudget": Annotated[int, Field(ge=0)],
        "generationConfig.thinkingConfig.includeThoughts": bool,
        "generationConfig.thinkingConfig.thinkingLevel": Literal["minimal", "low", "medium", "high"],
    },
    total=False,
)
setattr(Gemini_3_1_Pro_Preview_CustomtoolsParams, "__pydantic_config__", _PARAMS_CONFIG)

Gemini_3_5_FlashParams = TypedDict(
    "Gemini_3_5_FlashParams",
    {
        "generationConfig.maxOutputTokens": Annotated[int, Field(ge=1, le=65536)],
        "generationConfig.temperature": Annotated[float, Field(ge=0, le=2)],
        "generationConfig.topP": Annotated[float, Field(ge=0, le=1)],
        "generationConfig.topK": Annotated[int, Field(ge=1)],
        "generationConfig.seed": int,
        "generationConfig.candidateCount": Annotated[int, Field(ge=1, le=8)],
        "generationConfig.stopSequences": str,
        "generationConfig.presencePenalty": Annotated[float, Field(ge=-2, le=1)],
        "generationConfig.frequencyPenalty": Annotated[float, Field(ge=-2, le=1)],
        "generationConfig.responseMimeType": Literal["text/plain", "application/json"],
        "generationConfig.thinkingConfig.thinkingBudget": Annotated[int, Field(ge=0)],
        "generationConfig.thinkingConfig.includeThoughts": bool,
        "generationConfig.thinkingConfig.thinkingLevel": Literal["minimal", "low", "medium", "high"],
    },
    total=False,
)
setattr(Gemini_3_5_FlashParams, "__pydantic_config__", _PARAMS_CONFIG)

Gemini_3_5_Flash_LiteParams = TypedDict(
    "Gemini_3_5_Flash_LiteParams",
    {
        "generationConfig.maxOutputTokens": Annotated[int, Field(ge=1, le=65536)],
        "generationConfig.temperature": Annotated[float, Field(ge=0, le=2)],
        "generationConfig.topP": Annotated[float, Field(ge=0, le=1)],
        "generationConfig.topK": Annotated[int, Field(ge=1)],
        "generationConfig.seed": int,
        "generationConfig.candidateCount": Annotated[int, Field(ge=1, le=8)],
        "generationConfig.stopSequences": str,
        "generationConfig.responseMimeType": Literal["text/plain", "application/json"],
        "generationConfig.thinkingConfig.thinkingBudget": Annotated[int, Field(ge=0)],
        "generationConfig.thinkingConfig.includeThoughts": bool,
        "generationConfig.thinkingConfig.thinkingLevel": Literal["minimal", "low", "medium", "high"],
    },
    total=False,
)
setattr(Gemini_3_5_Flash_LiteParams, "__pydantic_config__", _PARAMS_CONFIG)

Gemini_3_6_FlashParams = TypedDict(
    "Gemini_3_6_FlashParams",
    {
        "generationConfig.maxOutputTokens": Annotated[int, Field(ge=1, le=65536)],
        "generationConfig.temperature": Annotated[float, Field(ge=0, le=2)],
        "generationConfig.topP": Annotated[float, Field(ge=0, le=1)],
        "generationConfig.topK": Annotated[int, Field(ge=1)],
        "generationConfig.seed": int,
        "generationConfig.candidateCount": Annotated[int, Field(ge=1, le=8)],
        "generationConfig.stopSequences": str,
        "generationConfig.responseMimeType": Literal["text/plain", "application/json"],
        "generationConfig.thinkingConfig.thinkingBudget": Annotated[int, Field(ge=0)],
        "generationConfig.thinkingConfig.includeThoughts": bool,
        "generationConfig.thinkingConfig.thinkingLevel": Literal["minimal", "low", "medium", "high"],
    },
    total=False,
)
setattr(Gemini_3_6_FlashParams, "__pydantic_config__", _PARAMS_CONFIG)

Gemini_3_7_FlashParams = TypedDict(
    "Gemini_3_7_FlashParams",
    {
        "generationConfig.maxOutputTokens": Annotated[int, Field(ge=1, le=65536)],
        "generationConfig.temperature": Annotated[float, Field(ge=0, le=2)],
        "generationConfig.topP": Annotated[float, Field(ge=0, le=1)],
        "generationConfig.topK": Annotated[int, Field(ge=1)],
        "generationConfig.seed": int,
        "generationConfig.candidateCount": Annotated[int, Field(ge=1, le=8)],
        "generationConfig.stopSequences": str,
        "generationConfig.responseMimeType": Literal["text/plain", "application/json"],
        "generationConfig.thinkingConfig.thinkingBudget": Annotated[int, Field(ge=0)],
        "generationConfig.thinkingConfig.includeThoughts": bool,
        "generationConfig.thinkingConfig.thinkingLevel": Literal["minimal", "low", "medium", "high"],
    },
    total=False,
)
setattr(Gemini_3_7_FlashParams, "__pydantic_config__", _PARAMS_CONFIG)

__all__ = [
    "Gemini_2_5_FlashParams",
    "Gemini_2_5_Flash_LiteParams",
    "Gemini_2_5_ProParams",
    "Gemini_3_Flash_PreviewParams",
    "Gemini_3_1_Flash_LiteParams",
    "Gemini_3_1_Pro_PreviewParams",
    "Gemini_3_1_Pro_Preview_CustomtoolsParams",
    "Gemini_3_5_FlashParams",
    "Gemini_3_5_Flash_LiteParams",
    "Gemini_3_6_FlashParams",
    "Gemini_3_7_FlashParams",
]
