# AUTO-GENERATED by packages/modelparams-python/scripts/codegen.ts.
# Do not edit by hand; the YAML catalog under /models is the source of truth.

# ruff: noqa: F401

from typing import Annotated, Literal

from pydantic import ConfigDict, Field
from typing_extensions import TypedDict

_PARAMS_CONFIG = ConfigDict(strict=True, extra="forbid")

Mimo_V2_5Params = TypedDict(
    "Mimo_V2_5Params",
    {
        "max_completion_tokens": Annotated[int, Field(ge=1)],
        "thinking.type": Literal["enabled", "disabled"],
        "temperature": Annotated[float, Field(ge=0, le=2)],
        "top_p": Annotated[float, Field(ge=0, le=1)],
        "response_format.type": Literal["text", "json_object"],
    },
    total=False,
)
setattr(Mimo_V2_5Params, "__pydantic_config__", _PARAMS_CONFIG)

Mimo_V2_5_ProParams = TypedDict(
    "Mimo_V2_5_ProParams",
    {
        "max_completion_tokens": Annotated[int, Field(ge=1)],
        "thinking.type": Literal["enabled", "disabled"],
        "temperature": Annotated[float, Field(ge=0, le=2)],
        "top_p": Annotated[float, Field(ge=0, le=1)],
        "presence_penalty": Annotated[float, Field(ge=-2, le=2)],
        "frequency_penalty": Annotated[float, Field(ge=-2, le=2)],
        "stop": str,
        "response_format.type": Literal["text", "json_object"],
    },
    total=False,
)
setattr(Mimo_V2_5_ProParams, "__pydantic_config__", _PARAMS_CONFIG)

Mimo_V2_5_SubscriptionParams = TypedDict(
    "Mimo_V2_5_SubscriptionParams",
    {
        "max_completion_tokens": Annotated[int, Field(ge=1)],
        "thinking.type": Literal["enabled", "disabled"],
        "temperature": Annotated[float, Field(ge=0, le=2)],
        "top_p": Annotated[float, Field(ge=0, le=1)],
        "response_format.type": Literal["text", "json_object"],
    },
    total=False,
)
setattr(Mimo_V2_5_SubscriptionParams, "__pydantic_config__", _PARAMS_CONFIG)

__all__ = [
    "Mimo_V2_5Params",
    "Mimo_V2_5_ProParams",
    "Mimo_V2_5_SubscriptionParams",
]
