# AUTO-GENERATED by packages/modelparams-python/scripts/codegen.ts.
# Do not edit by hand; the YAML catalog under /models is the source of truth.

# ruff: noqa: F401

from typing import Annotated, Literal

from pydantic import ConfigDict, Field
from typing_extensions import TypedDict

_PARAMS_CONFIG = ConfigDict(strict=True, extra="forbid")

Glm_4_5Params = TypedDict(
    "Glm_4_5Params",
    {
        "max_tokens": Annotated[int, Field(ge=1)],
        "temperature": Annotated[float, Field(ge=0, le=1)],
        "top_p": Annotated[float, Field(ge=0.01, le=1)],
        "do_sample": bool,
        "thinking.type": Literal["enabled", "disabled"],
        "response_format.type": Literal["text", "json_object"],
    },
    total=False,
)
setattr(Glm_4_5Params, "__pydantic_config__", _PARAMS_CONFIG)

Glm_4_5_AirParams = TypedDict(
    "Glm_4_5_AirParams",
    {
        "max_tokens": Annotated[int, Field(ge=1)],
        "temperature": Annotated[float, Field(ge=0, le=1)],
        "top_p": Annotated[float, Field(ge=0.01, le=1)],
        "do_sample": bool,
        "thinking.type": Literal["enabled", "disabled"],
        "response_format.type": Literal["text", "json_object"],
    },
    total=False,
)
setattr(Glm_4_5_AirParams, "__pydantic_config__", _PARAMS_CONFIG)

Glm_4_5_Air_SubscriptionParams = TypedDict(
    "Glm_4_5_Air_SubscriptionParams",
    {
        "max_tokens": Annotated[int, Field(ge=1)],
        "temperature": Annotated[float, Field(ge=0, le=1)],
        "top_p": Annotated[float, Field(ge=0.01, le=1)],
        "do_sample": bool,
        "thinking.type": Literal["enabled", "disabled"],
        "response_format.type": Literal["text", "json_object"],
    },
    total=False,
)
setattr(Glm_4_5_Air_SubscriptionParams, "__pydantic_config__", _PARAMS_CONFIG)

Glm_4_5_AirxParams = TypedDict(
    "Glm_4_5_AirxParams",
    {
        "max_tokens": Annotated[int, Field(ge=1)],
        "temperature": Annotated[float, Field(ge=0, le=1)],
        "top_p": Annotated[float, Field(ge=0.01, le=1)],
        "do_sample": bool,
        "thinking.type": Literal["enabled", "disabled"],
        "response_format.type": Literal["text", "json_object"],
    },
    total=False,
)
setattr(Glm_4_5_AirxParams, "__pydantic_config__", _PARAMS_CONFIG)

Glm_4_5_FlashParams = TypedDict(
    "Glm_4_5_FlashParams",
    {
        "max_tokens": Annotated[int, Field(ge=1)],
        "temperature": Annotated[float, Field(ge=0, le=1)],
        "top_p": Annotated[float, Field(ge=0.01, le=1)],
        "do_sample": bool,
        "thinking.type": Literal["enabled", "disabled"],
        "response_format.type": Literal["text", "json_object"],
    },
    total=False,
)
setattr(Glm_4_5_FlashParams, "__pydantic_config__", _PARAMS_CONFIG)

Glm_4_5_SubscriptionParams = TypedDict(
    "Glm_4_5_SubscriptionParams",
    {
        "max_tokens": Annotated[int, Field(ge=1)],
        "temperature": Annotated[float, Field(ge=0, le=1)],
        "top_p": Annotated[float, Field(ge=0.01, le=1)],
        "do_sample": bool,
        "thinking.type": Literal["enabled", "disabled"],
        "response_format.type": Literal["text", "json_object"],
    },
    total=False,
)
setattr(Glm_4_5_SubscriptionParams, "__pydantic_config__", _PARAMS_CONFIG)

Glm_4_5_XParams = TypedDict(
    "Glm_4_5_XParams",
    {
        "max_tokens": Annotated[int, Field(ge=1)],
        "temperature": Annotated[float, Field(ge=0, le=1)],
        "top_p": Annotated[float, Field(ge=0.01, le=1)],
        "do_sample": bool,
        "thinking.type": Literal["enabled", "disabled"],
        "response_format.type": Literal["text", "json_object"],
    },
    total=False,
)
setattr(Glm_4_5_XParams, "__pydantic_config__", _PARAMS_CONFIG)

Glm_4_6Params = TypedDict(
    "Glm_4_6Params",
    {
        "max_tokens": Annotated[int, Field(ge=1)],
        "temperature": Annotated[float, Field(ge=0, le=1)],
        "top_p": Annotated[float, Field(ge=0.01, le=1)],
        "do_sample": bool,
        "thinking.type": Literal["enabled", "disabled"],
        "response_format.type": Literal["text", "json_object"],
    },
    total=False,
)
setattr(Glm_4_6Params, "__pydantic_config__", _PARAMS_CONFIG)

Glm_4_6_SubscriptionParams = TypedDict(
    "Glm_4_6_SubscriptionParams",
    {
        "max_tokens": Annotated[int, Field(ge=1)],
        "temperature": Annotated[float, Field(ge=0, le=1)],
        "top_p": Annotated[float, Field(ge=0.01, le=1)],
        "do_sample": bool,
        "thinking.type": Literal["enabled", "disabled"],
        "response_format.type": Literal["text", "json_object"],
    },
    total=False,
)
setattr(Glm_4_6_SubscriptionParams, "__pydantic_config__", _PARAMS_CONFIG)

Glm_4_7Params = TypedDict(
    "Glm_4_7Params",
    {
        "max_tokens": Annotated[int, Field(ge=1)],
        "temperature": Annotated[float, Field(ge=0, le=1)],
        "top_p": Annotated[float, Field(ge=0.01, le=1)],
        "do_sample": bool,
        "thinking.type": Literal["enabled", "disabled"],
        "response_format.type": Literal["text", "json_object"],
    },
    total=False,
)
setattr(Glm_4_7Params, "__pydantic_config__", _PARAMS_CONFIG)

Glm_4_7_FlashParams = TypedDict(
    "Glm_4_7_FlashParams",
    {
        "max_tokens": Annotated[int, Field(ge=1)],
        "temperature": Annotated[float, Field(ge=0, le=1)],
        "top_p": Annotated[float, Field(ge=0.01, le=1)],
        "do_sample": bool,
        "thinking.type": Literal["enabled", "disabled"],
        "response_format.type": Literal["text", "json_object"],
    },
    total=False,
)
setattr(Glm_4_7_FlashParams, "__pydantic_config__", _PARAMS_CONFIG)

Glm_4_7_FlashxParams = TypedDict(
    "Glm_4_7_FlashxParams",
    {
        "max_tokens": Annotated[int, Field(ge=1)],
        "temperature": Annotated[float, Field(ge=0, le=1)],
        "top_p": Annotated[float, Field(ge=0.01, le=1)],
        "do_sample": bool,
        "thinking.type": Literal["enabled", "disabled"],
        "response_format.type": Literal["text", "json_object"],
    },
    total=False,
)
setattr(Glm_4_7_FlashxParams, "__pydantic_config__", _PARAMS_CONFIG)

Glm_4_7_SubscriptionParams = TypedDict(
    "Glm_4_7_SubscriptionParams",
    {
        "max_tokens": Annotated[int, Field(ge=1)],
        "temperature": Annotated[float, Field(ge=0, le=1)],
        "top_p": Annotated[float, Field(ge=0.01, le=1)],
        "do_sample": bool,
        "thinking.type": Literal["enabled", "disabled"],
        "response_format.type": Literal["text", "json_object"],
    },
    total=False,
)
setattr(Glm_4_7_SubscriptionParams, "__pydantic_config__", _PARAMS_CONFIG)

Glm_5Params = TypedDict(
    "Glm_5Params",
    {
        "max_tokens": Annotated[int, Field(ge=1)],
        "temperature": Annotated[float, Field(ge=0, le=1)],
        "top_p": Annotated[float, Field(ge=0.01, le=1)],
        "do_sample": bool,
        "thinking.type": Literal["enabled", "disabled"],
        "response_format.type": Literal["text", "json_object"],
    },
    total=False,
)
setattr(Glm_5Params, "__pydantic_config__", _PARAMS_CONFIG)

Glm_5_SubscriptionParams = TypedDict(
    "Glm_5_SubscriptionParams",
    {
        "max_tokens": Annotated[int, Field(ge=1)],
        "temperature": Annotated[float, Field(ge=0, le=1)],
        "top_p": Annotated[float, Field(ge=0.01, le=1)],
        "do_sample": bool,
        "thinking.type": Literal["enabled", "disabled"],
        "response_format.type": Literal["text", "json_object"],
    },
    total=False,
)
setattr(Glm_5_SubscriptionParams, "__pydantic_config__", _PARAMS_CONFIG)

Glm_5_TurboParams = TypedDict(
    "Glm_5_TurboParams",
    {
        "max_tokens": Annotated[int, Field(ge=1)],
        "temperature": Annotated[float, Field(ge=0, le=1)],
        "top_p": Annotated[float, Field(ge=0.01, le=1)],
        "do_sample": bool,
        "thinking.type": Literal["enabled", "disabled"],
        "response_format.type": Literal["text", "json_object"],
    },
    total=False,
)
setattr(Glm_5_TurboParams, "__pydantic_config__", _PARAMS_CONFIG)

Glm_5_Turbo_SubscriptionParams = TypedDict(
    "Glm_5_Turbo_SubscriptionParams",
    {
        "max_tokens": Annotated[int, Field(ge=1)],
        "temperature": Annotated[float, Field(ge=0, le=1)],
        "top_p": Annotated[float, Field(ge=0.01, le=1)],
        "do_sample": bool,
        "thinking.type": Literal["enabled", "disabled"],
        "response_format.type": Literal["text", "json_object"],
    },
    total=False,
)
setattr(Glm_5_Turbo_SubscriptionParams, "__pydantic_config__", _PARAMS_CONFIG)

Glm_5_1Params = TypedDict(
    "Glm_5_1Params",
    {
        "max_tokens": Annotated[int, Field(ge=1)],
        "temperature": Annotated[float, Field(ge=0, le=1)],
        "top_p": Annotated[float, Field(ge=0.01, le=1)],
        "do_sample": bool,
        "thinking.type": Literal["enabled", "disabled"],
        "response_format.type": Literal["text", "json_object"],
    },
    total=False,
)
setattr(Glm_5_1Params, "__pydantic_config__", _PARAMS_CONFIG)

Glm_5_1_SubscriptionParams = TypedDict(
    "Glm_5_1_SubscriptionParams",
    {
        "max_tokens": Annotated[int, Field(ge=1)],
        "temperature": Annotated[float, Field(ge=0, le=1)],
        "top_p": Annotated[float, Field(ge=0.01, le=1)],
        "do_sample": bool,
        "thinking.type": Literal["enabled", "disabled"],
        "response_format.type": Literal["text", "json_object"],
    },
    total=False,
)
setattr(Glm_5_1_SubscriptionParams, "__pydantic_config__", _PARAMS_CONFIG)

Glm_5_2Params = TypedDict(
    "Glm_5_2Params",
    {
        "max_tokens": Annotated[int, Field(ge=1, le=131072)],
        "temperature": Annotated[float, Field(ge=0, le=1)],
        "top_p": Annotated[float, Field(ge=0.01, le=1)],
        "do_sample": bool,
        "thinking.type": Literal["enabled", "disabled"],
        "reasoning_effort": Literal["none", "minimal", "low", "medium", "high", "xhigh", "max"],
        "response_format.type": Literal["text", "json_object"],
    },
    total=False,
)
setattr(Glm_5_2Params, "__pydantic_config__", _PARAMS_CONFIG)

Glm_5_2_SubscriptionParams = TypedDict(
    "Glm_5_2_SubscriptionParams",
    {
        "max_tokens": Annotated[int, Field(ge=1, le=131072)],
        "temperature": Annotated[float, Field(ge=0, le=1)],
        "top_p": Annotated[float, Field(ge=0.01, le=1)],
        "do_sample": bool,
        "thinking.type": Literal["enabled", "disabled"],
        "reasoning_effort": Literal["none", "minimal", "low", "medium", "high", "xhigh", "max"],
        "response_format.type": Literal["text", "json_object"],
    },
    total=False,
)
setattr(Glm_5_2_SubscriptionParams, "__pydantic_config__", _PARAMS_CONFIG)

__all__ = [
    "Glm_4_5Params",
    "Glm_4_5_AirParams",
    "Glm_4_5_Air_SubscriptionParams",
    "Glm_4_5_AirxParams",
    "Glm_4_5_FlashParams",
    "Glm_4_5_SubscriptionParams",
    "Glm_4_5_XParams",
    "Glm_4_6Params",
    "Glm_4_6_SubscriptionParams",
    "Glm_4_7Params",
    "Glm_4_7_FlashParams",
    "Glm_4_7_FlashxParams",
    "Glm_4_7_SubscriptionParams",
    "Glm_5Params",
    "Glm_5_SubscriptionParams",
    "Glm_5_TurboParams",
    "Glm_5_Turbo_SubscriptionParams",
    "Glm_5_1Params",
    "Glm_5_1_SubscriptionParams",
    "Glm_5_2Params",
    "Glm_5_2_SubscriptionParams",
]
