import fs from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { loadAllModels } from "../../../src/data/load.js";
import { loadAllDeprecations } from "../../../src/data/load-deprecations.js";
import { loadProviderEndpoints } from "../../../src/data/provider-endpoints.js";
import { authSuffix, modelId, type Model, type Parameter } from "../../../src/schema/model.js";
import { DeprecationReason, DeprecationStatus } from "../../../src/schema/deprecation.js";

const here = path.dirname(fileURLToPath(import.meta.url));
const OUT_DIR = path.resolve(here, "..", "src", "generated");

const HEADER =
  "// AUTO-GENERATED by packages/modelparams/scripts/codegen.ts. Do not edit by hand.\n" +
  "// Source of truth: the YAML catalog under /models in modelparams.dev.\n\n";

function tsType(p: Parameter): string {
  switch (p.type) {
    case "boolean":
      return "boolean";
    case "integer":
    case "number":
      return "number";
    case "string":
      return "string";
    case "enum":
      return p.values.map((v) => JSON.stringify(v)).join(" | ");
  }
}

function quoteKey(k: string): string {
  return /^[A-Za-z_$][\w$]*$/.test(k) ? k : JSON.stringify(k);
}

function emitParamsByIdEntry(m: Model): string {
  const id = modelId(m);
  const fields = m.params.map((p) => `    ${quoteKey(p.path)}: ${tsType(p)};`).join("\n");
  if (fields.length === 0) {
    return `  ${JSON.stringify(id)}: Record<string, never>;`;
  }

  return `  ${JSON.stringify(id)}: {\n${fields}\n  };`;
}

function emitDefaultsEntry(m: Model): string {
  const id = modelId(m);
  const entries = m.params
    .filter((p) => p.default !== undefined)
    .map((p) => `    ${quoteKey(p.path)}: ${JSON.stringify(p.default)},`)
    .join("\n");
  return entries.length > 0
    ? `  ${JSON.stringify(id)}: {\n${entries}\n  },`
    : `  ${JSON.stringify(id)}: {},`;
}

async function main(): Promise<void> {
  const [{ models, issues }, { deprecations, issues: deprecationIssues }] = await Promise.all([
    loadAllModels(),
    loadAllDeprecations(),
  ]);

  if (issues.length > 0) {
    console.error(`Catalog has ${issues.length} validation issue(s); refusing to codegen:`);
    for (const issue of issues) {
      console.error(`  ${issue.file}: ${issue.message}`);
    }
    process.exit(1);
  }

  if (deprecationIssues.length > 0) {
    console.error(
      `Deprecations have ${deprecationIssues.length} validation issue(s); refusing to codegen:`,
    );
    for (const issue of deprecationIssues) {
      console.error(`  ${issue.file}: ${issue.message}`);
    }
    process.exit(1);
  }

  await fs.mkdir(OUT_DIR, { recursive: true });

  const ids = models.map(modelId);
  const providers = [...new Set(models.map((m) => m.provider))].sort();
  const deprecationEntries = deprecations.map((d) => ({
    modelId: modelId(d),
    status: d.status,
    deprecatedAt: d.deprecatedAt,
    ...(d.sunsetAt !== undefined ? { sunsetAt: d.sunsetAt } : {}),
    ...(d.replacement !== undefined ? { replacement: d.replacement } : {}),
    reason: d.reason,
  }));

  // 1. model-ids.ts — ModelId union + Provider union
  await fs.writeFile(
    path.join(OUT_DIR, "model-ids.ts"),
    HEADER +
      `export const MODEL_IDS = ${JSON.stringify(ids, null, 2)} as const;\n\n` +
      `export type ModelId = (typeof MODEL_IDS)[number];\n\n` +
      `export const PROVIDERS = ${JSON.stringify(providers, null, 2)} as const;\n\n` +
      `export type Provider = (typeof PROVIDERS)[number];\n`,
  );

  // 2. params-by-id.ts — full parameter shape per model id (the typing payload)
  await fs.writeFile(
    path.join(OUT_DIR, "params-by-id.ts"),
    HEADER +
      `/**\n` +
      ` * Full parameter shape for each model id. The headline \`ParamsOf<Id>\` type in\n` +
      ` * \`../types\` is \`Partial<ParamsById[Id]>\` so consumers can set only the\n` +
      ` * parameters they want to override.\n` +
      ` */\n` +
      `export type ParamsById = {\n${models.map(emitParamsByIdEntry).join("\n")}\n};\n`,
  );

  // 3. defaults.ts — per-model defaults from the catalog
  await fs.writeFile(
    path.join(OUT_DIR, "defaults.ts"),
    HEADER +
      `import type { ModelId } from "./model-ids.js";\n` +
      `import type { ParamsById } from "./params-by-id.js";\n\n` +
      `export const DEFAULTS = {\n${models.map(emitDefaultsEntry).join("\n")}\n} as const satisfies { [K in ModelId]: Partial<ParamsById[K]> };\n`,
  );

  // 4. data.ts — runtime catalog (full Model objects + BY_ID lookup)
  await fs.writeFile(
    path.join(OUT_DIR, "data.ts"),
    HEADER +
      `import type { ModelId } from "./model-ids.js";\n\n` +
      `export const CATALOG = ${JSON.stringify(models, null, 2)} as const;\n\n` +
      `export type CatalogEntry = (typeof CATALOG)[number];\n\n` +
      `function authSuffix(authType: CatalogEntry["authType"]): "" | "-subscription" {\n` +
      `  return authType === "api_key" ? "" : "-subscription";\n` +
      `}\n\n` +
      `export const BY_ID: Readonly<Record<ModelId, CatalogEntry>> = Object.freeze(\n` +
      `  Object.fromEntries(\n` +
      `    CATALOG.map((m) => [\`\${m.provider}/\${m.model}\${authSuffix(m.authType)}\`, m]),\n` +
      `  ),\n` +
      `) as Readonly<Record<ModelId, CatalogEntry>>;\n`,
  );

  // 5. provider-endpoints.ts — base URLs an SDK configures per provider
  const endpoints = loadProviderEndpoints();
  await fs.writeFile(
    path.join(OUT_DIR, "provider-endpoints.ts"),
    HEADER + `export const PROVIDER_ENDPOINTS = ${JSON.stringify(endpoints, null, 2)} as const;\n`,
  );

  // 6. deprecations.ts — deprecated/sunset/removed models and their replacements
  const statusUnion = DeprecationStatus.options.map((o) => JSON.stringify(o)).join(" | ");
  const reasonUnion = DeprecationReason.options.map((o) => JSON.stringify(o)).join(" | ");
  await fs.writeFile(
    path.join(OUT_DIR, "deprecations.ts"),
    HEADER +
      `export type DeprecationStatus = ${statusUnion};\n\n` +
      `export type DeprecationReason = ${reasonUnion};\n\n` +
      `export interface DeprecationEntry {\n` +
      `  modelId: string;\n` +
      `  status: DeprecationStatus;\n` +
      `  deprecatedAt: string;\n` +
      `  sunsetAt?: string;\n` +
      `  replacement?: string;\n` +
      `  reason: DeprecationReason;\n` +
      `}\n\n` +
      `export const DEPRECATIONS: readonly DeprecationEntry[] = ${JSON.stringify(deprecationEntries, null, 2)};\n\n` +
      `export const DEPRECATIONS_BY_ID: Readonly<Record<string, DeprecationEntry>> = Object.freeze(\n` +
      `  Object.fromEntries(DEPRECATIONS.map((d) => [d.modelId, d])),\n` +
      `);\n`,
  );

  // 7. index.ts — barrel for the generated dir
  await fs.writeFile(
    path.join(OUT_DIR, "index.ts"),
    HEADER +
      `export * from "./model-ids.js";\n` +
      `export * from "./params-by-id.js";\n` +
      `export * from "./defaults.js";\n` +
      `export * from "./data.js";\n` +
      `export * from "./provider-endpoints.js";\n` +
      `export * from "./deprecations.js";\n`,
  );

  // Reference authSuffix so its `import` isn't tree-shaken from the type-checker's view.
  void authSuffix;

  console.log(
    `codegen: wrote 7 files for ${models.length} models across ${providers.length} providers (${deprecations.length} deprecations) → ${path.relative(process.cwd(), OUT_DIR)}/`,
  );
}

main().catch((err) => {
  console.error("codegen crashed:", err);
  process.exit(1);
});
