# AUTO-GENERATED by packages/modelparams-python/scripts/codegen.ts.
# Do not edit by hand; the YAML catalog under /models is the source of truth.

from typing import Literal

from typing_extensions import NotRequired, TypedDict

DeprecationStatus = Literal["deprecated", "sunset", "removed"]
DeprecationReason = Literal["superseded", "retired", "renamed", "removed"]

class DeprecationEntry(TypedDict):
    modelId: str
    status: DeprecationStatus
    deprecatedAt: str
    sunsetAt: NotRequired[str]
    replacement: NotRequired[str]
    reason: DeprecationReason

DEPRECATIONS: tuple[DeprecationEntry, ...] = ()

DEPRECATIONS_BY_ID: dict[str, DeprecationEntry] = {entry["modelId"]: entry for entry in DEPRECATIONS}
